### ISSUE TITLE
updateselectinput label parameter doesn't work in observe or observeEvent

### ISSUE THREAD

**Issue by davlee1972** [rstudio/shiny#1499] opened 2016-12-10 15:13 UTC
The label parameter has no effect when calling updateSelectInput or updateSelectizeInput. I can see the code executing in the debugger and I've been able to change the list of choices, but the label of the selectinput never changes.

When the user picks a chart type (radio button) I want to change the labels of the measure category selectinputs as outlined below. The select inputs define both what type of data is being filtered and type of data is reflected on charts. Scatter, Histograms, etc..

ur.R
                                      radioButtons(ns("chart_type"), "Chart Type",
                                                   choices=c("Histogram" = "histogram", "Scatter" = "scatter", "Box" = "box"),
                                                   selected = "histogram", inline = FALSE
                                      ),
                         selectInput(inputId = ns("measure_filter1"), label = "Measure Ranges", width = '100%', choices = screener_cols, selected = "age"),
                         numericInput(inputId = ns("measure_filter1_low"), label = NULL, value = NA),
                         numericInput(inputId = ns("measure_filter1_high"), label = NULL, value = NA),
                         sliderInput(ns("measure_filter1_mad"), "Median Absolute Deviations", min = 0, max = 10, value = 0, width = '100%'),
                         checkboxInput(inputId = ns("measure_filter1_na"), label = "Exclude Missing", value = FALSE),
                         actionButton(inputId = ns("measure_filter1_clear"), label = "Clear"),
                         hr(),
                         selectInput(inputId = ns("measure_filter2"), label = "Measure Ranges", width = '100%', choices = screener_cols, selected = "population"),
                         numericInput(inputId = ns("measure_filter2_low"), label = NULL, value = NA),
                         numericInput(inputId = ns("measure_filter2_high"), label = NULL, value = NA),
                         sliderInput(ns("measure_filter2_mad"), "Median Absolute Deviations", min = 0, max = 10, value = 0, width = '100%'),
                         checkboxInput(inputId = ns("measure_filter2_na"), label = "Exclude Missing", value = FALSE),
                         actionButton(inputId = ns("measure_filter2_clear"), label = "Clear")

server.R:
 observeEvent(input$chart_type,
                if (input$chart_type == "scatter") {
                  updateSelectInput(session = session, inputId = "measure_filter1", label = "Chart Measure - X Axis")
                  updateSelectInput(session = session, inputId = "measure_filter2", label = "Chart Measure - Y Axis")
                }
                else {
                  updateSelectInput(session = session, inputId = "measure_filter1", label = "Chart Measure")
                  updateSelectInput(session = session, inputId = "measure_filter2", label = "Measure Ranges")
                }
  )

**Comment by davlee1972** [comment] 2016-12-10 15:21
I added some additional testing code to verify it just impacts selectinput(s)

The label does change for the numeric slider..
        updateSelectInput(session = session, inputId = "measure_filter1", label = "Chart Measure")
        updateSelectInput(session = session, inputId = "measure_filter2", label = "Measure Ranges")
        updateSliderInput(session = session, inputId = "measure_filter1_mad", label = "test")

**Comment by davlee1972** [comment] 2016-12-10 16:00
I found a workaround by adding a extra textOutput widget and avoiding the use of selectInput labels entirely

                         strong(textOutput(outputId = ns("measure_filter1_text"))),
                         br(),
                         selectInput(inputId = ns("measure_filter1"), label = NULL, width = '100%', choices = screener_cols, selected = "PE_FY0"),


  output$measure_filter1_text = renderText({
     if (input$chart_type == "scatter") {
        "Chart Measure - X Axis"
      }
      else {
        "Chart Measure"
      }
  })

**Comment by alandipert** [comment] 2019-05-01 18:23
Thank you for the report. Closing as a duplicate of #2254

**Closed by alandipert** 2019-05-01 18:23 UTC
