### ISSUE TITLE
shinyAppDir(appDir) does not source global.R

### ISSUE THREAD

**Issue by mbacou** [rstudio/shiny#1911] opened 2017-12-20 02:16 UTC
Related to flexdashboard issue at https://github.com/rstudio/flexdashboard/issues/66#issuecomment-352913997

Trying to include an external shiny app inside a flexdashboard using `shinyAppDir(appDir)` following the example at http://rmarkdown.rstudio.com/flexdashboard/shiny.html#external_applications. The shiny app is iframed as expected, but the app errors out as it fails to source code in `global.R` inside `appDir` (e.g. loading datasets).

Sorry no RE just now!

**Comment by daattali** [comment] 2018-01-05 06:01
I think this is a duplicate of https://github.com/rstudio/shiny/issues/1063

**Closed** 2018-04-11 19:03 UTC
