### ISSUE TITLE
updateSelectInput label not anymore updated in 1.2.0

### ISSUE THREAD

**Issue by dylancis** [rstudio/shiny#2288] opened 2018-12-18 23:18 UTC
The 1.2.0 shiny example [here ](https://shiny.rstudio.com/reference/shiny/1.2.0/updateSelectInput.html) is not working anymore in shiny 1.2.0 - the label does not get updated anymore.

Try the below code and the label remains unchanged whatever you select (A/B/C):

```
## Only run examples in interactive R sessions
if (interactive()) {
  
  ui <- fluidPage(
    p("The checkbox group controls the select input"),
    checkboxGroupInput("inCheckboxGroup", "Input checkbox",
                       c("Item A", "Item B", "Item C")),
    selectInput("inSelect", "Select input",
                c("Item A", "Item B", "Item C"))
  )
  
  server <- function(input, output, session) {
    observe({
      x <- input$inCheckboxGroup
      
      # Can use character(0) to remove all choices
      if (is.null(x))
        x <- character(0)
      
      # Can also set the label and select items
      updateSelectInput(session, "inSelect",
                        label = paste("Select input label", length(x)),
                        choices = x,
                        selected = tail(x, 1)
      )
    })
  }
  shinyApp(ui, server)
}

```

I have tried the same with shiny 1.1.0 and it worked fine, the issue happened in 1.2.0

**Comment by gagecarto** [comment] 2018-12-28 19:00
This is probably a duplicate or has the same cause as https://github.com/rstudio/shiny/issues/2245. Hoping to see this resolved asap

**Comment by dylancis** [comment] 2018-12-28 19:06
You are right. Thanks very much @gagecarto

**Comment by wch** [comment] 2019-01-02 20:01
It is indeed a duplicate of #2245, and is fixed in the development version of shiny, which you can install with:

```
devtools::install_github('rstudio/shiny')
```

**Closed by wch** 2019-01-02 20:01 UTC
