### ISSUE TITLE
Shiny unit tests fail with dev ggplot2

### ISSUE THREAD

**Issue by hadley** [rstudio/shiny#2059] opened 2018-05-15 22:23 UTC
```
      ══ testthat results  ═══════════════════════════════════════════════════════════
      OK: 615 SKIPPED: 3 FAILED: 8
      1. Failure: ggplot coordmap (@test-plot-coordmap.R#34) 
      2. Failure: ggplot coordmap (@test-plot-coordmap.R#63) 
      3. Failure: ggplot coordmap (@test-plot-coordmap.R#73) 
      4. Failure: ggplot coordmap with facet_wrap (@test-plot-coordmap.R#106) 
      5. Failure: ggplot coordmap with facet_grid (@test-plot-coordmap.R#155) 
      6. Failure: ggplot coordmap with facet_grid (@test-plot-coordmap.R#192) 
      7. Failure: ggplot coordmap with 2D facet_grid (@test-plot-coordmap.R#243) 
      8. Failure: ggplot coordmap with various scales and coords (@test-plot-coordmap.R#336) 
      
      Error: testthat unit tests failed
      Execution halted
```

**Comment by wch** [comment] 2018-05-15 23:47
I think this is a dupe of #2016 and was fixed in #2026.

**Closed by wch** 2018-05-15 23:47 UTC
