### ISSUE TITLE
`shinyOptions()` and `options()` not working as expected

### ISSUE THREAD

**Issue by tomicapretto** [rstudio/shiny#2948] opened 2020-06-29 20:33 UTC
### Describe the problem in detail

I am trying to call a custom function defined in my server function when an error occurs at anytime in any part of my app so I'm trying to set the `shiny.error` option to a custom function.

The documentation in `?getShinyOption` the following about setting options: 
>  If options are set from global.R, app.R, ui.R, or server.R, or if they are set from inside the server function, then the options will be scoped to the application. When the application exits, the new option set is discarded and the global option set is restored.

But I am facing the following issues (let's say we want to call `recover()`) 

* `shinyOptions(shiny.error = recover)` seems not to work. No matter I place it within my server function or outside it, the app closes when an error occurs and `recover()` is not called.
* `options(shiny.error  = recover)` works both when set from outside or inside the server function. But the option persists after the application exits, which I didn't expect when setting from within server.

My ultimate goal is to call a function that shows a notification and restarts the application by calling to `session$reload()`.  But in this case, I found the following issues:

* If I place `options(shiny.error = session$reload)` within my server function, it has no effect.
* I tried to wrap it in a function `options(shiny.error = function() session$reload())` , but it didn't work either.
* And I finally  tried with `options(shiny.error = session$reload())` from inside the server function. But since I am making the call, the application gets reloaded all the time (I'm not sure if this is the continuous reloading is the expected behavior).

### Examples

1. Placing `shinyOptions(shiny.error=recover)` within server function. Does not work.

```R
shinyApp(
  ui = fluidPage(
    actionButton("btn", "Throw error!")
  ),
  server = function(input, output, session) {
    shinyOptions(shiny.error=recover)
    observeEvent(input$btn, {
      stop("Error!")
    })
  }
)
```
2. Placing `shinyOptions(shiny.error=recover)` outside the server function. Does not work.

```R
shinyOptions(shiny.error=recover)
shinyApp(
  ui = fluidPage(
    actionButton("btn", "Throw error!")
  ),
  server = function(input, output, session) {
    observeEvent(input$btn, {
      stop("Error!")
    })
  }
)
```

3. `options(shiny.error=recover)` outside server function. Works and the option persists, as expected.

```R
options(shiny.error=recover)
shinyApp(
  ui = fluidPage(
    actionButton("btn", "Throw error!")
  ),
  server = function(input, output, session) {
    observeEvent(input$btn, {
      stop("Error!")
    })
  }
)
# ... recover() messages/output
# Enter a frame number, or 0 to exit ...
# ... long output with all the options

options("shiny.error")
# prints `recover()` body.
```

4. `options(shiny.error=recover)` within server function. Works, but the option persists, which is not what I expected.

```R
shinyApp(
  ui = fluidPage(
    actionButton("btn", "Throw error!")
  ),
  server = function(input, output, session) {
    options(shiny.error=recover)
    observeEvent(input$btn, {
      stop("Error!")
    })
  }
)
# ... recover() messages/output
# Enter a frame number, or 0 to exit ...
# ... long output with all the options

options("shiny.error")
# prints `recover()` body.
```

### System details

Output of `sessionInfo()`:
```
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=Spanish_Argentina.1252  LC_CTYPE=Spanish_Argentina.1252   
[3] LC_MONETARY=Spanish_Argentina.1252 LC_NUMERIC=C                      
[5] LC_TIME=Spanish_Argentina.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_1.5.0

loaded via a namespace (and not attached):
 [1] compiler_3.6.3  fastmap_1.0.1   magrittr_1.5    R6_2.4.1        promises_1.1.0 
 [6] later_1.0.0     htmltools_0.5.0 tools_3.6.3     Rcpp_1.0.4.6    jsonlite_1.6.1 
[11] digest_0.6.25   xtable_1.8-4    httpuv_1.5.2    mime_0.9        rlang_0.4.6   
```

**Comment by cpsievert** [comment] 2020-06-30 21:42
Thanks for the report! The documentation on `?shinyOptions` is currently misleading/wrong (see #2953). That is, you currently have to use `options()` (not `shinyOptions()`) for the `shiny.*` options documented on `shinyOptions()` (confusing, I know). 

Closing since this is essentially a duplicate of #2953

**Closed by cpsievert** 2020-06-30 21:42 UTC
