### ISSUE TITLE
ggplot disappears on browser zoom (firefox and chrome) on mac and windows

### ISSUE THREAD

**Issue by vnijs** [rstudio/shiny#781] opened 2015-03-27 00:36 UTC
When using grid-arrange with ggplot2 plots disappear if the user zooms in or out in chrome and firefox on mac and windows. Reproducible examples below. This only happens when calling plots from a reactive (plot_vt_reactive) but not when called from a 'regular' function (plot_vt). I have the same problem with base R plots using par for multiple plots. Without grid.arrange zooming in-out works fine.

``` r
library(shiny)
library(ggplot2)
library(gridExtra)

ui <- bootstrapPage(
  tabPanel("Plot", plotOutput("plot_vt"))
)

server <- function(input, output, session) {
  output$plot_vt <- renderPlot({
    plot_vt_reactive()
    # plot_vt()
  }, width=400, height=400)

  plot_vt_reactive <- reactive({
    plot_vt()
  })

  plot_vt <- function() {
    dat <- data.frame(a = rnorm(100), b = rnorm(100))
    p <- list()
    p[[1]] <- ggplot(dat, aes(x=a)) + geom_histogram(binwidth = .5)
    p[[2]] <- ggplot(dat, aes(x=b)) + geom_histogram(binwidth = .5)
    do.call(grid.arrange, c(p, list(ncol = 1)))
    # without grid.arrange the reactive works fine
    # p[[1]]
  }
}

shinyApp(ui = ui, server = server)
```

**Comment by wch** [comment] 2015-03-27 20:55
Interesting... it turns out this isn't a ggplot2 or grid issue. It even happens with a base graphics plot, in Firefox and Chrome (but not Safari):

```R
library(shiny)

ui <- bootstrapPage(
  tabPanel("Plot", plotOutput("plot_vt"))
)

server <- function(input, output, session) {
  output$plot_vt <- renderPlot({
    print("plot output")
    plot_vt_reactive()
  }, width=400, height=400)

  plot_vt_reactive <- reactive({
    plot(1:5, 1:5)
  })
}

shinyApp(ui = ui, server = server)
```

I believe this is the intersection of two things:
* When zooming in these browsers, a new image is requested, probably because the height or width changes.
* The plot is generated as a *side effect* of the reactive, not as the return value. (In contrast, `ggplot()` returns a ggplot object, which gets printed by `renderPlot()`.) Usually, the reactive runs and the plot output gets captured. But it's possible to invalidate the `renderPlot()` without invalidating the plot-generating reactive, and in this case, when the `renderPlot()` code re-executes, it uses the cached value of the reactive (which is NULL), and there's no plot output to capture.

This example illustrates with an `actionButton`:

```R
library(shiny)

ui <- fluidPage(
  actionButton("newplot", "New Plot"),
  plotOutput("plot_vt")
)

server <- function(input, output, session) {
  output$plot_vt <- renderPlot({
    input$newplot
    plot_vt_reactive()
  }, width=300, height=300)

  plot_vt_reactive <- reactive({
    plot(1:5, 1:5)
  })
}

shinyApp(ui = ui, server = server)
```

As a workaround, if you can get `grid.arrange` to return a `print`able object (like `ggplot` does), then I think this should work, though I'm not 100% sure.

To really fix the problem might be difficult.

**Comment by vnijs** [comment] 2015-03-27 23:34
Great suggestion @wch ! After some searching I found arrangeGrob. Add a print statement to renderplot and the plot remains visible when zooming. The plot also stays the same (i.e., rnorm is not called when zooming in/out). Working example below.

Questions:
- How likely is a 'fix' in Shiny for this issue in the near future?
- I am not sure a work-around similar to the approach with arrangeGrob is possible for base graphics. Any suggestions/comments?
- Using arrangeGrob means that when the plot methods in my app are called outside of a ShinyApp you have to use plot( ) %>% print. I don't want users to have to do that. Is there an easy way to determine if a function is called from within a ShinyApp (either local or on a server)? I have some ideas for a workaround but nothing that is very clean.

library(shiny)
library(ggplot2)
library(gridExtra)

ui <- bootstrapPage(
  tabPanel("Plot", plotOutput("plot_vt"))
)

server <- function(input, output, session) {
  output$plot_vt <- renderPlot({
    plot_vt_reactive() %>% print
  }, width=400, height=400)
  
  plot_vt_reactive <- reactive({
    dat <- data.frame(a = rnorm(100), b = rnorm(100))
    p <- list()
    p[[1]] <- ggplot(dat, aes(x=a)) + geom_histogram(binwidth = .5)
    p[[2]] <- ggplot(dat, aes(x=b)) + geom_histogram(binwidth = .5)
    # based on http://stackoverflow.com/questions/17059099/saving-grid-arrange-plot-to-file
    do.call(arrangeGrob, c(p, list(ncol = 1)))
  })
}

shinyApp(ui = ui, server = server)

**Comment by wch** [comment] 2015-03-28 01:05
I'm not entirely sure that it's going to be possible to have a real fix. The problem is that, strictly speaking, the imperative plot functions break the reactive flow model because they don't return their values; we just simulate it by capturing the PNG file generated.

That said, I was able to whip together a workaround. I wrote a function, `capture_plot`, which captures an expression and environment, and returns them in an object which can later be `print`ed.

In this example, note that the `rand()` gets called (and gives different values) each time the expression is evaluated, but this is unavoidable even without this workaround.

```R
capture_plot <- function(expr, env = parent.frame()) {
  structure(
    list(expr = substitute(expr), env = env),
    class = "capture_plot"
  )
}

print.capture_plot <- function(x, ...) {
  eval(x$expr, x$env)
}

ui <- fluidPage(
  actionButton("newplot", "New Plot"),
  plotOutput("plot_vt")
)

server <- function(input, output, session) {
  output$plot_vt <- renderPlot({
    input$newplot
    plot_vt_reactive()
  }, width=300, height=300)

  plot_vt_reactive <- reactive({
    capture_plot( plot(rnorm(5), rnorm(5)) )
  })
}

shinyApp(ui = ui, server = server)
```

This might be able to serve as the basis for a full fix in Shiny, but we'll have to think about it a bit more.

**Comment by vnijs** [comment] 2015-03-29 05:20
I will try this for base graphics. Thanks Winston. It seems that the preferable solution would still be to return a printable object so I will use arrangeGrob where possible.

**Comment by baptiste** [comment] 2015-07-10 00:26
see also https://github.com/baptiste/gridextra/blob/master/inst/testing/shiny.R
for a related workaround to display gtables (now also the class of arrangeGrob). Could renderPlot() be modified to use a more specific drawing method than the generic print()? ggplot2 recently gained a grid.draw.ggplot method, I wonder if a generic draw method could be defined, with methods for base, trellis, ggplot, gtable, and grobs, and used instead of print in renderPlot/.

**Comment by dkulp2** [comment] 2016-06-14 13:27
The workaround that @wch offered above no longer works (if it ever did) for me. Using that code, I get a blank page. (A [similar proposed workaround](https://github.com/baptiste/gridextra/blob/master/inst/testing/shiny.R) by @baptiste also no longer works.) It appears that the print method is not called. Is the behavior different now due to the change in how renderPlot chooses to call print() as mentioned in #841?
Is there a new workaround to the general problem that objects such as gtable cannot display in Shiny?

**Comment by wch** [comment] 2016-06-14 14:53
@dkulp2 What version of Shiny are you using, and what browser? The workaround code (with `rand()`) works for me. I'm using the development version of Shiny, Chrome 51.0.2704.84, and Firefox 47.0

**Comment by dkulp2** [comment] 2016-06-15 13:28
My apologies.

First, the plot_capture wrapper does not seem to work. The print method
doesn't get called as far as I can tell.

However, using Shiny 0.13.2 (release or development), I *am *able to have
my return object displayed - whether it's a call to plot or otherwise (if I
just use vanilla Shiny return values and don't wrap the result in
plot_capture).

I became confused by the workaround because I was having troubles
displaying a gtable and thought that the problem was this issue. In fact, I
just needed to call grid.arrange() as under normal non-Shiny usage.

So, in sum, I'm not sure that the problem described in this issue is still
a problem at all. And for my specific interest, displaying grobs seems to
work fine using something like

 renderPlot({ grid.arrange(arrangeGrob(p1,p2)) })

**Comment by baptiste** [comment] 2016-06-15 20:22
I don't know if it's related but `ggsave()` recently switched from calling `print()` to `grid.draw()`; if such a change happened here, that would explain why the print workaround no longer works, while grobs work just fine.

**Comment by jcheng5** [comment] 2016-06-15 20:55
Plotting simply should not be done in a reactive. Plotting is a side effecty operation, and reactives are only useful for their return values.

Either of these two solutions should work:

1. Convert the reactive that does the plotting to a no-arg function. `foo <- reactive({ plot(...) })` becomes `foo <- function() { plot(...) }`. This is the best solution IMHO.
2. Convert the reactive to actually return a useful value that can be used to plot with.

```r
plot_reactive <- reactive({
  plot(rnorm(10), rnorm(10))
  recordPlot()
})

output$plot <- renderPlot({
  replayPlot(plot_reactive())
})
```

There's not really an advantage to doing this though. Just pointing out that it's possible because `recordPlot` almost magically turns a side effect into a value.

**Comment by alandipert** [comment] 2019-04-26 15:18
Based on my read of this thread, I don't believe it represents a bug or a feature request, so I will close it. Essentially: plotting in a reactive only ever worked incidentally.

If I misunderstand, please don't hesitate to comment or create a new issue.

**Closed by alandipert** 2019-04-26 15:18 UTC
