### ISSUE TITLE
Using `dateInput` with value = NA leads to error in browser on `updateDateInput`

### ISSUE THREAD

**Issue by lbusett** [rstudio/shiny#2663] opened 2019-10-15 09:37 UTC
### System details

Browser Version: 

Output of `sessionInfo()`:

```
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=it_IT.UTF-8    LC_MESSAGES=en_GB.UTF-8    LC_PAPER=it_IT.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=it_IT.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] bfsapps_1.0.3         leafem_0.0.2          rgeos_0.5-2           rgdal_1.4-6           gstat_2.0-3          
 [6] ggplot2_3.2.1         raster_3.0-7          sp_1.3-1              SearchTrees_0.5.2     shinyWidgets_0.4.9   
[11] velox_0.2.0           shinycssloaders_0.2.0 openxlsx_4.1.0.1      shinyalert_1.0        DT_0.9               
[16] data.table_1.12.4     dplyr_0.8.3           shinyFiles_0.7.3      shinydashboard_0.7.1  pals_1.5             
[21] maps_3.3.0            rhandsontable_0.3.7   mapview_2.7.0         sf_0.8-0              shinyjs_1.0          
[26] leaflet_2.0.2         shiny_1.4.0.9000      testthat_2.2.1       

loaded via a namespace (and not attached):
  [1] backports_1.1.5         lwgeom_0.1-7            lazyeval_0.2.2          crosstalk_1.0.0        
  [5] listenv_0.7.0           usethis_1.5.1.9000      digest_0.6.21           foreach_1.4.7          
  [9] htmltools_0.4.0         gdata_2.18.0            magrittr_1.5            checkmate_1.9.4        
 [13] memoise_1.1.0           cluster_2.1.0           doParallel_1.0.15       remotes_2.1.0          
 [17] readr_1.3.1             globals_0.12.4          doFuture_0.8.1          R.utils_2.9.0          
 [21] xts_0.11-2              prettyunits_1.0.2       colorspace_1.4-1        rappdirs_0.3.1         
 [25] xfun_0.10               callr_3.3.2             crayon_1.3.4            jsonlite_1.6           
 [29] zeallot_0.1.0           zoo_1.8-6               iterators_1.0.12        glue_1.3.1             
 [33] gtable_0.3.0            webshot_0.5.1           V8_2.3                  pkgbuild_1.0.6         
 [37] kernlab_0.9-27          prabclus_2.3-1          DEoptimR_1.0-8          scales_1.0.0           
 [41] DBI_1.0.0               miniUI_0.1.1.1          Rcpp_1.0.2              viridisLite_0.3.0      
 [45] xtable_1.8-4            units_0.6-5             foreign_0.8-72          mapproj_1.2.6          
 [49] mclust_5.4.5            stats4_3.6.1            intervals_0.15.1        htmlwidgets_1.5.1      
 [53] httr_1.4.1              RColorBrewer_1.1-2      FNN_1.1.3               fpc_2.2-3              
 [57] modeltools_0.2-22       ellipsis_0.3.0          pkgconfig_2.0.3         R.methodsS3_1.7.1      
 [61] flexmix_2.3-15          nnet_7.3-12             tidyselect_0.2.5        rlang_0.4.0            
 [65] manipulateWidget_0.10.0 later_1.0.0             munsell_0.5.0           tools_3.6.1            
 [69] cli_1.1.0               devtools_2.2.1          shinyBS_0.61            evaluate_0.14          
 [73] stringr_1.4.0           fastmap_1.0.1           yaml_2.2.0              processx_3.4.1         
 [77] knitr_1.25              fs_1.3.1                zip_2.0.4               robustbase_0.93-5      
 [81] rgl_0.100.30            purrr_0.3.2             satellite_1.0.1         packrat_0.5.0          
 [85] future_1.14.0           mime_0.7                R.oo_1.22.0             tictoc_1.0             
 [89] compiler_3.6.1          rstudioapi_0.10         curl_4.2                plotly_4.9.0           
 [93] png_0.1-7               e1071_1.7-2             spacetime_1.2-2         tibble_2.1.3           
 [97] stringi_1.4.3           ps_1.3.0                desc_1.2.0              forcats_0.4.0          
[101] lattice_0.20-38         classInt_0.4-1          vctrs_0.2.0             stringdist_0.9.5.3     
[105] fasterize_1.0.0         lifecycle_0.1.0         pillar_1.4.2            maptools_0.9-8         
[109] httpuv_1.5.2            R6_2.4.0                promises_1.1.0          KernSmooth_2.23-15     
[113] sessioninfo_1.1.1       codetools_0.2-16        gdalUtils_2.0.1.14      dichromat_2.0-0        
[117] gtools_3.8.1            MASS_7.3-51.4           assertthat_0.2.1        pkgload_1.0.2          
[121] rprojroot_1.3-2         withr_2.1.2             hms_0.5.1               diptest_0.75-7         
[125] grid_3.6.1              tidyr_1.0.0             class_7.3-15            rmarkdown_1.16         
[129] lubridate_1.7.4         base64enc_0.1-3 
```

### Example application *or* steps to reproduce the problem

 

```R
ui <- fluidPage(
  
  dateInput("date2", "Date:", value = NA)
  
)

shinyApp(ui, server = function(input, output, session) { 
  
  shiny::observe(shiny::updateDateInput(
    session, "date2", "Data trattamento", value = "2015-01-01",
    min = as.Date("1950-01-01"),
    max = as.Date("2019-01-01")))
})
```

### Describe the problem in detail

Starting shiny 1.4.0, if I initialize a `dateInput()` with value = NAand then try to update it with `updateDateInput`, I get the following error when "inspecting" the app in chrome: 

![image](https://user-images.githubusercontent.com/4480397/66817562-318e5b00-ef3c-11e9-9c50-e12e9755294d.png)

In the example app above, this does not appear to have ill effects, but in a quite complex app I am developing (which used to work before the update), it appears to completely break reactivity (sorry, I was not able to understand how and why the reported error affects my app...).  Removing the initialization to NA solves the issue.

I know it is a very particular case, but it took me a while to figure this out, and maybe someone else will stumble upon this. 

HTH.

**Comment by AElborolosyNBA** [comment] 2019-10-28 14:54
I have a similar issue where using updateDateInput leads to a "Uncaught TypeError: Cannot read property 'getTime' of null" when starting w/ an NA default.

**Comment by HarrisonHenri** [comment] 2019-11-22 16:05
Indeed, this error also ocurr in dateInput element.

**Comment by cpsievert** [comment] 2020-09-09 17:16
Closing as this as a duplicate of https://github.com/rstudio/shiny/issues/2703 which will be fixed by https://github.com/rstudio/shiny/pull/3038

**Closed by cpsievert** 2020-09-09 17:16 UTC
