### ISSUE TITLE
Possible memory leak reactiveFileReader

### ISSUE THREAD

**Issue by RichardHooijmaijers** [rstudio/shiny#2321] opened 2019-02-06 09:35 UTC
I know there are a couple of issues that are linked (e.g #1551 #2021) but thought this might be considered as a new issue. 

If I run a slightly adapted version of the `reactiveFileReader` example, my memory seems to increase quite a bit when the app runs for a longer time (e.g. >12h). This happens with the following code:

```
library(shiny)
ui <- fluidPage(
  verbatimTextOutput("monitor_txt")
)
server <- function(input, output, session) {
  monitor_out <- reactiveFileReader(500,session,"memtext.txt", readLines)
  output$monitor_txt <- renderText({paste(monitor_out(), collapse = '\n')})
}
shinyApp(ui, server,options=list(launch.browser=TRUE))
```

The memory increase by a couple of hundred mb in 12h. Something similar is seen when I read in the file 'manually' in combination with `invalidateLater`. The file being read is not very large (10-100kb). This was tested in R 3.4.2 with shiny 1.2.0 on ubuntu 16.04

Any help on this is would b very helpful!

**Comment by Jingadilian** [comment] 2019-03-20 11:04
@RichardHooijmaijers thank you so much for posting this issue!

I have been trying figure out why my app also increased in memory usage even when idle. For example, after sitting idle for one hour it usually increased by 500mb.

Preliminary results suggests that removing my 5 x reactiveFileReader has fixed the issue.

**Comment by shrektan** [comment] 2019-03-20 23:08
I have the same experience. One of my app uses `reactiveFileReader()`. The memory starts from 100mb. After 12 or 24 hours, it bumps to 1gb or more. Adding a `gc()` doesn’t help. So I doubt it’s a memory leak.

**Comment by alandipert** [comment] 2019-03-30 07:26
I think I saw something like this too. I made the following app to demonstrate the increased memory usage over time, and the fact that `gc()` doesn't appear to help:

```R
library(shiny)

ui <- fluidPage(
  plotOutput("plot"),
  verbatimTextOutput("stats"),
  actionButton("gcButton", "GC")
)

server <- function(input, output, session) {
  continue <- TRUE
  hist <- reactiveVal(data.frame())
  poll <- function() {
    if (continue) {
      cat("foo\n", file = "somefile")
      later::later(poll, 0.02)
    }
  }
  poll()
  onStop(function() { 
    continue <<- FALSE
    unlink("somefile")
  })
  
  reader <- reactiveFileReader(100, session, "somefile", readLines)
  
  observeEvent(reader(), {
    hist(rbind(hist(), data.frame(
      mem = as.numeric(pryr::mem_used()),
      time = Sys.time()
    )))
  })
  
  output$plot <- renderPlot({
    plot(hist(), type = "l")
  })
  
  output$stats <- renderText({
    sprintf("Start time: %s\nStart mem: %s\nCurrent time: %s\nCurrent mem: %s",
      toString(head(hist(), 1)$time),
      utils:::format.object_size(head(hist(), 1)$mem, "auto"),
      toString(tail(hist(), 1)$time),
      utils:::format.object_size(tail(hist(), 1)$mem, "auto")
    )
  })
  
  observeEvent(input$gcButton, {
    cat("GCing...\n")
    gc()
  })
}

shinyApp(ui, server,options=list(launch.browser=TRUE))
```

**Comment by alandipert** [comment] 2019-04-04 22:12
Worked with @jcheng5 and arrived at a smaller repro:
```R
setInterval <- function(func, interval) {
  poll <- function() {
    func()
    later::later(poll, interval)
  }
  poll()
}

setInterval(function() {
  message(pryr::mem_used())
}, 2)

library(shiny)

rv <- reactiveValues(x = 0L)
observe({ rv$x })

setInterval(function() {
  rv$x <- isolate(rv$x) + 1L
  shiny:::flushReact()
}, 0.05)
```

**Comment by jcheng5** [comment] 2019-04-05 00:16
🤔 

```r
# Fill global string pool
for (i in 1:512) {
  paste(i)
}

dependents <- new.env(parent = emptyenv())
while (TRUE) {
  message(pryr::mem_used())
  for (i in 1:1000) {
    x <- as.character(runif(1))
    # If you comment out the next line, no leak...
    exists(x, envir = dependents, inherits = FALSE)
  }
}
```

```
─ Session info ────────────────────────────────────────────────────────────────────────────────
 setting  value                                      
 version  R version 3.5.1 Patched (2018-10-15 r75450)
 os       macOS Sierra 10.12.3                       
 system   x86_64, darwin15.6.0                       
 ui       RStudio                                    
 language (EN)                                       
 collate  en_US.UTF-8                                
 ctype    en_US.UTF-8                                
 tz       America/Los_Angeles                        
 date     2019-04-04                                 
```

**Comment by alandipert** [comment] 2019-04-05 06:47
I haven't looked at where we use `exists` and so I can't contribute any solution ideas yet, but I think the problem is: `exists` makes a symbol out of its argument and that symbol is interned in the global symbol table and remains there indefinitely.

1. `base::exists()` calls the the `.Internal` function `exists()`, which [maps](https://github.com/wch/r-source/blob/13cf48bc8e190f214a340ce86f11f667962dd633/src/main/names.c#L244) to the C function [`do_get`](https://github.com/wch/r-source/blob/13cf48bc8e190f214a340ce86f11f667962dd633/src/main/envir.c#L1998)
1. `do_get` [calls `installTrChar`](https://github.com/wch/r-source/blob/13cf48bc8e190f214a340ce86f11f667962dd633/src/main/envir.c#L2011)
1. `installTrChar` calls [install](https://github.com/wch/r-source/blob/13cf48bc8e190f214a340ce86f11f667962dd633/src/main/names.c#L1220)
1. `install` adds the new symbol to the global symbol table [R_SymbolTable](https://github.com/wch/r-source/blob/13cf48bc8e190f214a340ce86f11f667962dd633/src/include/Defn.h#L693)
1. The symbol is never "un-interned" and so `R_SymbolTable` grows indefinitely.

**Comment by jcheng5** [comment] 2019-04-05 23:49
I suspect we'll need to replace everywhere we're using environments as maps. Unfortunately we don't have a great candidate for replacement right now. I prototyped a naive impl that uses Rcpp to wrap a std::map, which worked, but the performance is much worse than with environments.

**Comment by wch** [comment] 2019-09-13 16:27
It turns out there were two sources of leakage that are relevant here, both of which are fixed now: #2429 and #2522.

**Closed by wch** 2019-09-13 16:27 UTC
Labels: Difficulty: Advanced, Priority: Medium, Type: Bug :bug:

**Comment by Lukasyo** [comment] 2019-10-15 05:55
Hi, I encountered the same problem with reactiveFileReader(). Thanks to @wch I understand that it is fixed by using fastmap as backing store for Map class [#2429 ](https://github.com/rstudio/shiny/pull/2429). However it is not clear to me, how it is used in the case of reactiveFileReader().

Help would be very much appreciated as I am currently surviving this by cron rebooting server 5 times a day.

**Comment by shrektan** [comment] 2019-10-15 07:27
Updating shiny package to the latest CRAN version (1.4.0) should be enough, isn't it?

**Comment by Lukasyo** [comment] 2019-11-14 15:40
@shrektan , yes it is enough, thanks!
