### ISSUE TITLE
more control over widget resize events

### ISSUE THREAD

**Issue by Paul-A-Kavan** [rstudio/shiny#2320] opened 2019-02-05 03:54 UTC
Hi, I'm working on an htmlwidget that requires some custom ability to re-render when the height or width of the window changes. I'd like shiny to fire my widget's resize every time the height or width of the browser window is changed. 
Is there a way to add my widget to a different resize firing policy? Or some other solution that allows me to fire resize with more control?
Thanks, Paul.

**Comment by alandipert** [comment] 2019-04-02 19:28
@Paul-A-Kavan I'm not aware of a "stock Shiny" way of doing this, but I have run across other solutions. In particular, I would direct you at this issue thread on htmlwidgets: https://github.com/ramnathv/htmlwidgets/issues/200

The general strategy appears to be to manage a polling process that checks for a size change and triggers resize in response.

I'm closing this because it's a general question and not a bug/issue with Shiny per se, but I encourage you to post on [Community](http://community.rstudio.com) with any additional questions you may have.

**Closed by alandipert** 2019-04-02 19:28 UTC

**Comment by jcheng5** [comment] 2019-04-02 22:34
The `resize` you provide, as described [here](http://www.htmlwidgets.org/develop_sizing.html#javascript-resize-method), is supposed to be called whenever the height/width of the window changes (assuming it results in a change to the size of the widget itself). If that's not happening, please file an issue on the htmlwidgets GitHub repository.

If you want to be called back whenever the window size changes _regardless of whether the widget itself changes size_, I'd just go ahead and listen for `$(window).resize(...)` as documented [here](https://api.jquery.com/resize/).
