### ISSUE TITLE
fileInput fails strangely with some xls files

### ISSUE THREAD

**Issue by markriseley** [rstudio/shiny#991] opened 2015-10-28 17:11 UTC
I get a strange file upload error on some .xls files, such as below do you know why this might be happening? This error is only occurring on a shinyapps.io published app, not when I run locally on my windows PC.

![image](https://cloud.githubusercontent.com/assets/9608028/10796273/6db9aa66-7d95-11e5-9b6b-204e154da147.png)

The problematic xls files are non-public so I will have to share an example directly by email if that's ok. When I resave as xlsx the problem goes away, and deleting some of the rows appears to fix the issue but there's no rhyme or reason to which cells cause issues and which don't. Could it be an xls encoding issue?

The difficulty I have is the error in shiny is non-recoverable, there are no warnings or errors in the logs, and I can't figure out how to tryCatch my way around it when uploading multiple files it just stops with the html content showing in the progress bar and the file upload failing. Any ideas?

Minimal app that generates the error + session_info():

```


# code for shiny app to reproduce issue
library(shiny)
library(magrittr)
library(XLConnect)
library(XLConnectJars)

ui <- fluidPage(
 fileInput("file1", label = "upload xls file", multiple = TRUE),
 tableOutput("contents")
)

server <- function(input, output) {
 output$contents <- renderTable({
 inFile <- input$file1
 if (is.null(inFile)) return(NULL)
 XLConnect::loadWorkbook(inFile$datapath) %>% 
 XLConnect::readWorksheet(sheet=1, header = F) 
 })
}
shinyApp(ui,server)

devtools::session_info()
#> Session info --------------------------------------------------------------
#>  setting  value 
#>  version  R version 3.1.2 (2014-10-31)
#>  system   x86_64, mingw32 
#>  ui       RStudio (0.99.441) 
#>  language (EN) 
#>  collate  English_United Kingdom.1252 
#>  tz       Europe/London 
#>  date     2015-10-28
#> Packages ------------------------------------------------------------------
#>  package       * version     date       source 
#>  bitops          1.0-6       2013-08-17 CRAN (R 3.1.2) 
#>  clipr           0.1.1       2015-09-04 CRAN (R 3.1.3) 
#>  curl            0.9.3       2015-08-25 CRAN (R 3.1.3) 
#>  devtools        1.9.1       2015-09-11 CRAN (R 3.1.3) 
#>  digest          0.6.8       2014-12-31 CRAN (R 3.1.2) 
#>  evaluate        0.8         2015-09-18 CRAN (R 3.1.3) 
#>  formatR         1.2.1       2015-09-18 CRAN (R 3.1.3) 
#>  htmltools       0.2.6       2014-09-08 CRAN (R 3.1.2) 
#>  httpuv          1.3.3       2015-08-04 CRAN (R 3.1.3) 
#>  httr            1.0.0       2015-06-25 CRAN (R 3.1.3) 
#>  jsonlite        0.9.17      2015-09-06 CRAN (R 3.1.3) 
#>  knitr           1.11        2015-08-14 CRAN (R 3.1.3) 
#>  magrittr      * 1.5         2015-07-21 Github (smbache/magrittr@effbadc) 
#>  memoise         0.2.1       2014-04-22 CRAN (R 3.1.2) 
#>  mime            0.4         2015-09-03 CRAN (R 3.1.3) 
#>  R6              2.1.1       2015-08-19 CRAN (R 3.1.3) 
#>  Rcpp            0.12.1      2015-09-10 CRAN (R 3.1.3) 
#>  RCurl           1.95-4.7    2015-06-30 CRAN (R 3.1.3) 
#>  reprex          0.0.0.9001  2015-10-06 Github (jennybc/reprex@826ddf4) 
#>  rJava           0.9-7       2015-07-29 CRAN (R 3.1.3) 
#>  RJSONIO         1.3-0       2014-07-28 CRAN (R 3.1.2) 
#>  rmarkdown       0.8         2015-08-30 CRAN (R 3.1.3) 
#>  rsconnect       0.3.79      2015-05-20 Github (rstudio/rsconnect@79f5016)
#>  rstudioapi      0.3.1       2015-04-07 CRAN (R 3.1.3) 
#>  shiny         * 0.12.2.9004 2015-10-28 Github (rstudio/shiny@303fce5) 
#>  stringi         0.5-5       2015-06-29 CRAN (R 3.1.3) 
#>  stringr         1.0.0       2015-04-30 CRAN (R 3.1.3) 
#>  XLConnect     * 0.2-11      2015-03-01 CRAN (R 3.1.2) 
#>  XLConnectJars * 0.2-9       2014-08-14 CRAN (R 3.1.2) 
#>  xtable          1.7-4       2014-09-12 CRAN (R 3.1.2)
```

**Comment by jcheng5** [comment] 2016-08-10 18:20
So sorry, this slipped through the cracks. Can you please send the XLS to barbara@rstudio.com, if you still have it?

**Comment by bborgesr** [comment] 2016-09-20 16:23
Closing this now since we cannot reproduce it. If you still encounter this, feel free to tell us and we'll re-open, we'll try to be more responsive next time!

**Comment by thomasblanchet** [comment] 2017-05-28 12:17
I have the exact same problem, so it'd be great if you re-open the issue. Here is an example of problematic file: [RawSurveyTabulationsUSSR.xlsx](https://github.com/rstudio/shiny/files/1034135/RawSurveyTabulationsUSSR.xlsx)

You can reproduce the bug with the exact same code as @markriseley above: https://thomasblanchet.shinyapps.io/excel-import-error/

**Comment by alandipert** [comment] 2019-04-26 23:41
I was also able to reproduce on shinyapps.io, and with latest Shiny (1.3.2).

I filed an issue internally with the shinyapps team and will update here when there's any update or resolution (https://github.com/rstudio/lucid/issues/1686)

**Comment by mmoralesIG** [comment] 2020-12-03 21:01
Hi. had a similar issue while uploading an image 

it's works in desktop but it doesn't after deployment in shinyapp

![7](https://user-images.githubusercontent.com/41596736/101087698-31a24d80-3578-11eb-9fbe-cc26a8d953cb.jpg)

**Comment by wch** [comment] 2020-12-04 16:27
I'm able to reproduce the problem uploading this image.

**Comment by mmoralesIG** [comment] 2020-12-04 18:40
Thank you, @wch 
Weird. I guess we'll have to wait in the meantime.  
(that lucid-redx#2 is not public, right?)
Thanks again

**Comment by wch** [comment] 2020-12-04 18:54
Right, that issue is not public. In the meantime, one workaround is that you can accept zip files as well; if you detect that an uploaded file is a zip file, then unzip it before going on.

**Comment by mmoralesIG** [comment] 2020-12-04 22:33
thank you. I'll check that one.

**Comment by dcaud** [comment] 2021-06-17 15:21
I have a very similar issue. Is there a fix?

**Comment by mgirdwood7** [comment] 2022-04-06 03:14
I had the exact same issue uploading xlsx.
It seemed to be an issue with the actual file for me and not the app - as some xlsx files worked while another didn't.

My work around was to save the problematic xlsx file "as strict XML .xlsx" - then the issue resolved.

**Comment by wch** [comment] 2022-08-09 17:25
Hi all, the underlying issue should be fixed, and these file uploads should work now. Sorry that it has taken so long to address!

**Closed** 2022-08-09 17:39 UTC
Labels: Type: shinyapps.io
