### ISSUE TITLE
updateTabsetPanel in navbarMenu

### ISSUE THREAD

**Issue by HermanSontrop** [rstudio/shiny#595] opened 2014-09-17 09:31 UTC
Hi,

is it correct that currently updateTabsetPanel cannot be used with tabs inside a navbarMenu?

The following code (from yihui) works fine:

    runApp(list(
     ui = fluidPage(navlistPanel(
      id = 'nav',
      tabPanel('Foo', value='foo'),
      tabPanel('Bar', value='bar')
     )),
    server = function(input, output, session) {
      observe(print(input$nav))
      updateTabsetPanel(session, 'nav', 'bar')
     }
     ))

In a similar way with a navbarMenu this also works:

      runApp(list(

       ui = shinyUI(
       navbarPage( "test", 
       tabPanel("tab1", h1("page1")
       ),
       navbarMenu( "menu",
        tabPanel('tab2a', h1("page2a")),
         tabPanel('tab2b', h1("page2b"))
       ))
     ),
  
     server = function(input, output, session) {
    }
     ))

However adding id's and values in an analogous way leads to the error:

Error in buildTabset(divTag$tabs, "dropdown-menu") : tabsetPanel doesn't have an id assigned, but one of its tabPanels has a value. The value won't be sent without an id.

    runApp(list(
     ui = shinyUI(
        navbarPage( "test", 
         tabPanel("tab1", h1("page1")),
               
         navbarMenu( "menu", id = 'someID',
                    tabPanel('tab2a',  value='foo', h1("page2a")),
                     tabPanel('tab2b',  value='bar', h1("page2b"))
         )
      )),
  
     server = function(input, output, session) {
     }
    ))

Is there is way to make this work? 

Finally, is there some progress on the fact that currently a navbarMenu can't be the first panel in a navbarPage? For instance, this doesn't work (or at least not properly):

     runApp(list(
       ui = shinyUI(
         navbarPage( "test",      
         navbarMenu( "menu", id = 'someID',
                    tabPanel('tab2a', h1("page2a")),
                     tabPanel('tab2b', h1("page2b"))
         ),        
         tabPanel("tab1", h1("page1"))         
       )
     ),
    server = function(input, output, session) { 
     }
    ))

Kind regards, Herman

**Comment by wch** [comment] 2015-03-04 21:37
Sorry for the very late reply. The `id` should actually be in `navbarPage`, not `navbarMenu`. For example:

```R
runApp(list(
  ui = shinyUI(
    navbarPage( "test", id = 'someID',
      tabPanel("tab1", h1("page1")),
      
      navbarMenu( "menu", 
        tabPanel('tab2a',  value='foo', h1("page2a")),
        tabPanel('tab2b',  value='bar', h1("page2b"))
      )
    )),
  
  server = function(input, output, session) {
    observe(print(input$someID))
    updateTabsetPanel(session, 'someID', 'bar')
  }
))
```

As for using menus first, that's a bug - it was also reported in #543. I'm closing this issue because it's a duplicate of the other one.

**Closed by wch** 2015-03-04 21:37 UTC

**Comment by mostly-harmless** [comment] 2015-03-04 23:58
Not sure if this is the best place to put this but it seems related to @HermanSontrop's question. In an adapted version of the code above ... how to use updateTabsetPanel to navigate to tab sub2?  

```r
library(shiny)
runApp(list(
  ui = shinyUI(
    navbarPage( "test", id = 'someID',
                tabPanel("tab1", h1("page1")),

                navbarMenu( "menu",
                            tabPanel('tab2a',  value='foo', h1("page2a")),
                            tabPanel('tab2b',  value='bar', h1("page2b")),
                            # tabPanel('tab_sub',  value='sub', uiOutput("sub_tabPanel"))
                            tabPanel('tab_sub',  uiOutput("sub_tabPanel"))
                )
    )),

  server = function(input, output, session) {
    observe(print(input$someID))

    output$sub_tabPanel <- renderUI({
      tabsetPanel(
        tabPanel("Summary", value = "sub1", h1("sub1")),
        tabPanel("Plot", value = "sub2", h2("sub2"))
      )
    })

    # updateTabsetPanel(session, 'someID', 'sub')
    updateTabsetPanel(session, 'someID', 'sub2')
    # updateTabsetPanel(session, 'someID', 'sub')
    # updateTabsetPanel(session, 'sub', 'sub2')
  }
))
```
