### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by vnijs** [rstudio/shiny#1102] opened 2016-02-09 04:46 UTC
On occasion (can't pinpoint what causes it) conditional panels break and I see the error below. Is this something a check could be added for?

<img width="539" alt="screen shot 2016-02-08 at 8 42 16 pm" src="https://cloud.githubusercontent.com/assets/2998956/12907823/c25ead90-cea4-11e5-8a69-1195cd087cbf.png">

**Comment by yihui** [comment] 2016-02-09 05:04
I spent a few hours last week digging into an issue of the same error message with no avail. My issue was related to rendering a DataTable in a hidden HTML element.

**Comment by yihui** [comment] 2016-02-16 05:50
It apears this was caused by the bug https://github.com/ramnathv/htmlwidgets/issues/151 discovered by @jcheng5.

**Comment by wch** [comment] 2016-07-27 18:25
This looks like it was fixed in htmlwidgets. If you still encounter the bug, you can re-open this issue.

**Closed by wch** 2016-07-27 18:25 UTC
