### ISSUE TITLE
`boxCox` plot fails

### ISSUE THREAD

**Issue by pbosetti** [rstudio/shiny#3773] opened 2023-01-23 16:33 UTC
I have found that any function that produces the Box-Cox plot fails when used in a reactive environment. This includes `car::boxCox` but also `MASS::boxcox` and `Linda::gg_boxcox` as well.

### System details

Browser Version: Not relevant

Output of `sessionInfo()`:

```
R version 4.2.2 (2022-10-31)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] car_3.1-1        carData_3.0-5    scales_1.2.1     lubridate_1.9.0  timechange_0.1.1
 [6] hexbin_1.28.2    forcats_0.5.2    stringr_1.4.1    dplyr_1.0.10     purrr_0.3.5     
[11] readr_2.1.3      tidyr_1.2.1      tibble_3.1.8     ggplot2_3.4.0    tidyverse_1.3.2 
[16] shiny_1.7.3     

loaded via a namespace (and not attached):
 [1] httr_1.4.4          sass_0.4.2          bit64_4.0.5         vroom_1.6.0        
 [5] jsonlite_1.8.3      modelr_0.1.9        bslib_0.4.1         assertthat_0.2.1   
 [9] googlesheets4_1.0.1 cellranger_1.1.0    pillar_1.8.1        backports_1.4.1    
[13] lattice_0.20-45     glue_1.6.2          digest_0.6.30       promises_1.2.0.1   
[17] rvest_1.0.3         colorspace_2.0-3    htmltools_0.5.4     httpuv_1.6.6       
[21] pkgconfig_2.0.3     broom_1.0.1         haven_2.5.1         xtable_1.8-4       
[25] later_1.3.0         tzdb_0.3.0          googledrive_2.0.0   generics_0.1.3     
[29] farver_2.1.1        ellipsis_0.3.2      cachem_1.0.6        withr_2.5.0        
[33] cli_3.4.1           magrittr_2.0.3      crayon_1.5.2        readxl_1.4.1       
[37] mime_0.12           memoise_2.0.1       evaluate_0.18       fs_1.5.2           
[41] fansi_1.0.3         xml2_1.3.3          textshaping_0.3.6   tools_4.2.2        
[45] hms_1.1.2           gargle_1.2.1        lifecycle_1.0.3     munsell_0.5.0      
[49] reprex_2.0.2        compiler_4.2.2      jquerylib_0.1.4     systemfonts_1.0.4  
[53] rlang_1.0.6         grid_4.2.2          rstudioapi_0.14     labeling_0.4.2     
[57] rmarkdown_2.18      gtable_0.3.1        abind_1.4-5         DBI_1.1.3          
[61] R6_2.5.1            knitr_1.40          bit_4.0.4           fastmap_1.1.0      
[65] utf8_1.2.2          ragg_1.2.4          stringi_1.7.8       parallel_4.2.2     
[69] Rcpp_1.0.9          vctrs_0.5.0         dbplyr_2.2.1        tidyselect_1.2.0   
[73] xfun_0.34
```

### Example application 

Launch the following app and load the attached example data frame [cencompdes.csv](https://github.com/rstudio/shiny/files/10481710/cencompdes.csv). Use the formula `Y~A*B*C` in the corresponding text input.

```R
library(shiny)
library(tidyverse)
library(car)

source("grading_lib.R")

empty_plot <- ggplot() +
  geom_text(aes(x=0, y=0, label="Please load data"))

ui <- fluidPage(# Application title
  titlePanel("Test BoxCox"),
  
  sidebarLayout(
    sidebarPanel(
      fileInput("datafile", "Data table",
                accept = ".csv"),
      textInput("model", "Model formula", placeholder="Y~A*B*C"),
    ),
    
    mainPanel(
      tabsetPanel(
        tabPanel("Box-Cox",
                 h2("Box-Cox plot"),
                 plotOutput("boxcox")
        )
      )
    )
  )
)

server <- function(input, output) {
  data <- reactive({
    if (!is_null(input$datafile$datapath)) {
      read_csv2(input$datafile$datapath)
    }
  })
  
  model <- reactive({
    if (!is_null(data())) {
      tryCatch(
        {
          lm(formula=input$model, data=data())
        },
        error = \(e) {NULL}
      )
    }
  })
  
  output$boxcox <- renderPlot({
    if (is_null(model())) return(empty_plot)
    model() %>% boxCox()
  })
}

# Run the application
shinyApp(ui = ui, server = server)
```

### Describe the problem in detail

The plot fails rendering with `Error in stats::model.frame: object 'input' not found`. Looks like the lazy evaluation of `model()` is the problem.

**Comment by wch** [comment] 2023-01-23 21:25
It would help if you could provide a minimal reproducible example. (The example you provided sources another R file.) Here is a simplified version that I came up with.

```R
library(shiny)
library(car)

ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      textInput("model", "Model formula", value="speed~dist"),
    ),
    mainPanel(
      plotOutput("plot")
    )
  )
)

server <- function(input, output) {
  model1 <- reactive({
    lm(formula=input$model, data=cars)
  })
  output$plot <- renderPlot({
    print(as.formula(model1()))
    boxCox(model1())
  })
}

shinyApp(ui, server)
```

It produces the following message instead of a plot:

```
Warning: Error in stats::model.frame: object 'input' not found
  180: stats::model.frame
  172: boxCox.lm
  170: renderPlot [#7]
  168: func
  128: drawPlot
  114: <reactive:plotObj>
   98: drawReactive
   85: renderFunc
   84: output$plot
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>
```

*****

The problem is:
* `car::boxCox.lm` calls
* `stats::update(object, y = TRUE, qr = TRUE)` (where `object` is the `lm` object), which is dispatched to 
* `stats::update.default`, which in turn tries to modify the original call and then evaluate it in the `parent.frame()` (also known as the calling environment).

The problem can be reproduced without Shiny involved at all. If the model object is created in an environment that's different from

```R
mymodel <- function() {
  model_str <- "speed~dist"
  lm(formula=model_str, data=cars)
}

# Error calling boxCox()
car::boxCox(mymodel())
#> Error in stats::model.frame(formula = model_str, data = cars, drop.unused.levels = TRUE) : 
#>  object 'model_str' not found

# Same error calling update() directly
stats::update(mymodel(), y = TRUE)
#> Error in stats::model.frame(formula = model_str, data = cars, drop.unused.levels = TRUE) : 
#>   object 'model_str' not found
```


```R
model_str <- "dist~speed")
car::boxCox(mymodel())
```

**Comment by wch** [comment] 2023-01-23 21:33
I think the root of the problem is that `stats::update` is designed only to work in interactive R sessions, or in scripts where it is called at the top level.

**Comment by cpsievert** [comment] 2023-01-23 21:37
Perhaps the issue can be addressed by changing

```r
lm(formula=input$model, data=data())
```

to 

```r
lm(formula=str2lang(input$model), data=data())
```

?

**Comment by wch** [comment] 2023-01-23 21:43
@cpsievert Unfortunately, that doesn't work. The problem is not that `lm()` is not getting a formula object -- the problem is that `stats::update.default()` tries to re-evaluate the call to `lm()`, but in the wrong environment. It assumes that it should be evaluated in the calling environment, but that's not a safe thing to assume.

**Comment by cpsievert** [comment] 2023-01-23 21:51
Ahh, right. I got confused because of the `print(as.formula(model1()))` in reprex, and also by the face that this happens to work:

```r
test1 <- function() {
    model_str <- "speed~dist"
    model <- lm(formula=as.formula(model_str), data=cars)
    car::boxCox(model)
}
test1()
```

**Comment by wch** [comment] 2023-01-23 21:54
Ah, I've edited the example to remove that line.

I've created a gist which illustrates the problem with `stats::update` more directly.

**Comment by wch** [comment] 2023-01-23 22:13
I found this in one of the vignettes for the `car` package, titled "[Using car functions inside user functions](https://cran.r-project.org/web/packages/car/vignettes/embedding.pdf)":

>  Some users of the car and effects package have found it convenient to write their own functions that call the functions in car or effects. While this will generally occur as expected, in some instances calls to car or effects functions will fail because the results of an input fitted model may not be available inside a user-written function. This brief note describes how this problem can be solved.

It seems like their workaround is basically to copy stuff to the global environment before calling functions from `car`. This seems pretty hacky to me, and if there are multiple simultaneous users of the app, it could cause one users's session to interfere with another.

**Comment by wch** [comment] 2023-01-23 22:19
I have a workaround that is simple and should avoid copying to the global env.

First, notice that `car:::boxCox.lm` calls `update()` only if `y` and `qr` are not set:

```R
> car:::boxCox.lm
function (object, lambda = seq(-2, 2, 1/10), plotit = TRUE, ...) 
{
    m <- length(lambda)
    if (is.null(object$y) || is.null(object$qr)) 
        object <- update(object, y = TRUE, qr = TRUE)
    result <- NextMethod()
    if (plotit) 
        invisible(result)
    else result
}
<bytecode: 0x146a15e28>
<environment: namespace:car>
```

So all you need to do is make sure that when `lm()` is called, it is called with values for `y` and `qr`. For example, here's a version of my app above, with those values provided to `lm()`, and it works.

```R
library(shiny)
library(car)

ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      textInput("model", "Model formula", value="speed~dist"),
    ),
    mainPanel(
      plotOutput("plot")
    )
  )
)

server <- function(input, output) {
  model <- reactive({
    lm(formula=as.formula(input$model), data=cars, y=TRUE, qr=TRUE)
  })
  output$plot <- renderPlot({
    boxCox(model())
  })
}

shinyApp(ui, server)
```

**Closed** 2023-01-23 23:27 UTC

**Comment by pbosetti** [comment] 2023-01-24 08:22
Apologies for the reprex, I edited it by removing the unnecessary `source`.

**Comment by pbosetti** [comment] 2023-01-24 08:25
And thanks @wch for the workaround!
