### ISSUE TITLE
Strange rendering of ggplotly in Shiny app on Macbook Pro 2016

### ISSUE THREAD

**Issue by andirey** [rstudio/shiny#2001] opened 2018-04-09 05:03 UTC
Dear friends!
I'm stuck with the strange rendering of ggplot graphs (via plotly) in Shiny applications on my new MacBook Pro 2016. The plots are working well on shiny-servers, and on other computers. I tried to updated packages and etc. No effects. Will be glad to have any pieces of advice how to fix this problem.
<img width="672" alt="plot" src="https://user-images.githubusercontent.com/1951536/38480131-590bc476-3bcc-11e8-9615-f98303fae98a.png">

**Comment by jcheng5** [comment] 2018-04-10 17:11
Hi, can you please provide a reproducible example for us to try? Thanks.

**Comment by andirey** [comment] 2018-04-10 20:34
Here is the code as a reproducible example.
==
<img width="945" alt="ggplot_problem" src="https://user-images.githubusercontent.com/1951536/38582206-b2b3bf5a-3d17-11e8-9695-0385fc910b04.png">

library(tidyverse)
library(plotly)
library(shinydashboard)
library(DT)

server <- function(input, output, session) {

  output$plot_mtcars <- renderPlotly({
    g <- mtcars %>% 
      ggplot(aes(mpg, wt)) +
      ggtitle("mpg vs wt") +
      xlab("mpg") + ylab("wt") +
      geom_point() + geom_smooth() +
      theme_bw()
    g
  })
  
  df_mtcars <- reactive({
    mtcars
  })
  
  output$dt_mtcars <- renderDataTable(
    datatable(df_mtcars()))
  
}

sidebar <- dashboardSidebar(
  sidebarMenu(
    menuItem("Dashboard", icon = icon("dashboard"),
             menuSubItem("Data", tabName = "mtcars"))
  )
)

body <- dashboardBody(
  tabItems(
    tabItem(tabName = "mtcars",
            tabPanel("mtcars",
                     fluidPage(
                       fluidRow(plotlyOutput("plot_mtcars")),
                       fluidRow(dataTableOutput("dt_mtcars"))
                     ))
    ))
)

ui <- dashboardPage(
  dashboardHeader(title = "Test"),
  sidebar, body)

shinyApp(ui, server)

**Comment by wch** [comment] 2018-04-10 20:54
A few things:

* `fluidPage()` shouldn't be used here. It shouldn't be used inside of any other UI components.
* The content should be in boxes, as in https://rstudio.github.io/shinydashboard/structure.html#body.

Fixed version:

```R
library(shiny)
library(tidyverse)
library(plotly)
library(shinydashboard)
library(DT)

server <- function(input, output, session) {
  
  output$plot_mtcars <- renderPlotly({
    g <- mtcars %>%
      ggplot(aes(mpg, wt)) +
      ggtitle("mpg vs wt") +
      xlab("mpg") + ylab("wt") +
      geom_point() + geom_smooth() +
      theme_bw()
    g
  })
  
  df_mtcars <- reactive({
    mtcars
  })
  
  output$dt_mtcars <- renderDataTable(
    datatable(df_mtcars()))
  
}

sidebar <- dashboardSidebar(
  sidebarMenu(
    menuItem("Dashboard", icon = icon("dashboard"),
      menuSubItem("Data", tabName = "mtcars"))
  )
)

body <- dashboardBody(
  tabItems(
    tabItem(tabName = "mtcars",
      tabPanel("mtcars",
          fluidRow(
            box(plotlyOutput("plot_mtcars"), width = 12))
          ),
          fluidRow(
            box(dataTableOutput("dt_mtcars"), width = 12)
          )
        )
    ))
)

ui <- dashboardPage(
  dashboardHeader(title = "Test"),
  sidebar, body)

shinyApp(ui, server)
```

![image](https://user-images.githubusercontent.com/86978/38583041-54aa9b9e-3cd7-11e8-90ad-9e8d64985765.png)


I'm closing this because it's not a Shiny bug. For general help questions like this, please use https://community.rstudio.com/ or https://stackoverflow.com/.

**Closed by wch** 2018-04-10 20:54 UTC

**Comment by andirey** [comment] 2018-04-13 17:27
Dear Winston!
Thanks a lot for your kind answer.
The "box()" is really cool option.
I made copy-paste for fixed code, and again get the same.
No idea why it happens because on shiny-server (web) all works fine.
<img width="1245" alt="mtcars" src="https://user-images.githubusercontent.com/1951536/38749038-e146d6c0-3f58-11e8-8d5b-297e7ea6a0b9.png">

**Comment by andirey** [comment] 2018-04-16 17:12
Re-install package "plotly", and this strange bug was fixed.
