### ISSUE TITLE
Shiny.onInputChange() in Shiny module

### ISSUE THREAD

**Issue by JianWang2016** [rstudio/shiny#1264] opened 2016-07-29 19:04 UTC
Dear Shiny Module developer(s),

I would appreciate your advice on correct name space for the object in Shiny.OnInputChange() in a module.  I encountered this issue when using rAmCharts so I posted it there.  Since it has to do with shiny module, so I provide a link here, hoping someone could help out.  Thanks much.

https://github.com/datastorm-open/rAmCharts/issues/59

**Comment by bborgesr** [comment] 2016-08-02 17:31
Can you provide a minimal reproducible examples and tell me exactly what error is happening?

**Comment by JianWang2016** [comment] 2016-08-03 13:33
Barbara:
The example<http://datastorm-open.github.io/introduction_ramcharts/shiny.html> works great until the codes are adapted for shiny modules. Any advice on how to change shiny.onInputChange() javascript is greatly appreciated.
Here is the code without using module.

library(shiny)
library(rAmCharts)
shinyApp(
ui = fluidPage(
amChartsOutput(outputId = "amchart"),
fluidRow(
column(width = 1, strong("Values: ")),
column(width = 3, verbatimTextOutput("click"))
)
),
server = function(input, output) {
output$amchart <- renderAmCharts({
# build the chart
pipeR::pipeline(
amBoxplot(iris[, -5]),
addListener(name = 'clickGraphItem',
expression = paste('function (event) {',
'Shiny.onInputChange(\'myValues\', event.item.values);',
'}'))
)
})
output$click <- renderPrint(input$myValues)
}
)
`
Here is the module UI and Server codes in a file named testClickModule.R. The graph still displays but the click event is not registered. I get a sense that the name space is the culprit but didn't manage to get it working after testing session$ns.
`
clickMeUI <- function(id) {
ns <- NS(id)
tagList(
amChartsOutput(outputId = ns("amchart")),
fluidRow(
column(width = 1, strong("Values: ")),
column(width = 3, verbatimTextOutput(ns("click")))
)
)
}
clickMe <- function(input, output, session) {
output$amchart <- renderAmCharts({
  # build the chart
  pipeR::pipeline(
    amBoxplot(iris[, -5]),
    addListener(name = 'clickGraphItem',
                expression = paste('function (event) {',
                                   'Shiny.onInputChange(\'myValues\', event.item.values);',
                                   '}'))
  )
})

output$click <- renderPrint(input$myValues)
}

**Comment by jcheng5** [comment] 2016-08-09 19:06
Related to #1621

**Comment by daattali** [comment] 2016-08-15 08:28
@jcheng5 I think #1261 was meant to be attached here

**Comment by alandipert** [comment] 2019-04-29 18:33
Closing because the original issue datastorm-open/rAmCharts#59 has been closed, and appears to rule out `Shiny.onInputChange()`

Please don't hesitate to comment further or open a new issue if you are still facing this problem or one like it.

**Closed by alandipert** 2019-04-29 18:33 UTC

**Comment by dvfariaf** [comment] 2019-05-13 13:02
Hello, 

I think I have a similar issue, let me know if this is not the case. 

I'm simply trying to recover the moment when a user clicks a node of a graph with `visNetwork`. 

In the following case `Shiny.onInputChange()` works: 

```
## dev #################
library("shiny")
library("visNetwork")

server <- function(input, output) {
  
  output$my_network <- renderVisNetwork({
    nodes <- data.frame(id = 1:10)
    
    edges <- data.frame(from = round(runif(
      n = 10, min = 1, max = 10
    )),
    to = round(runif(
      n = 10, min = 1, max = 10
    )))
    
    visNetwork(nodes, edges) %>%
      visInteraction(hover = TRUE) %>%
      visEvents(
        click = 'function(nodes) {
        console.info("click")
        console.info(nodes)
        Shiny.onInputChange("clicked_node", {nodes : nodes.nodes, edges : nodes.edges});
        ;}'
      )
    
})
  
  output$clicked_node <- renderUI({
    if (is.null(input$clicked_node)) {
      "No node has been clicked yet"
    } else {
      print(input$clicked_node)
      "Node has been clicked"
    }
    
  })
  
  output$hovered_node <- renderUI({
    if (is.null(input$hovered_node)) {
      "No node has been hovered yet"
    } else {
      print(input$hovered_node)
      "Node has been hovered"
    }
    
  })
  
  
}

ui <- fluidPage(
  uiOutput("clicked_node"),
  uiOutput("hovered_node"),
  visNetworkOutput("my_network")
)

shinyApp(ui, server)
```

In this other case, when modules are used, it doesn't work any more. 

```
## dev #################
library("shiny")
library("visNetwork")

graph <- function(input, output, session) {
  
  output$my_network <- renderVisNetwork({
    nodes <- data.frame(id = 1:10)
    
    edges <- data.frame(from = round(runif(
      n = 10, min = 1, max = 10
    )),
    to = round(runif(
      n = 10, min = 1, max = 10
    )))
    
    visNetwork(nodes, edges) %>%
      visInteraction(hover = TRUE) %>%
      visEvents(
        click = 'function(nodes) {
        console.info("click")
        console.info(nodes)
        Shiny.onInputChange("clicked_node", {nodes : nodes.nodes, edges : nodes.edges});
        ;}'
      )
    
  })
  
  output$clicked_node <- renderUI({
    if (is.null(input$clicked_node)) {
      "No node has been clicked yet"
    } else {
      print(input$clicked_node)
      "Node has been clicked"
    }
    
  })
  
  output$hovered_node <- renderUI({
    if (is.null(input$hovered_node)) {
      "No node has been hovered yet"
    } else {
      print(input$hovered_node)
      "Node has been hovered"
    }
    
  })
  
  
  }


graph_UI <- function(id){
  
  ns <- NS(id)
  fluidPage(
    uiOutput(ns("clicked_node")),
    uiOutput(ns("hovered_node")),
    visNetworkOutput(ns("my_network"))
  )
  
}

server <- function(input, output, session){
  callModule(graph, "graph")
}

ui <- fluidPage(
  graph_UI(id="graph")
)


shinyApp(ui, server)
```

I checked with `shinytest` and the event `input$clicked_node` is indeed registered.

Here is my `infoSession` output just in case it helps reproducing:

```
R version 3.5.3 (2019-03-11)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252 LC_NUMERIC=C                  
[5] LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] visNetwork_2.0.6 shiny_1.3.2     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1        lattice_0.20-38   digest_0.6.18     later_0.8.0       mime_0.6          grid_3.5.3        R6_2.4.0          xtable_1.8-3     
 [9] jsonlite_1.6      magrittr_1.5      promises_1.0.1    Matrix_1.2-17     DT_0.5            reticulate_1.11.1 tools_3.5.3       htmlwidgets_1.3  
[17] yaml_2.2.0        httpuv_1.5.1      compiler_3.5.3    htmltools_0.3.6
```

**Comment by dvfariaf** [comment] 2019-05-13 16:34
If anyone still has the same issue:

The javascript id must be defined in the current session namespace, using `session$ns`. Replacing 

`Shiny.onInputChange("clicked_node", {nodes : nodes.nodes, edges : nodes.edges})`

by 

`paste0(Shiny.onInputChange("',session$ns("clicked_node"),'", {nodes : nodes.nodes, edges : nodes.edges});`

Does the trick.  

What is counterintuitive is that when recording the app input/output with `shinytest`, `clicked_node` is shown as `input$clicked_node`, even in the case without wrapping the parameter name with `session$ns`. This made me think that the problem was elsewhere other than the definition of the parameter itself.

**Comment by jianhaizhang** [comment] 2022-09-23 06:25
> If anyone still has the same issue:
> 
> The javascript id must be defined in the current session namespace, using `session$ns`. Replacing
> 
> `Shiny.onInputChange("clicked_node", {nodes : nodes.nodes, edges : nodes.edges})`
> 
> by
> 
> `paste0(Shiny.onInputChange("',session$ns("clicked_node"),'", {nodes : nodes.nodes, edges : nodes.edges});`
> 
> Does the trick.
> 
> What is counterintuitive is that when recording the app input/output with `shinytest`, `clicked_node` is shown as `input$clicked_node`, even in the case without wrapping the parameter name with `session$ns`. This made me think that the problem was elsewhere other than the definition of the parameter itself.

This solution helped me a lot. Thank you so much!
