### ISSUE TITLE
Any way to not have the "ERROR: [on_request_read] connection reset by peer" appear when running apps in RStudio Viewer?

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#1469] opened 2016-11-17 19:38 UTC
It seems to trip up beginners into thinking they've done something wrong.

**Comment by grayskripko** [comment] 2017-01-09 17:01
hate this error.
I have another one case of it.
I use RSelenium+phantomjs to test a shiny app.
Built-in 'check' RStudio opportunity generates it too:

![image](https://cloud.githubusercontent.com/assets/10427026/21775212/ddda8cae-d69d-11e6-886e-d636eeeb2f3a.png)

**Comment by loudermilk** [comment] 2017-01-24 15:43
From RStudio I get this error (i.e. **ERROR: [on_request_read] connection reset by peer**) whenever I run my app in "_Viewer Pane_" or in "_External_", but I ***do not*** get the error when I run in "_Window_" mode.

**Comment by loudermilk** [comment] 2017-07-05 14:58
New Shiny app, same error, but my "workaround" mentioned above doesn't work.
**Shiny 1.0.3**
**R version 3.4.0 Patched (2017-05-25 r72742)**

New perplexing behavior:  (1) Launch RStudio, Run App, app works fine, close app; (2a) Run App (again), dies with **ERROR: [on_request_read] connection reset by peer**; (2b) Close RStudio, Launch RStudio, Run App, app works fine.

I've also tried removing all variable from global environment before re-running app, but that doesn't help.

**Comment by jcheng5** [comment] 2017-07-05 21:43
@loudermilk "connection reset by peer" is probably not the cause of the grey-out, but the result. Right before the call to `show`, try `print(environment(show))`, that should show you which package's implementation of `show` you're getting when you don't qualify it with the shinyjs:: prefix.

**Comment by jcheng5** [comment] 2017-07-05 21:46
Moving this to httpuv

**Closed by jcheng5** 2017-07-05 21:46 UTC

**Comment by daattali** [comment] 2017-07-05 21:48
I'm going to make it more clear that showElement is the preferred alias to
show, it's one too many times that someone suffered from this!
