### ISSUE TITLE
Downloading / uploading large files: md5 checksum does not always match

### ISSUE THREAD

**Issue by fxi** [rstudio/shiny#3429] opened 2021-06-16 16:23 UTC
Hi there !

We need to import / export large files for a Shiny offline app: users need to be able to backup and re-import all their data. It could be huge. Spatial application with a lot of layers.

We got something weird. Sometimes while uploading a large file the md5 checksum is off. The data appears to be corrupted.

I created a minimal reproducible app in a docker image to isolate everything.

You can test it using:

```sh
docker run --rm -ti -p 5099:5099 fredmoser/shinyuploadissue:latest
```

It's a large image, as it include the sample data ( a zip file ) in `/app/www/data.zip`

If you download the sample data using the link, then upload it again, sometimes, not always, the md5 sum do not match : 

![image](https://user-images.githubusercontent.com/1196833/122256120-0a391f80-cecf-11eb-95a8-60ae450a3764.png)

Am I expecting too much from Shiny ?

Thanks !

 

<details>
<summary>sessionInfo</summary>

```sh
R version 4.1.0 (2021-05-18)
Platform: x86_64-pc-linux-musl (64-bit)
Running under: Alpine Linux v3.12

Matrix products: default
BLAS:   /usr/local/lib/R/lib/libRblas.so
LAPACK: /usr/local/lib/R/lib/libRlapack.so

locale:
[1] C.UTF-8 C       C       C       C       C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] shiny_1.6.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6        digest_0.6.27     withr_2.4.2       later_1.2.0
 [5] mime_0.10         R6_2.5.0          jsonlite_1.7.2    lifecycle_1.0.0
 [9] xtable_1.8-4      magrittr_2.0.1    cachem_1.0.5      rlang_0.4.11
[13] promises_1.2.0.1  jquerylib_0.1.4   bslib_0.2.5.1     ellipsis_0.3.2
[17] tools_4.1.0       httpuv_1.6.1      fastmap_1.1.0     compiler_4.1.0
[21] htmltools_0.5.1.1 sass_0.4.0
```

</details>

<details> 
<summary>Dockerfile</summary>

```Dockerfile
ARG R_VERSION="4.1.0"
FROM rhub/r-minimal:${R_VERSION} as build_r
ENV R_PACKAGES_DATE="2021-06-15"

RUN echo "local({ \
rep <- getOption('repos'); \
rep['CRAN'] <- 'https://mran.microsoft.com/snapshot/$R_PACKAGES_DATE'; \
options(Ncpus = $(nproc --all)) ; \
options(repos = rep) \
})" > .Rprofile

RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
# R httuv -> autoconf + automake specific version -> 3.11 main
RUN echo "http://dl-cdn.alpinelinux.org/alpine/v3.11/main" >> /etc/apk/repositories

RUN apk add --no-cache \
    libpng \
    libxml2 \
    icu-libs \
    ca-certificates

RUN apk add --no-cache --virtual build_deps \
  linux-headers \
  build-base \
  R-dev \
  libressl-dev \
  libxml2-dev \
  tiff-dev \
  libpng-dev \
  pcre2-dev \
  m4 \
  zip \
  file \
  autoconf=2.69-r2 \
  automake=1.16.1-r0 

RUN Rscript -e ' install.packages("shiny")'
RUN apk del build_deps

FROM rhub/r-minimal:${R_VERSION} as final
COPY --from=build_r / /

WORKDIR /app 
COPY /www/data.zip /app/www/data.zip
COPY run.R .
COPY app.R . 

CMD ["Rscript","--vanilla","run.R", "5099"]
```
</details>

<details>
<summary>The simple app</summary>

```R

options(shiny.maxRequestSize=2e3*1024^2)

ui <- bootstrapPage(
  tags$label('1) Download the sample file (~980MB)'),
  tags$a(href="data.zip", "Download", download=NA, target="_blank"),
  fileInput('file', '2) Re-upload it a few times'),
  tags$label('MD5 check sum before:'),
  textOutput('md5Before'),
  tags$label('MD5 check sum after (sometimes it does not match)'),
  textOutput('md5After')
)

server <- function(input, output) {

  observeEvent(input$file,{
    md5Before <- system(sprintf('md5sum %1$s','www/data.zip'),intern=T) 
    output$md5Before <- renderText(md5Before)
    md5After <- system(sprintf('md5sum %1$s',input$file$datapath),intern=T) 
    output$md5After <- renderText(md5After)
    # unzip ?
    #unzip(input$file$datapath,exdir=dirname(input$file$datapath))
})

}

shinyApp(ui = ui, server = server)
```

</details>

[edit 2021-06-29 : formatting using `<details>`]

**Comment by wch** [comment] 2021-06-16 21:58
That's strange. Are you sure that something else odd isn't happening, like the Docker image running out of storage space?

Also, your code is structured in a way where the reactivity might be doing something other than what you're expecting. Instead of assigning to `output$xx` inside of the `observeEvent`, the code should be structured like this:

```r
output$md5Before <- renderText({
    system(sprintf('md5sum %1$s','www/data.zip'),intern=T) 
})

output$md5After <- renderText({
    if (is.null(input$file)) return()
    system(sprintf('md5sum %1$s',input$file$datapath),intern=T) 
})
```

**Comment by fxi** [comment] 2021-06-16 22:50
Thanks for the quick reply :)

It sounds like a storage issue, right ? But... we work in /tmp and

```sh
/app # df -h
Filesystem                Size      Used Available Use% Mounted on
overlay                 125.7G     87.1G     32.3G  73% /
tmpfs                    64.0M         0     64.0M   0% /dev
tmpfs                     3.9G         0      3.9G   0% /sys/fs/cgroup
shm                      64.0M         0     64.0M   0% /dev/shm
/dev/vda1               125.7G     87.1G     32.3G  73% /etc/resolv.conf
/dev/vda1               125.7G     87.1G     32.3G  73% /etc/hostname
/dev/vda1               125.7G     87.1G     32.3G  73% /etc/hosts
tmpfs                     3.9G         0      3.9G   0% /proc/acpi
tmpfs                    64.0M         0     64.0M   0% /proc/kcore
tmpfs                    64.0M         0     64.0M   0% /proc/keys
tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
tmpfs                    64.0M         0     64.0M   0% /proc/sched_debug
tmpfs                     3.9G         0      3.9G   0% /sys/firmware
```

<image  width="60%" src=https://user-images.githubusercontent.com/1196833/122301738-66b53280-cf01-11eb-9130-f598f9bbc419.png>

And the result is not right:

![image](https://user-images.githubusercontent.com/1196833/122304516-a5e58280-cf05-11eb-9069-f1aade59d2b6.png)



For the logic, yep, my version was not by the book, but I wanted to trigger on purpose both `md5sum` each time input$file was updated to exclude something funny with md5sum. ObserveEvent should not be triggered by null value by default, so we avoid a if(<test>);  Outputs can be assigned from within reactive context, and value set is just a non reactive object. So my logic was ok, I guess. However, I could have wrote this as : 

```r
output$md5Before <- renderText({
    if (is.null(input$file)) return()
    system(sprintf('md5sum %1$s','www/data.zip'),intern=T) 
})

output$md5After <- renderText({
    if (is.null(input$file)) return()
    system(sprintf('md5sum %1$s',input$file$datapath),intern=T) 
})
```

So it's late for me and maybe I don't have a clear mind. I will check this again tomorrow, maybe on a fresh docker install or with huge image disk constraints. 

Thanks

**Comment by fxi** [comment] 2021-06-17 12:39
This seems to only happen with Shiny on Docker desktop for mac, with or without bind volumes or docker volumes.

I tested on Windows, Linux and native - no docker - and it works fine.

I also tried with a clean install of Docker on macOS and it fails.

My apps send a lot of POST requests using nodejs uploaders in alpine containers and it never fails. That's very intriguing that this happens only with Shiny. 

I'm closing this for now, but I still don't understand exactly what happens.

**Comment by fxi** [comment] 2021-06-21 08:16
This was the most strange bug I've had in many years. I was not able to solve this, but I found a workaround that happen to be faster, too.

For those interested, here is some details on how I tried to tackle this. It's very specific to my complex stack and an overkill in most cases, but it could be useful for some.

Instead of using a browser to access the app, I shoved the dockerized image in an Electron app. End users, who are not technical staff, with low-end machines and very spotty internet connection, can install, work offline, and delete the app with just a few clicks, without compiling stuff or worrying about the dependency hell. A Docker daemon/endpoint must be available though, which is not always possible: it's not a one size fits all.

The new "direct uploader" solution reads the large archive on the host from the Electron app, starts a container, mounts the file as volume, the database as another volume, moves the contents between them, decompresses and install everything. It's super fast and reliable: 15s for importing ~1GB of data. No POST http request. 

Electron's installer, including an Alpine image with GRASS, R + all packages, GDAL, python, etc., weighs about ~ 275MB, which is not much.

```sh
drwxr-xr-x@  6 fxi  staff   192B Jun 18 19:21 .
drwxr-xr-x@ 10 fxi  staff   320B May 11 18:02 ..
-rw-r--r--@  1 fxi  staff   263M Jun 18 19:16 accessmod-5.7.5-alpha Setup.exe
-rw-r--r--@  1 fxi  staff   265M Jun 18 19:08 accessmod-5.7.5-alpha.dmg
```

**Comment by jcheng5** [comment] 2021-06-21 20:06
I'm able to repro with the docker image. The files are mostly the same, except the range from `0x15338000` through `0x15467ff0`. All the data is there in both files, but in the uploaded copy, it's like the data was chopped up into 2048-byte segments and reordered.

**Comment by jcheng5** [comment] 2021-06-21 20:36
This is what I did:

1. Grabbed both versions of data.zip (call them old.zip and new.zip)
2. `hexdump old.zip > old.zip.txt` and `hexdump new.zip > new.zip.txt`
3. `diff old.zip.txt new.zip.txt > bigdiff.txt`
4. Ran the following code

```r
library(tidyverse)

bigdiff <- readLines("~/Downloads/bigdiff.txt") %>% grep("^[><]", ., value = TRUE)
direction <- substr(bigdiff, 1, 1)
line <- substr(bigdiff, 3, 10)
value <- substr(bigdiff, 12, 99)
reference_vals <- value[1:(length(value)/2)]
pos <- match(value, reference_vals)
offset <- pos - seq_along(value)

df <- data.frame(
  dir = direction,
  line = factor(line, levels = unique(line)),
  value = value,
  pos = pos,
  offset = offset
)

blocknum <- rep(1:(length(value)/2048), each = 2048)
blocks <- df %>%
  mutate(blocknum) %>%
  group_by(dir, blocknum) %>%
  summarise(address = line[[1]], value = digest::digest(value))

match(blocks$value, blocks$value)[(nrow(blocks)/2 + 1):nrow(blocks)]
```

The last line prints out the order in which the misplaced blocks from old.zip, appear in new.zip. I get this:

```
 [1] 20  1  2 21 22  3 23 24  4 25  5 26  6 27 28  7  8 29 30  9 10 31 32 11 12 33 13 14 34 15 16 35 36 17 37 18 38 19
```

If you look closely, it's like one thread is writing from 1-19, and one thread is writing 20-38, and they are being randomly interleaved.

**Comment by wch** [comment] 2021-06-21 21:06
I tried this on a Docker container running on a Linux machine, and I didn't see the problem there: I uploaded the file six times, the MD5 sum matched every time.

**Comment by wch** [comment] 2021-06-21 21:51
I also tried it with Docker on my Mac, and got errors for some versions of Docker, but not for others! I found that newer versions had corrupted data, while an older version did not.

* 3.3.3: Mismatch 3 out of 3 uploads
* 2.5.0.1: Mismatch 3 out of 3 uploads
* 2.2.0.0: Mismatch 0 out of 3 uploads

I downloaded old versions of Docker from https://docs.docker.com/docker-for-mac/release-notes/

I didn't try every version, but you could do a binary search to find which version of Docker introduced the problem.

Some screen shots:

3.3.3:
<img width="947" alt="Screen Shot 2021-06-21 at 4 34 28 PM" src="https://user-images.githubusercontent.com/86978/122832293-c3716e00-d2b0-11eb-98e7-cecb01a24b5a.png">

2.5.0.1:
<img width="780" alt="Screen Shot 2021-06-21 at 4 41 32 PM" src="https://user-images.githubusercontent.com/86978/122832320-ccfad600-d2b0-11eb-8b1e-ae4d67972992.png">

2.2.0.0:
<img width="786" alt="Screen Shot 2021-06-21 at 4 47 30 PM" src="https://user-images.githubusercontent.com/86978/122832333-d08e5d00-d2b0-11eb-9bc6-7f740788f16a.png">

**Comment by wch** [comment] 2021-06-23 17:56
Using Docker 2.5.0.1 and a httpuv web app, I was able reproduce the error, but it happens much less frequently. Out of seven uploads, I saw it happen once.

This is the code to run the httpuv app, using the same Docker image:

```
docker run --rm -ti -p 5099:5099 fredmoser/shinyuploadissue:latest /bin/ash
R

library(httpuv)
outfilename <- "post.zip"

handle_req <- function(req) {
  md5_result <- ""
  if (identical(req$REQUEST_METHOD, "POST")) {
    req_input <- req$rook.input
    message("Writing to ", outfilename)
    
    outfile <- file(outfilename, open='wb')
    while (length(buf <- req_input$read(2^16)) > 0) {
      writeBin(buf, outfile)
    }
    close(outfile)

    md5_result <- system(sprintf('md5sum %s', outfilename) ,intern = TRUE)
    message("md5: ", md5_result)
  }
  
  list(
    status = 200L,
    headers = list(
      'Content-Type' = 'text/html'
    ),
    body = paste0("File was successfully uploaded. md5: ", md5_result)
  )
}


s <- startServer("0.0.0.0", 5099,
  list(
    call = function(req) {
      handle_req(req)
    }
  )
)
```


From the host, I uploaded the file with:

```
curl -X POST --data-binary @data.zip http://127.0.0.1:5099/
```

Result. Notice only one of these had an error:

```
$ curl -X POST --data-binary @data.zip http://127.0.0.1:5099/
File was successfully uploaded. md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip

$ curl -X POST --data-binary @data.zip http://127.0.0.1:5099/
File was successfully uploaded. md5: 1c5746233b39c10c1d334bc3df781d9d  post.zip

$ curl -X POST --data-binary @data.zip http://127.0.0.1:5099/
File was successfully uploaded. md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip

$ curl -X POST --data-binary @data.zip http://127.0.0.1:5099/
File was successfully uploaded. md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip

$ curl -X POST --data-binary @data.zip http://127.0.0.1:5099/
File was successfully uploaded. md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip

$ curl -X POST --data-binary @data.zip http://127.0.0.1:5099/
File was successfully uploaded. md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip

$ curl -X POST --data-binary @data.zip http://127.0.0.1:5099/
File was successfully uploaded. md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
```

This happens much less frequently than with the Shiny app, where I can get the error almost every time. There is also less overhead with this bare httpuv app, because it does less work. This makes me wonder if a buffer is overflowing by getting filled faster than it can write to disk.

**Comment by wch** [comment] 2021-06-23 18:25
One more data point. I used `curl` to upload data to the httpuv web app, from within the same Docker container, and I did see an occasional error.

To reproduce, run the httpuv app from the container above. Then start another terminal in the same container. (You will need to use `docker ps` to find the name of the running container, and replace `<container_name>` below with that name.)

```R
docker exec -ti <container_name> /bin/sh

apk add curl
for i in 1 2 3 4 5 6 7 8 9 10 ; do curl -X POST --data-binary @data.zip http://127.0.0.1:5099/; done
```

After running 10 times, I saw one error:

```
File was successfully uploaded. md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
File was successfully uploaded. md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
File was successfully uploaded. md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
File was successfully uploaded. md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
File was successfully uploaded. md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
File was successfully uploaded. md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
File was successfully uploaded. md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
File was successfully uploaded. md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
File was successfully uploaded. md5: ac3fba2ae35a1d09e09c5aba16439e4a  post.zip
File was successfully uploaded. md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
```

**Comment by wch** [comment] 2021-06-23 22:51
I also tested with a python flask app, and did not see any corruption there.

Using the same docker image, this will run the flask app:

```
docker run --rm -ti -p 5099:5099 fredmoser/shinyuploadissue:latest /bin/ash
apk add --update python3 py3-pip
pip3 install flask

cat <<EOF > srv.py
from flask import Flask, render_template, request, redirect, url_for

app = Flask(__name__)

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/', methods=['POST'])
def upload_file():
    if request.method == 'POST':
        bytes_left = int(request.headers.get('content-length'))
        with open('post.zip', 'wb') as upload:
            chunk_size = 65536
            while bytes_left > 0:
                chunk = request.stream.read(chunk_size)
                upload.write(chunk)
                bytes_left -= len(chunk)
    return "Uploaded file\n"
EOF

export FLASK_APP=srv.py
flask run -h 0.0.0.0 -p 5099
```


And then in another terminal, you can enter the container, then upload the file and calculate the md5sum. This will do it 10 times:

```R
docker exec -ti <container_name> /bin/ash
apk add curl
for i in 1 2 3 4 5 6 7 8 9 10; do
    curl -X POST --data-binary @www/data.zip -H "Content-Type: application/foo"  http://127.0.0.1:5099/
    md5sum  post.zip 
done
```

**Comment by fxi** [comment] 2021-06-24 09:00
Could it be a problem with building `libuv` against MUSL in alpine ? 

It does not explain the "docker mac only" part. Is it still a "mac docker only" problem?

Anyway, I've build another stripped down image (45MB, compressed) to get only `httpuv` and keep things simple, based on your example. It's usable like this manually or in your CI : 

```sh
docker run --rm -ti -p 5099:5099 fredmoser/httpuvuploadissue:latest
# Overwrite app.R
# docker run --rm -ti -v $(pwd)/app.R:/app/app.R -p 5099:5099 fredmoser/httpuvuploadissue:latest
````
And
```sh
#!/bin/bash
for i in {1..20} ; do curl -X POST --data-binary @data.zip http://localhost:5099/; done
```

```sh
listening at http://localhost:5099
md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
md5: bb441537e738459396ad71f6bedddeee  post.zip
md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
md5: d9dc47052560a0ca811b9de42b496435  post.zip
md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
md5: f1015befd8ebfaa0440f644baba2d340  post.zip
```



<details>
<summary > Dockerfile </summary>

```Dockerfile
ARG R_VERSION="4.1.0"
FROM rhub/r-minimal:${R_VERSION} as build_r
ENV R_PACKAGES_DATE="2021-06-15"

RUN echo "local({ \
rep <- getOption('repos'); \
rep['CRAN'] <- 'https://mran.microsoft.com/snapshot/$R_PACKAGES_DATE'; \
options(Ncpus = $(nproc --all)) ; \
options(repos = rep) \
})" > .Rprofile

RUN echo "http://dl-cdn.alpinelinux.org/alpine/v3.11/main" >> /etc/apk/repositories

RUN apk add --no-cache --virtual build_deps \
  linux-headers \
  build-base \
  R-dev \
  autoconf=2.69-r2 \
  automake=1.16.1-r0 

RUN Rscript -e ' install.packages("httpuv")'
RUN apk del build_deps

FROM rhub/r-minimal:${R_VERSION} as final
COPY --from=build_r / /

WORKDIR /app 
COPY app.R . 

CMD ["Rscript","--vanilla","app.R", "5099"]
```

</details>

<details>
<summary> app.R</summary>

```R
library(httpuv)
outfilename <- "post.zip"

handle_req <- function(req) {
  md5_result <- ""
  if (identical(req$REQUEST_METHOD, "POST")) {
    req_input <- req$rook.input
    # message("Writing to ", outfilename)
    
    outfile <- file(outfilename, open='wb')
    n_blocks <- 0
    while (length(buf <- req_input$read(2^16)) > 0) {
      writeBin(buf, outfile)
      n_blocks <- n_blocks + 1
    }
    close(outfile)

    md5_result <- system(sprintf('md5sum %s', outfilename) ,intern = TRUE)
    message("md5: ", md5_result)
  }
  
  list(
    status = 200L,
    headers = list(
      'Content-Type' = 'text/html'
    ),
    body = paste0("File was successfully uploaded. md5: ", md5_result, "\n")
  )
}


s <- startServer("0.0.0.0", 5099,
  list(
    call = function(req) {
      handle_req(req)
    }
  )
)

message('listening at http://localhost:5099');
service(0)

```

</details>

I'm sorry I didn't have more time to dig this: I've got a lot of my plate lately + the second vaccine being nasty + it's way out of my comfort zone ...

**Comment by jcheng5** [comment] 2021-06-24 22:05
@wch Another possibility is `invoke_later`/`later::later` not maintaining FIFO for some reason?
https://github.com/rstudio/httpuv/blob/ee4a0e6ca4fd228160455c6db2feea82ce56f3e7/src/httprequest.cpp#L451-L459

**Comment by jcheng5** [comment] 2021-06-24 23:28
@wch I tried compiling with [thread assertions](https://github.com/rstudio/httpuv/compare/debug), still repros with no errors.

**Comment by jcheng5** [comment] 2021-06-25 00:04
Repros with a rocker/shiny image (Debian based).

**Comment by jcheng5** [comment] 2021-06-25 01:17
It looks like it is indeed an out-of-order `later` problem. With this branch: https://github.com/rstudio/httpuv/compare/debug

```
listening at http://localhost:5099
Out-of-order onBodyData!
md5: df0482b78941bd1f5c01d0497708c9ee  post.zip
md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
Out-of-order onBodyData!
md5: 66145f5d5e4762ed822698001283899d  post.zip
md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
Out-of-order onBodyData!
md5: 5beecacfb08854f714604d2d207ec2a5  post.zip
```

Unfortunately, I have to stop for the day, and I'm out on vacation tomorrow and all of next week...

**Comment by jcheng5** [comment] 2021-06-25 01:24
This looks pretty airtight, what am I missing? https://github.com/r-lib/later/blob/9335226596f85de890e6f8c610d126a855d7ad01/src/callback_registry.h#L26-L33

**Comment by wch** [comment] 2021-06-25 01:25
Maybe the VM has poor time resolution?

**Comment by wch** [comment] 2021-06-25 02:44
I tested different Docker versions, and 2.5.0.0 was the first one which had the problem. I don't see anything that particularly stands out in the [changelog](https://docs.docker.com/docker-for-mac/release-notes/#docker-desktop-community-2500), but maybe it has something to do with the kernel update.

**Comment by wch** [comment] 2021-06-25 14:55
@jcheng5 I made a reproducible example of the execution order problem just using later: https://github.com/r-lib/later/issues/150

**Comment by wch** [comment] 2021-06-26 16:04
@fxi, I believe we've figured out the cause of the problem. In some cases, the `gettimeofday()` function can sometimes return a value that is _less_ that a previous call, which means that the clock has gone backward. In the case here, this is probably because the VM periodically corrects for clock drift. When this happens, the callbacks that are scheduled to write data to disk may execute in the wrong order.

See r-lib/later#150 for more information.

**Comment by fxi** [comment] 2021-06-28 08:30
Impressive work of ( time ) detective ! Thanks :)

As a quick recap, this is originally an issue with the docker (>2.5.0.0) VM on mac, but could be solved in `later` for unix platform with the use of monotonic clock time source such as `clock_gettime(CLOCK_BOOTTIME` ( or  apparently `clock_get_time(...` [on mac](https://gist.github.com/jbenet/1087739) .. ). 

It seems that a patch is already on its way to cover this, so I will wait for the next release. If not, I would appreciate having more details.

Thanks again !

**Comment by wch** [comment] 2021-06-28 20:25
@fxi, can you test with the fix in r-lib/later#151?

**Comment by fxi** [comment] 2021-06-29 08:46
Thanks ! 

It seems to work well in docker/alpine using docker desktop for mac (3.4.0 65384, engine 20.10.7). 

I ran the test below natively on macOS (11.4, R 4.0.5), same result, as expected.


### httpuv


```sh
# Launch server
docker run --rm -ti -p 5099:5099 fredmoser/httpuvuploadissue:later-monotonic-fix
# Upload test 
for i in {1..20} ; do curl -X POST --data-binary @data.zip http://localhost:5099/; done
# Result
listening at http://localhost:5099
md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
md5: aeb957f11a4ff8453dc04152f6d7f08c  post.zip
```

<details>
<summary>Dockerfile (45.8 MB) </summary>

```Dockerfile
ARG R_VERSION="4.1.0"
FROM rhub/r-minimal:${R_VERSION} as build_r
ENV R_PACKAGES_DATE="2021-06-15"

RUN echo "local({ \
rep <- getOption('repos'); \
rep['CRAN'] <- 'https://mran.microsoft.com/snapshot/$R_PACKAGES_DATE'; \
options(Ncpus = $(nproc --all)) ; \
options(repos = rep) \
})" > .Rprofile

RUN echo "http://dl-cdn.alpinelinux.org/alpine/v3.11/main" >> /etc/apk/repositories

RUN apk add --no-cache --virtual build_deps \
  linux-headers \
  build-base \
  R-dev \
  autoconf=2.69-r2 \
  automake=1.16.1-r0 

RUN Rscript -e 'install.packages("remotes")'
RUN Rscript -e 'remotes::install_github("r-lib/later@fix-clock-monotonic")'
RUN Rscript -e 'install.packages("httpuv")'

RUN apk del build_deps

FROM rhub/r-minimal:${R_VERSION} as final
COPY --from=build_r / /

WORKDIR /app 
COPY app.R . 

CMD ["Rscript","--vanilla","app.R", "5099"]
```

</details>


<details>
<summary>App</summary>

```R
library(httpuv)
outfilename <- "post.zip"

handle_req <- function(req) {
  md5_result <- ""
  if (identical(req$REQUEST_METHOD, "POST")) {
    req_input <- req$rook.input
    # message("Writing to ", outfilename)
    
    outfile <- file(outfilename, open='wb')
    n_blocks <- 0
    while (length(buf <- req_input$read(2^16)) > 0) {
      writeBin(buf, outfile)
      n_blocks <- n_blocks + 1
    }
    close(outfile)

    md5_result <- system(sprintf('md5sum %s', outfilename) ,intern = TRUE)
    message("md5: ", md5_result)
  }
  
  list(
    status = 200L,
    headers = list(
      'Content-Type' = 'text/html'
    ),
    body = paste0("File was successfully uploaded. md5: ", md5_result, "\n")
  )
}


s <- startServer("0.0.0.0", 5099,
  list(
    call = function(req) {
      handle_req(req)
    }
  )
)

message('listening at http://localhost:5099');
service(0)
```

</details>


### shiny

```sh
# Launch server
docker run --rm -ti -p 5099:5099 fredmoser/shinyuploadissue:later-monotonic-fix
Listening on http://0.0.0.0:5099
```
![image](https://user-images.githubusercontent.com/1196833/123759941-aea06600-d8c0-11eb-9492-5c0dce574a0d.png)


<details>
<summary>Dockerfile (1007.69 MB, incl. data) </summary>

```Dockerfile
ARG R_VERSION="4.1.0"
FROM rhub/r-minimal:${R_VERSION} as build_r
ENV R_PACKAGES_DATE="2021-06-15"

RUN echo "local({ \
rep <- getOption('repos'); \
rep['CRAN'] <- 'https://mran.microsoft.com/snapshot/$R_PACKAGES_DATE'; \
options(Ncpus = $(nproc --all)) ; \
options(repos = rep) \
})" > .Rprofile

RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
# R httuv -> autoconf + automake specific version -> 3.11 main
RUN echo "http://dl-cdn.alpinelinux.org/alpine/v3.11/main" >> /etc/apk/repositories

RUN apk add --no-cache \
    libpng \
    libxml2 \
    icu-libs \
    ca-certificates

RUN apk add --no-cache --virtual build_deps \
  linux-headers \
  build-base \
  R-dev \
  libressl-dev \
  libxml2-dev \
  tiff-dev \
  libpng-dev \
  pcre2-dev \
  m4 \
  zip \
  file \
  autoconf=2.69-r2 \
  automake=1.16.1-r0 

RUN Rscript -e 'install.packages("remotes")'
RUN Rscript -e 'remotes::install_github("r-lib/later@fix-clock-monotonic")'
RUN Rscript -e 'install.packages("shiny")'
RUN apk del build_deps

FROM rhub/r-minimal:${R_VERSION} as final
COPY --from=build_r / /

WORKDIR /app 
COPY /www/data.zip /app/www/data.zip
COPY run.R .
COPY app.R . 

CMD ["Rscript","--vanilla","run.R", "5099"]
```

</details>

<details>
<summary>App</summary>

```R
# app.R
options(shiny.maxRequestSize=2e3*1024^2)

ui <- bootstrapPage(
  tags$label('1) Download the sample file (~980MB)'),
  tags$a(href="data.zip", "Download", download=NA, target="_blank"),
  fileInput('file', '2) Re-upload it a few times'),
  tags$label('MD5 check sum before:'),
  textOutput('md5Before'),
  tags$label('MD5 check sum after (sometimes it does not match)'),
  textOutput('md5After')
)

server <- function(input, output) {

  output$md5After <- renderText({
    if (is.null(input$file)) return("No file uploaded")
    system(sprintf('md5sum %1$s',input$file$datapath),intern=T) 
  })

  output$md5Before <- renderText({
    system(sprintf('md5sum %1$s','www/data.zip'),intern=T) 
  })

  
}

shinyApp(ui = ui, server = server)
```

```R
# run.R ( for docker CMD )
library(shiny)
port <- 3434
args <- commandArgs(trailingOnly=TRUE)
if(length(args)>0){
  port <- as.numeric(args[1])
}
runApp(".",host="0.0.0.0",launch.browser=F,port=port)
```

</details>

**Comment by wch** [comment] 2021-06-29 17:56
@fxi, thanks for testing! I've merged the later PR.

**Closed by wch** 2021-06-29 17:56 UTC
