### ISSUE TITLE
/012-datatables/ on Edge (and shinyapps.io) looks weird with showcase mode

### ISSUE THREAD

**Issue by bborgesr** [rstudio/shiny#1636] opened 2017-03-30 00:12 UTC
![screen shot 2017-03-30 at 1 09 59 am](https://cloud.githubusercontent.com/assets/6527540/24481934/c84af550-14e5-11e7-977c-0dde5adf1a01.png)

![screen shot 2017-03-30 at 1 12 05 am](https://cloud.githubusercontent.com/assets/6527540/24481954/e983f83e-14e5-11e7-8dfe-5d98f303f0ea.png)

**Comment by bborgesr** [comment] 2017-03-30 03:36
Also happening on SSP with Safari, so I guess, this is a general issue of datatables and showcase mode (and only when the datatable isn't present from the start):

![screen shot 2017-03-30 at 4 32 42 am](https://cloud.githubusercontent.com/assets/6527540/24486469/2eaa8470-1502-11e7-9b70-c98c5ed23ab9.png)

@wch can you confirm you also see this with the new version of Safari?

**Comment by wch** [comment] 2017-03-30 03:40
Yup, looks weird:

![image](https://cloud.githubusercontent.com/assets/86978/24486588/76e55954-14d0-11e7-8c61-9ef1cf5bca01.png)

But it also looks weird on Chrome:

![image](https://cloud.githubusercontent.com/assets/86978/24486599/94355a68-14d0-11e7-9691-dde8dc720aa3.png)

I think this is due to the way that DataTables does its sizing.

**Comment by bborgesr** [comment] 2017-03-30 18:31
possible fix: `overflow:hidden` or `overflow:auto` on the left side of the showcase mode container (td .showcase-app-container-expanded)

**Comment by alandipert** [comment] 2019-05-08 19:49
Closing because probably duplicate of #1659 and appears to be fixed in latest Edge.

**Closed by alandipert** 2019-05-08 19:49 UTC
