### ISSUE TITLE
fileInput no longer works with IE9

### ISSUE THREAD

**Issue by jcheng5** [rstudio/shiny#1332] opened 2016-08-30 19:36 UTC
Choosing a file results in the following browser error:

```
Line: 3
Error: Unable to get value of the property 'length': object is null or undefined
```

Tested on IE 9.0.8112.16421 on Windows 7.

**Comment by jcheng5** [comment] 2016-08-30 19:38
No repro with IE 11

**Comment by bborgesr** [comment] 2017-01-08 15:14
Hmm, I think this is malfunctioning again, but it seems like it has a different error message... It shows the prompt to choose the file to upload:

<img width="1440" alt="screen shot 2017-01-08 at 2 57 05 pm" src="https://cloud.githubusercontent.com/assets/6527540/21750773/e3193a80-d5b2-11e6-974e-ecb94b289796.png">

But, as soon, as I select it, it gives a error and a while laster the app crashes:

![Uploading Screen Shot 2017-01-08 at 2.57.15 PM.png…]()

**Comment by jcheng5** [comment] 2017-01-08 17:14
Any repro with either of these IE9 bugs with earlier versions of Shiny?

**Comment by wch** [comment] 2017-01-09 16:25
I'm able to repro this on shinyapps.io, and when running in a local R session.

With `options(shiny.minified=F)`, I get this in my console:


```
SCRIPT5007: Unable to get value of the property 'sessionId': object is null or undefined 
shiny.js, line 4694 character 7
SCRIPT5007: Unable to get value of the property 'readyState': object is null or undefined 
shiny.js, line 834 character 7
```

**Comment by wch** [comment] 2017-01-09 16:37
Actually, looking over the history of this and related issues, I think this is all as expected.

* Running the app locally won't work with IE9, because running apps locally doesn't work at all with IE9 -- it requires Shiny Server.
* We knew that file uploads didn't work with IE9 and shinyapps.io, but decided not to invest time in the issue: #1352.
* File uploads with IE9 **do** work on RSC: https://beta.rstudioconnect.com/content/1598/. This deployed app is with v1.0.0-rc.

I will test IE9 on Shiny Server and Shiny v1.0.0-rc. If that works, I think we can close this issue.

**Comment by wch** [comment] 2017-01-09 17:01
I've confirmed that file uploads work fine with IE9 + Shiny 1.0.0-rc on Shiny Server, so I think we can close this.

**Comment by bborgesr** [comment] 2017-01-09 18:11
Ah, I didn't realize we'd already noticed this problem in #1352. So, I'm fine with closing this if our opinion continues to be that it isn't worth it to invest time on this...

FYI, now that I have functioning internet again, here's the screenshot of the bug: after I select the dataset, it gives me an error message, and moments later the app crashes:

<img width="1440" alt="screen shot 2017-01-08 at 3 25 53 pm" src="https://cloud.githubusercontent.com/assets/6527540/21777498/1d395eb0-d66d-11e6-9c17-c6563cfce808.png">

**Closed** 2017-01-09 18:37 UTC
Labels: P1
