### ISSUE TITLE
fileInput accept Variable Does Not Restrict Choice of File Types

### ISSUE THREAD

**Issue by DarioS** [rstudio/shiny#951] opened 2015-09-10 08:00 UTC
For example, I use `fileInput("fileChooser", "Upload a Processed File", accept = "text/plain")` but the file chooser shows all types of files. Also, the documentation should explicitly state what MIME value to provide for `RData` files. I can't find that extension in the [MIME type list](http://www.sitepoint.com/web-foundations/mime-types-complete-list/).

**Comment by daattali** [comment] 2015-09-18 01:21
@DarioS are you seeing this behaviour in a browser?  In the RStudio viewer the file chooser indeed does not filter file types, but in a browser it should. I just tried your example and in my Chrome on Windows it only showed me files ending in `.txt`

**Comment by DarioS** [comment] 2015-09-22 08:00
I only experience it in RStudio's browser. The question about the MIME type of `RData` files also remains.

**Comment by daattali** [comment] 2015-09-22 08:02
The fact that it doesn't work in an rstudio browser is known and I wouldn't worry about that.  I would try `accept = ".RData"` or whatever the extension of your files are (`.rda` perhaps?)

**Comment by rickyars** [comment] 2017-03-09 19:46
How does one prevent file uploads by file type? I set the accept variable but I can still select other files (in both Rstudio and the browser). This really isn't a matter of restricting what's selectable. I want to make sure no files are stored on the server if they aren't of the correct type. Is this possible?

**Comment by alandipert** [comment] 2019-04-26 23:26
@DarioS afaik `RData` doesn't have an official MIME type associated with it, so no browser's file chooser dialog would know how to recognize `RData` files. Maybe `application/binary` would be acceptable? At least then plain text files would be excluded by the browser.

@rickyars To my knowledge, what you want isn't possible. A workaround might be to inspect the file yourself after it's uploaded, deleting it if it fails whatever tests you perform.

I was able to reproduce this on RStudio 1.2.1335 on macOS and was not able to reproduce on Firefox 66 or Chrome 73 (also on macOS), so I think this issue is particular to RStudio.

Consequently I'm closing this and have [opened an issue on rstudio/rstudio](https://github.com/rstudio/rstudio/issues/4718). Please don't hesitate to comment further or open a new issue if you still have problems.

**Closed by alandipert** 2019-04-26 23:26 UTC

**Comment by daattali** [comment] 2019-04-26 23:32
I wonder if it's worth having a place to gather issues that are specific to the RStudio browser, because over the years I've ran into many issues that are specific to RStudio, and when someone told me "shiny has a bug; X is happening" I already knew to tell them that as soon as they'll move to a real browser, it won't happen anymore. But I never saw a place that collected a list of these known issues.

**Comment by alandipert** [comment] 2019-04-26 23:33
@daattali I think the rstudio/rstudio issues is probably the best place to aggregate them, once we know they're specific to RStudio.

**Comment by alandipert** [comment] 2019-04-26 23:39
Oh, and PSA: RStudio 1.2+'s browser is based on Chromium, so there should be way fewer weird browser problems with RStudio Desktop moving forward.

**Comment by guybrettrobertson** [comment] 2022-04-07 11:54
Anyone know of any new developments regarding this issue?

It seems not to have been fixed and I think it means that R Shiny applications in production that require fileInput can allow any kind of file to be uploaded including malicious .exe files. I really hope this isn't the case!

**Comment by michaelhogersnplm** [comment] 2022-04-07 12:45
@guybrettrobertson Interesting question I think, thought I'd explain a bit below for others as well 

I suggest to always check on Shiny's server side (inside an event handler) the file extension using, for example, tools::file_ext() on (in this original post's case) input$fileChooser$datapath. If the file extension is incorrect you could ask the user to retry the upload.

In the example in the original post the argument `accept="text/plain"` for the `fileInput` function results in a HTML input tag with an attribute `accept="text/plain"` which can easily be circumvented/changed by any application user since it is only a client side restriction..

So I think one should not worry about safety issues arising from the accept = "" argument, as often the application should perform an additional file extension check regardless of the client side restriction. That said, one may want to perform a virus scan before uploading a file to a file storage solution or once uploaded into a file storage solution. Some file storage solutions of cloud providers may allow you to scan all files for viruses which should add a layer of security regarding malicious files. Virus scanning is a bit outside of the scope of Shiny itself though.
