### ISSUE TITLE
dateInput/dateRangeInput with NA default and min allowed date not obeying max allowed date 

### ISSUE THREAD

**Issue by andrewjpfeiffer** [rstudio/shiny#2679] opened 2019-10-22 21:38 UTC
### System details

Browser Version: Not applicable

Output of `sessionInfo()`:

```
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_1.4.0

loaded via a namespace (and not attached):
 [1] compiler_3.6.1  fastmap_1.0.1   magrittr_1.5    R6_2.4.0        promises_1.1.0 
 [6] later_1.0.0     htmltools_0.4.0 tools_3.6.1     Rcpp_1.0.2      jsonlite_1.6   
[11] digest_0.6.22   xtable_1.8-4    httpuv_1.5.2    mime_0.7        rlang_0.4.0
```

#### dateInput

```R
library(shiny)

ui <- fluidPage(
  dateInput("date_in", "Choose date", value = as.Date(NA),
            min = "2019-10-20", max = "2019-10-30"),
)

shinyApp(ui = ui, server = function(input, output) {})
```

#### dateRangeInput

```R
library(shiny)

ui <- fluidPage(
  dateRangeInput("date_range_in", "Choose date range",
                 start = as.Date(NA), end = as.Date(NA),
                 min = "2019-10-20", max = "2019-10-30")
)

shinyApp(ui = ui, server = function(input, output) {})
```

### Describe the problem in detail

I want to include a date picker and a date range picker in my Shiny application with:

- No default date(s)
- A minimum allowed date
- A maximum allowed date.

However, the date picker does not obey the maximum allowed date, specified with the `max` argument.

#### Similar code that works

The function `dateInput()` obeys the `max` argument when:

* I remove `value = as.Date(NA)`, setting the default date to today.
* I remove `min = "2019-10-20"`, removing the minimum allowed date.

Similarly, the function `dateRangeInput()` obeys the `max` argument when:

* I remove `start = as.Date(NA)` and `end = as.Date(NA)`, setting the default dates to today.
* I remove `min = "2019-10-20"`, removing the minimum allowed date.

#### StackOverflow reference

https://stackoverflow.com/questions/58494839/r-shiny-dateinput-not-obeying-max-allowed-date-when-na-default-and-min-allowed-d

**Comment by ismirsehregal** [comment] 2019-10-24 14:06
Seems to be the same problem as reported [here](https://github.com/rstudio/shiny/issues/2663).

**Comment by cpsievert** [comment] 2020-09-09 17:17
Closing as this as a duplicate of https://github.com/rstudio/shiny/issues/2703 which will be fixed by https://github.com/rstudio/shiny/pull/3038

**Closed by cpsievert** 2020-09-09 17:17 UTC
