### ISSUE TITLE
New shiny version (0.12.2.9006) not working with following code

### ISSUE THREAD

**Issue by maxmoro** [rstudio/shiny#1042] opened 2015-12-18 18:53 UTC
The following code is working with shiny version on CRAN, but not with 0.12.2.9006
This is a very-stripped-down version of a bigger application, so forgive weird naming..
Basically, if I run this with the new shiny version in github, it doesn't work. But, if I remove one of the two controls, it works. 
What am I doing wrong?

```r


library(shiny)
library(shinydashboard)
shinyApp(
    ui = dashboardPage(title='Time Application'
                       #header
                       ,dashboardHeader(title=strong(h4("Time Application")),titleWidth='150px')
                       #left side tabs
                       ,dashboardSidebar(
                           sidebarMenu(id='tabs',menuItem("Filters",icon=icon("filter"), tabName='tab_parameters')) 
                           ,width='150px'
                       )
                       #body of the application, based on the tab
                       ,dashboardBody(
                           tabItems(
                               tabItem(tabName = 'tab_parameters'
                                       ,fluidRow(
                                           box(width=6,title='Filters'
                                               #remove dateRange input and  it works
                                               ,dateRangeInput("period"
                                                               , label ="Period"
                                                               , min  = '2013-01-01'
                                                               , max  = '2016-01-01'
                                                               , start = '2013-01-01'
                                                               , end = '2016-01-01'
                                               )
                                           )
                                       )
                                       ,fluidRow(width=12,box(status='success',title='Group By' 
                                                              ,selectizeInput( "OT_summary_criteria"
                                                                               , label =NULL
                                                                               , multiple=TRUE
                                                                               , choices = c('a','b')
                                                                               , selected ='a'
                                                                               #remove next line and it works
                                                                               , options=list(plugins = list('remove_button','drag_drop'))
                                                              )
                                       ))
                                       ,"You should see something here below if it works:"
                                       ,textOutput('infot')
                               )
                           )
                       )
    )
    ,
    server =
        function(input, output, session) {
            output$infot = renderText( paste0('IT IS WORKING'))
        }
)
```

**Comment by maxmoro** [comment] 2016-01-05 15:28
Still not working with the current DEVL version, anyone can test the code? Thanks!

**Comment by wch** [comment] 2016-01-05 15:46
Here's a minimal example. I believe the problem is an incompatibility with the `drag_drop` plugin and jQuery UI.

```R
library(shiny)
shinyApp(
  ui = fluidPage(
    dateRangeInput("time",
      label ="Time"
    ),
    selectizeInput("select",
      label = NULL,
      choices = 'a'
      # Remove next line and it works
      ,options = list(plugins = list('drag_drop'))
    ),
    "You should see text here below if it works:",
    textOutput('infot')
  ),
  server = function(input, output, session) {
    output$infot = renderText(paste0('App is working'))
  }
)
```

**Comment by maxmoro** [comment] 2016-01-05 16:07
Good catch, thanks! 
What should I do to have the drag_drop working?
Max

**Comment by wch** [comment] 2016-01-05 16:10
It should just work without trouble, so I think it's a problem that needs to be addressed in Shiny. I'm looking into it.

**Closed** 2016-01-05 17:04 UTC

**Comment by wch** [comment] 2016-01-05 17:05
OK, it should be fixed now. The problem was that we switched to a complete build of jQuery UI, but we should have left out the datepicker, as noted in this comment: https://github.com/rstudio/shiny/blob/8e89a1f/R/jqueryui.R#L83-L84

**Comment by maxmoro** [comment] 2016-01-05 17:18
Yes! It is working now!

Thank you very much.
Max
