### ISSUE TITLE
renderTable digit does not perform the same as xtable 

### ISSUE THREAD

**Issue by mtvincen** [rstudio/shiny#2539] opened 2019-08-01 00:32 UTC
I have a table that I produced by xtable that I use in a report that has different significant digits for different row. I made use of assigning each element in the table with a digit value in a matrix. I tried using the same digit arguments in an xtable  arguement that is then sent to renderTable, but they seem to be ignored. In addition, when I out the digit arguments in the renderTable they appeared to be ignored and a default of 2 is applied everywhere

I am trying to reproduce the table interactively through R shiny but cannot because the digit option only takes a single value. Can you change the functionality in renderTable to reproduce what is used in the xtable environment?

**Comment by cpsievert** [comment] 2019-09-11 15:36
Duplicate of https://github.com/rstudio/shiny/issues/2596

**Closed by cpsievert** 2019-09-11 15:36 UTC
