### ISSUE TITLE
outputOptions Documentation Examples Errors

### ISSUE THREAD

**Issue by DarioS** [rstudio/shiny#1233] opened 2016-07-06 07:00 UTC
Even trying the first example of the help page causes an error.

    library(shiny)
    
    server <- shinyServer(function(input, output, session)
    {
        outputOptions(output)
    })
    
    ui <- fluidPage(plotOutput("aPlot"))
    
    shinyApp(ui = ui, server = server)

Should list the output objects, but results in the error:

    Error in .subset2(x, "ns"): argument "name" is missing, with no default

Calling the function with a `name` value also fails : 

    outputOptions(output, "aPlot") # Replace server function's code with this.

    # Results in a different error.
    Error in .subset2(x, "impl")$outputOptions(name, ...) : 
      aPlot is not in list of output objects

Perhaps if examples could be designed that could be run during `R CMD check`, such as applications that terminate after a couple of seconds automatically, these problems could be found quicker.

**Comment by bborgesr** [comment] 2016-07-06 13:24
You're half right. The first problem (the first example of the docs, which doesn't include a `name`) was a bug and I just fixed in the Shiny's development version. As for the the other examples, that's actually the expected behavior, since you do not define any output observers (the code in the `ui` just basically "reserves" that space for a future plot). It will work just fine if you include a `output$aPlot <- renderPlot({...})` in your `server` function:

```r
library(shiny)

server <- shinyServer(function(input, output, session)
{
  output$aPlot <- renderPlot(plot(cars))
  print(outputOptions(output, "aPlot"))
})

ui <- fluidPage(plotOutput("aPlot"))

shinyApp(ui = ui, server = server)
```

**Closed by bborgesr** 2016-07-06 13:24 UTC
