### ISSUE TITLE
get user ip in r shiny through  shinyapps.io

### ISSUE THREAD

**Issue by acharmie** [rstudio/shiny#2291] opened 2018-12-27 10:51 UTC
Hi,
I have hosted my shiny app on shinyapps.io .I want to  know the ip address of users & geographic information to know who is using my shinyapp for commercial purpose.

Please tell me how to do this using r shiny & provide code if possible.
I am using separate server.r & ui.r file thanks

**Comment by nteetor** [comment] 2018-12-27 14:09
Hello @acharmie, it doesn't sound like you are reporting a bug, so I would recommend asking your question over at https://community.rstudio.com/. I think many (dare I say most) people find success when posting on rstudio community. I hope someone can help.

**Comment by alandipert** [comment] 2019-05-01 19:41
Hello, thank you for the report. Unfortunately there isn't currently a way to retrieve the client's IP address from a Shiny application on shinyapps.io, since it's not something we expose via `session$clientData`. Accessing the client's IP would be the first step toward guessing the client's location.

However, we are tracking this enhancement with #141.

An alternative you might consider is collecting location information directly from the user's browser, with their consent. I haven't tried it, but this looks like a way to do just that: https://github.com/AugustT/shiny_geolocation

I'm closing this because it's a duplicate of #141, but if you have additional questions please don't hesitate to comment further on this issue or create a new one.

**Closed by alandipert** 2019-05-01 19:41 UTC
