### ISSUE TITLE
ERROR: [on_request_read] connection reset by peer

### ISSUE THREAD

**Issue by earthcli** [rstudio/shiny#1550] opened 2017-01-20 01:10 UTC
when I update shiny package from version  0.13.2 to version 1.0, I got an error of "ERROR: [on_request_read] connection reset by peer".
How can I check my program?

ps: I have checked that the error start from version   0.14 to version 0.14.1.

**Comment by bborgesr** [comment] 2017-01-23 22:54
Are you using any "out of the ordinary" features in your app? Does this happen only in a particular browser? Also, can you give us a minimal reproducible example?

**Comment by ak-koli** [comment] 2017-05-06 19:09
I'm also facing the same issue. I'm using citr package in Rstudio. But the shiny citation app crashes with this error:
> citr:::insert_citation()

Listening on http://127.0.0.1:3873
Warning in RefManageR::ReadBib(file, check = FALSE) :
  
F:/thesis-HANDmade-akk/My Library.bib:2212:0
	syntax error, unexpected TOKEN_LITERAL, expecting TOKEN_ABBREV or TOKEN_COMMA or TOKEN_KEY
	Dropping the entry `burke_indian_2012` (starting at line 2196) 
Warning: Error in .BibEntryCheckBibEntry1: A bibentry of bibtype ‘InCollection’ has to specify the field: editor
Stack trace (innermost first):
    80: .BibEntryCheckBibEntry1
    79: $<-.BibEntry
    78: $<-
    77: MakeKeysUnique
    76: c.BibEntry
    75: <Anonymous>
    74: do.call
    73: eval
    72: eval
    71: withProgress
    70: <reactive>
    59: bibliography
    58: observerFunc
     3: shiny::runApp
     2: runGadget
     1: citr:::insert_citation
ERROR: [on_request_read] connection reset by peer
 
> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_India.1252  LC_CTYPE=English_India.1252   
[3] LC_MONETARY=English_India.1252 LC_NUMERIC=C                  
[5] LC_TIME=English_India.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_1.0.3

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.10      rstudioapi_0.6    knitr_1.15.1     
 [4] magrittr_1.5      xtable_1.8-2      R6_2.2.0         
 [7] bibtex_0.4.0      plyr_1.8.4        httr_1.2.1       
[10] stringr_1.2.0     tools_3.4.0       miniUI_0.1.1     
[13] htmltools_0.3.6   yaml_2.1.14       assertthat_0.2.0 
[16] rprojroot_1.2     digest_0.6.12     bookdown_0.3     
[19] RJSONIO_1.3-0     RefManageR_0.13.1 bitops_1.0-6     
[22] RCurl_1.95-4.8    curl_2.6          evaluate_0.10    
[25] mime_0.5          rmarkdown_1.5     stringi_1.1.5    
[28] compiler_3.4.0    citr_0.2.0        backports_1.0.5  
[31] XML_3.98-1.7      lubridate_1.6.0   jsonlite_1.4     
[34] httpuv_1.3.3

**Comment by alandipert** [comment] 2019-05-02 20:00
Hello, thank you for the report, and sorry to take so long to get back to you.

I'm closing this since I'm unable to reproduce it and because it's likely fixed in recent versions of httpuv, a package Shiny depends on: rstudio/httpuv#75

If after updating Shiny and httpuv you still have the problem, don't hesitate to comment further here or create a new issue.

**Closed by alandipert** 2019-05-02 20:00 UTC
