### ISSUE TITLE
Shiny: Constrain dateRangeInput min date & max date

### ISSUE THREAD

**Issue by enuma-elis** [rstudio/shiny#2563] opened 2019-08-28 07:17 UTC
I am missing an useful feature in Shiny's dateRangeInput. When selecting the date it would constrain the max date so that it can't be lower than the min date (and the min date that it can't be higher than the max date). Atm, you can select min dates which are later than max dates, which leads to missing data errors in shiny.

**Comment by ColinFay** [comment] 2019-08-28 09:49
See #2043

**Comment by cpsievert** [comment] 2019-09-11 15:38
Duplicate of #2043

**Closed by cpsievert** 2019-09-11 15:38 UTC
