### ISSUE TITLE
Errors with `_R_CHECK_LENGTH_1_CONDITION_` = "true" and `_R_CHECK_LENGTH_1_LOGIC2_` = "true"

### ISSUE THREAD

**Issue by mgirlich** [rstudio/shiny#2656] opened 2019-10-08 07:21 UTC
In R 3.6 there are two useful flags (`_R_CHECK_LENGTH_1_CONDITION_` = "true", `_R_CHECK_LENGTH_1_LOGIC2_` = "true") to have stricter checking on `==` in an if statement and `&&` and `||`. I noticed that `observeEvent` doesn't seem to work with these new settings. It would probably be a good idea to use these flags for checking all functions and get rid of these errors.

``` r
library(shiny)

Sys.setenv(
  `_R_CHECK_LENGTH_1_CONDITION_` = "true",
  `_R_CHECK_LENGTH_1_LOGIC2_` = "true"
)

shinyApp(
  ui = fluidPage(
    column(4,
           numericInput("x", "Value", 5),
           br(),
           actionButton("button", "Show")
    )
  ),
  server = function(input, output) {
    observeEvent(input$button, {
      cat("Showing", input$x, "rows\n")
    })
  }
)

## Error in &&: 'length(x) = 3 > 1' in coercion to 'logical(1)'
```

<div class="muted well" style="width: 100% ; height: 400px ; text-align: center; box-sizing: border-box; -moz-box-sizing: border-box; -webkit-box-sizing: border-box;">

Shiny applications not supported in static R Markdown documents

</div>

<sup>Created on 2019-10-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by wch** [comment] 2019-10-11 21:29
I don't get this error when I run the same code. Can you update your packages and try again?

```
> sessioninfo::session_info()
─ Session info ─────────────────────────────────────────────────────────────────────
 setting  value                                             
 version  R Under development (unstable) (2019-09-18 r77193)
 os       macOS Mojave 10.14.6                              
 system   x86_64, darwin18.7.0                              
 ui       RStudio                                           
 language (EN)                                              
 collate  en_US.UTF-8                                       
 ctype    en_US.UTF-8                                       
 tz       America/Chicago                                   
 date     2019-10-11                                        

─ Packages ─────────────────────────────────────────────────────────────────────────
 package     * version    date       lib source           
 assertthat    0.2.1      2019-03-21 [1] CRAN (R 3.7.0)   
 cli           1.1.0      2019-03-19 [1] CRAN (R 3.7.0)   
 crayon        1.3.4      2017-09-16 [1] CRAN (R 3.7.0)   
 digest        0.6.21     2019-09-20 [1] CRAN (R 3.7.0)   
 fastmap       1.0.1      2019-10-08 [1] CRAN (R 3.7.0)   
 htmltools     0.4.0      2019-10-04 [1] CRAN (R 3.7.0)   
 httpuv        1.5.2.9000 2019-09-24 [1] local            
 jsonlite      1.6        2018-12-07 [1] CRAN (R 3.7.0)   
 later         1.0.0      2019-10-04 [1] CRAN (R 3.7.0)   
 magrittr      1.5        2014-11-22 [1] CRAN (R 3.7.0)   
 mime          0.7        2019-06-11 [1] standard (@0.7)  
 packrat       0.5.0      2018-11-14 [1] CRAN (R 3.7.0)   
 promises      1.1.0      2019-10-04 [1] CRAN (R 3.7.0)   
 R6            2.4.0      2019-02-14 [1] CRAN (R 3.7.0)   
 Rcpp          1.0.2      2019-07-25 [1] CRAN (R 3.7.0)   
 rlang         0.4.0      2019-06-25 [1] CRAN (R 3.7.0)   
 rsconnect     0.8.15     2019-07-22 [1] CRAN (R 3.7.0)   
 rstudioapi    0.10       2019-03-19 [1] standard (@0.10) 
 sessioninfo   1.1.1      2018-11-05 [1] standard (@1.1.1)
 shiny       * 1.4.0      2019-10-10 [1] CRAN (R 3.7.0)   
 withr         2.1.2      2018-03-15 [1] CRAN (R 3.7.0)   
 xtable        1.8-4      2019-04-21 [1] standard (@1.8-4)
```

**Comment by mgirlich** [comment] 2019-10-14 10:16
Sorry, the code above was wrong... In copy pasting I accidentally set these options to false instead of true. So, you might want to check again.

**Comment by wch** [comment] 2019-10-14 18:58
OK, that works. We'll look into it.

**Comment by daattali** [comment] 2020-01-10 18:47
`renderText()` (and probably many other functions) also break when `_R_CHECK_LENGTH_1_CONDITION_` is set.

```
library(shiny)
shinyApp(
  ui = fluidPage(
    textOutput("test")
  ),
  server = function(input, output, session) {
    output$test <- renderText("test")
  }
)
```

```
Listening on http://127.0.0.1:7477
Warning: Error in &&: 'length(x) = 3 > 1' in coercion to 'logical(1)'
  63: .rs.findBreakpointSteps
  62: .rs.findBreakpointSteps
  61: .rs.findBreakpointSteps
  60: .rs.findBreakpointSteps
  59: .rs.removeBreakpoints
  58: registerShinyDebugHook
  57: registerDebugHook
  56: wrapFunctionLabel
  55: .subset2(x, "impl")$defineOutput
  54: $<-.shinyoutput
  52: server [#6]
Error in is.call(funBody[[idx]]) && as.character(funBody[[idx]][[1]]) ==  : 
  'length(x) = 3 > 1' in coercion to 'logical(1)'

Error during wrapup: 'length(x) = 2 > 1' in coercion to 'logical(1)'
```

**Comment by wch** [comment] 2020-01-10 19:15
@daattali How did you get that stack trace? When I run the following code, I just see this:

```R
library(shiny)

Sys.setenv(
  `_R_CHECK_LENGTH_1_CONDITION_` = "true",
  `_R_CHECK_LENGTH_1_LOGIC2_` = "true"
)

shinyApp(
  ui = fluidPage(
    textOutput("test")
  ),
  server = function(input, output, session) {
    output$test <- renderText("test")
  }
)
```

output:

```
> library(shiny)
> Sys.setenv(
+   `_R_CHECK_LENGTH_1_CONDITION_` = "true",
+   `_R_CHECK_LENGTH_1_LOGIC2_` = "true"
+ )
> shinyApp(
+   ui = fluidPage(
+     textOutput("test")
+   ),
+   server = function(input, output, session) {
+     output$test <- renderText("test")
+   }
+ )

Listening on http://127.0.0.1:3561

Error during wrapup: 'length(x) = 2 > 1' in coercion to 'logical(1)'

Error during wrapup: 'length(x) = 2 > 1' in coercion to 'logical(1)'
```

**Comment by daattali** [comment] 2020-01-10 19:17
I'm not sure why I see it. I don't have anything in my Rprofile

**Comment by schloerke** [comment] 2020-03-12 20:57
Ah! It's an IDE bug. Will submit an issue there soon.

-----

Didn't know about the sys envs. Neat!

**Comment by wch** [comment] 2020-03-12 21:08
For the record, the error occurs only in the RStudio IDE, and not in the terminal.

When setting the variables to `"verbose"`, the stack trace points to `.rs.isSourceCall()`.



```R
library(shiny)

Sys.setenv(
  `_R_CHECK_LENGTH_1_CONDITION_` = "verbose",
  `_R_CHECK_LENGTH_1_LOGIC2_` = "verbose"
)

shinyApp(
  ui = fluidPage(
    column(4,
           numericInput("x", "Value", 5),
           br(),
           actionButton("button", "Show")
    )
  ),
  server = function(input, output) {
    observeEvent(input$button, {
      cat("Showing", input$x, "rows\n")
    })
  }
)
```

```
Listening on http://127.0.0.1:6057

 ----------- FAILURE REPORT -------------- 
 --- failure: length > 1 in coercion to logical ---
 --- srcref --- 
: 
 --- package (from environment) --- 
package:stats
 --- call from context --- 
.rs.isSourceCall(call)
 --- call from argument --- 
fun == "source" || fun == "debugSource"
 --- R stacktrace ---
where 1: .rs.isSourceCall(call)
where 2: FUN(X[[i]], ...)
where 3: lapply(calls[1:(length(calls) - 2)], function(call) {
    if (isTRUE(attr(call[[1]], "hideFromDebugger"))) 
        return(NULL)
    isSourceCall <- FALSE
    if (.rs.isSourceCall(call)) {
        isSourceCall <- TRUE
        inSource <<- TRUE
    }
    srcref <- attr(call, "srcref")
    srcfile <- ""
    if (!is.null(srcref)) {
        fileattr <- attr(srcref, "srcfile")
        srcfile <- fileattr$filename
        if (!is.null(srcfile)) {
            if (inSource && !isSourceCall) 
                inSource <<- FALSE
            else foundUserCode <<- TRUE
        }
    }
    else srcref <- rep(0L, 8)
    lines <- deparse(call)
    if (length(lines) > 4) {
        lines <- lines[1:4]
        lines[4] <- paste(lines[4], "...")
    }
    c(list(func = .rs.scalar(paste(lines, collapse = "\n")), 
        file = .rs.scalar(srcfile)), .rs.lineDataList(srcref))
})
where 4: .rs.recordTraceback(TRUE, 5, .rs.enqueueError)
where 5: (function () 
{
    .rs.recordTraceback(TRUE, 5, .rs.enqueueError)
})()
where 6: execCallbacks(timeoutSecs, all, loop$id)
where 7: force(expr)
where 8: with_loop(loop, invisible(execCallbacks(timeoutSecs, all, loop$id)))
where 9: run_now(timeoutMs/1000, all = FALSE)
where 10 at /Users/winston/Dropbox/Projects/shiny/R/server.R#621: service(timeout)
where 11 at /Users/winston/Dropbox/Projects/shiny/R/server.R#989: serviceApp()
where 12 at /Users/winston/Dropbox/Projects/shiny/R/server.R#989: ..stacktracefloor..(serviceApp())
where 13 at /Users/winston/Dropbox/Projects/shiny/R/conditions.R#185: withCallingHandlers(expr, error = doCaptureStack)
where 14: domain$wrapSync(expr)
where 15 at /Users/winston/Dropbox/Projects/shiny/R/conditions.R#125: promises::with_promise_domain(createStackTracePromiseDomain(), 
    expr)
where 16 at /Users/winston/Dropbox/Projects/shiny/R/server.R#986: captureStackTraces({
    while (!.globals$stopped) {
        ..stacktracefloor..(serviceApp())
    }
})
where 17 at /Users/winston/Dropbox/Projects/shiny/R/server.R#986: ..stacktraceoff..(captureStackTraces({
    while (!.globals$stopped) {
        ..stacktracefloor..(serviceApp())
    }
}))
where 18: runApp(x)
where 19 at /Users/winston/Dropbox/Projects/shiny/R/app.R#520: do.call("runApp", args)
where 20: print.shiny.appobj(x)
where 21: (function (x, ...) 
UseMethod("print"))(x)

 --- value of length: 2 type: logical ---
[1] FALSE FALSE
 --- function from context --- 
function (call) 
{
    fun <- deparse(call[[1]])
    return(fun == "source" || fun == "debugSource")
}
<environment: 0x7fb5feb1a158>
 --- function search by body ---
 ----------- END OF FAILURE REPORT -------------- 
Error during wrapup: 'length(x) = 2 > 1' in coercion to 'logical(1)'

 ----------- FAILURE REPORT -------------- 
 --- failure: length > 1 in coercion to logical ---
 --- srcref --- 
: 
 --- package (from environment) --- 
package:stats
 --- call from context --- 
.rs.isSourceCall(call)
 --- call from argument --- 
fun == "source" || fun == "debugSource"
 --- R stacktrace ---
where 1: .rs.isSourceCall(call)
where 2: FUN(X[[i]], ...)
where 3: lapply(calls[1:(length(calls) - 2)], function(call) {
    if (isTRUE(attr(call[[1]], "hideFromDebugger"))) 
        return(NULL)
    isSourceCall <- FALSE
    if (.rs.isSourceCall(call)) {
        isSourceCall <- TRUE
        inSource <<- TRUE
    }
    srcref <- attr(call, "srcref")
    srcfile <- ""
    if (!is.null(srcref)) {
        fileattr <- attr(srcref, "srcfile")
        srcfile <- fileattr$filename
        if (!is.null(srcfile)) {
            if (inSource && !isSourceCall) 
                inSource <<- FALSE
            else foundUserCode <<- TRUE
        }
    }
    else srcref <- rep(0L, 8)
    lines <- deparse(call)
    if (length(lines) > 4) {
        lines <- lines[1:4]
        lines[4] <- paste(lines[4], "...")
    }
    c(list(func = .rs.scalar(paste(lines, collapse = "\n")), 
        file = .rs.scalar(srcfile)), .rs.lineDataList(srcref))
})
where 4: .rs.recordTraceback(TRUE, 5, .rs.enqueueError)
where 5: (function () 
{
    .rs.recordTraceback(TRUE, 5, .rs.enqueueError)
})()
where 6: execCallbacks(timeoutSecs, all, loop$id)
where 7: force(expr)
where 8: with_loop(loop, invisible(execCallbacks(timeoutSecs, all, loop$id)))
where 9: run_now(timeoutMs/1000, all = FALSE)
where 10 at /Users/winston/Dropbox/Projects/shiny/R/server.R#621: service(timeout)
where 11 at /Users/winston/Dropbox/Projects/shiny/R/server.R#989: serviceApp()
where 12 at /Users/winston/Dropbox/Projects/shiny/R/server.R#989: ..stacktracefloor..(serviceApp())
where 13 at /Users/winston/Dropbox/Projects/shiny/R/conditions.R#185: withCallingHandlers(expr, error = doCaptureStack)
where 14: domain$wrapSync(expr)
where 15 at /Users/winston/Dropbox/Projects/shiny/R/conditions.R#125: promises::with_promise_domain(createStackTracePromiseDomain(), 
    expr)
where 16 at /Users/winston/Dropbox/Projects/shiny/R/server.R#986: captureStackTraces({
    while (!.globals$stopped) {
        ..stacktracefloor..(serviceApp())
    }
})
where 17 at /Users/winston/Dropbox/Projects/shiny/R/server.R#986: ..stacktraceoff..(captureStackTraces({
    while (!.globals$stopped) {
        ..stacktracefloor..(serviceApp())
    }
}))
where 18: runApp(x)
where 19 at /Users/winston/Dropbox/Projects/shiny/R/app.R#520: do.call("runApp", args)
where 20: print.shiny.appobj(x)
where 21: (function (x, ...) 
UseMethod("print"))(x)

 --- value of length: 2 type: logical ---
[1] FALSE FALSE
 --- function from context --- 
function (call) 
{
    fun <- deparse(call[[1]])
    return(fun == "source" || fun == "debugSource")
}
<environment: 0x7fb5feb1a158>
 --- function search by body ---
 ----------- END OF FAILURE REPORT -------------- 
Error during wrapup: 'length(x) = 2 > 1' in coercion to 'logical(1)'
```

This is the content of `.rs.isSourceCall`:

```R
function (call) 
{
    fun <- deparse(call[[1]])
    return(fun == "source" || fun == "debugSource")
}
```

After running `debug(.rs.isSourceCall)` and inspecting the value of `fun`, it appears to be a two-element vector, which is being compared to a single-element vector:

```
debugging in: .rs.isSourceCall(call)
debug: {
    fun <- deparse(call[[1]])
    return(fun == "source" || fun == "debugSource")
}
Browse[2]> n
debug: fun <- deparse(call[[1]])
Browse[2]> n
debug: return(fun == "source" || fun == "debugSource")
Browse[2]> fun
[1] "function (x, ...) "   "UseMethod(\"print\")"
```

**Comment by schloerke** [comment] 2020-03-12 21:31
I was able to reproduce the bug in RStudio IDE v1.2.5001.  


I am not able to reproduce the bug in RStudio IDE v1.2.5033.  This is the latest release of desktop (12/17/2019).

1.2.5033 release notes: https://github.com/rstudio/rstudio/blame/1814bf5205a4d12709586daf9f17e8acda4b20ff/NEWS-1.2-patch.md#L8

> * Eliminate warnings when using `_R_CHECK_LENGTH_1_CONDITION_` ([#5268](https://github.com/rstudio/rstudio/issues/5268), [#5363](https://github.com/rstudio/rstudio/issues/5363))

------------------------

Closing.

**Closed by schloerke** 2020-03-12 21:31 UTC

**Comment by mgirlich** [comment] 2020-03-13 07:52
wow, nice finding! Thanks for investigating.

**Comment by wch** [comment] 2020-03-13 17:44
Looks like this has been fixed by https://github.com/rstudio/rstudio/pull/6466.
