### ISSUE TITLE
Date-time or at least time input needed

### ISSUE THREAD

**Issue by SamoPP** [rstudio/shiny#784] opened 2015-03-28 11:10 UTC
A date-time input or just a time input is really needed in shiny. I have searched all over but can not find one working.

Would it be possible to support this one (or similar): http://eonasdan.github.io/bootstrap-datetimepicker/ ? Pretty please... :)

**Comment by wch** [comment] 2015-06-01 23:17
This is related to #290.

**Comment by alandipert** [comment] 2019-04-26 15:21
Closing because duplicate of #897

**Closed by alandipert** 2019-04-26 15:21 UTC
