### ISSUE TITLE
Error with addResourcePath and font-awsome

### ISSUE THREAD

**Issue by jjesusfilho** [rstudio/shiny#2407] opened 2019-04-28 15:50 UTC
After updating shiny, I can no longer output a highcharter graphic with the motion plugin. I get the following error:

`Warning: Error in value[[3L]]: Couldn't normalize path in `addResourcePath`, with arguments: `prefix` = 'font-awesome-0.0.0'; `directoryPath` = ''`. 

 If I interactively run the same `hc` object in RStudio, it normally displays the graphic.

**Comment by alandipert** [comment] 2019-04-29 03:35
Thanks for the report. I was able to reproduce with the following app with Shiny 1.3.2 (R 3.5.2, RStudio Server Pro), adapted from the [highcharter motion example](http://jkunst.com/highcharter/plugins.html#motion):

```R
library(shiny)
library(highcharter)
library("idbr")
library("purrr")
library("dplyr")

idb_api_key("35f116582d5a89d11a47c7ffbfc2ba309133f09d")
yrs <-  seq(1980, 2030, by = 5)

df <- map_df(c("male", "female"), function(sex){
  mutate(idb1("US", yrs, sex = sex), sex_label = sex)
})

names(df) <- tolower(names(df))

df <- df %>%
  mutate(population = pop*ifelse(sex_label == "male", -1, 1))

series <- df %>%
  group_by(sex_label, age) %>%
  do(data = list(sequence = .$population)) %>%
  ungroup() %>%
  group_by(sex_label) %>%
  do(data = .$data) %>%
  mutate(name = sex_label) %>%
  list_parse()

maxpop <- max(abs(df$population))

xaxis <- list(categories = sort(unique(df$age)),
              reversed = FALSE, tickInterval = 5,
              labels = list(step = 5))

hc <- highchart() %>%
  hc_chart(type = "bar") %>%
  hc_motion(enabled = TRUE, labels = yrs, series = c(0,1), autoplay = TRUE, updateInterval = 1) %>%
  hc_add_series_list(series) %>%
  hc_plotOptions(
    series = list(stacking = "normal"),
    bar = list(groupPadding = 0, pointPadding =  0, borderWidth = 0)
  ) %>%
  hc_tooltip(shared = TRUE) %>%
  hc_yAxis(
    labels = list(
      formatter = JS("function(){ return Math.abs(this.value) / 1000000 + 'M'; }")
    ),
    tickInterval = 0.5e6,
    min = -maxpop,
    max = maxpop) %>%
  hc_xAxis(
    xaxis,
    rlist::list.merge(xaxis, list(opposite = TRUE, linkedTo = 0))
  ) %>%
  hc_tooltip(shared = FALSE,
             formatter = JS("function () { return '<b>' + this.series.name + ', age ' + this.point.category + '</b><br/>' + 'Population: ' + Highcharts.numberFormat(Math.abs(this.point.y), 0);}")
  )

library(shiny)

ui <- fluidPage(
  highchartOutput("hc1")
)

server <- function(input, output, session) {
  output$hc1 <- renderHighchart(hc)
}

shinyApp(ui, server)
```

@jjesusfilho Do you happen to remember the last version of Shiny you were using where this worked for you?

**Comment by cpsievert** [comment] 2019-04-29 15:44
@jjesusfilho you can get this example working by doing `remotes::install_github("jbkunst/highcharter")`

@jbkunst are you aware of this issue? Looks like it was introduced when we upgraded to FontAwesome 5.3.1 in 3cea5fb2d04632d6339e033fd517dca1f600f0dc. It that commit renames the `www/shared/font-awesome` to `www/shared/fontawesome`, but your `highcharter:::hc_add_dependency_fa()` references shiny's `www/shared/font-awesome` path.

It looks like you might be removing this function, though https://github.com/jbkunst/highcharter/commit/b225beb8ab75d06b350ab3a12ff9ca8266552a5c?

**Comment by cpsievert** [comment] 2019-04-29 15:45
Closing since there isn't anything shiny can do to help the situation...

**Closed by cpsievert** 2019-04-29 15:45 UTC
Labels: Difficulty: Advanced, Priority: Medium, Type: Bug :bug:

**Comment by jjesusfilho** [comment] 2019-04-30 08:34
> Thanks for the report.
> 
> I was able to reproduce with Shiny 1.3.2 and Shiny 1.2.0 and @cpsievert was able to reproduce with 1.1.0, so this must be a fairly old problem.
> 
> I used the following app, adapted from the [highcharter motion example](http://jkunst.com/highcharter/plugins.html#motion):
> 
> ```r
> library(shiny)
> library(highcharter)
> library("idbr")
> library("purrr")
> library("dplyr")
> 
> idb_api_key("35f116582d5a89d11a47c7ffbfc2ba309133f09d")
> yrs <-  seq(1980, 2030, by = 5)
> 
> df <- map_df(c("male", "female"), function(sex){
>   mutate(idb1("US", yrs, sex = sex), sex_label = sex)
> })
> 
> names(df) <- tolower(names(df))
> 
> df <- df %>%
>   mutate(population = pop*ifelse(sex_label == "male", -1, 1))
> 
> series <- df %>%
>   group_by(sex_label, age) %>%
>   do(data = list(sequence = .$population)) %>%
>   ungroup() %>%
>   group_by(sex_label) %>%
>   do(data = .$data) %>%
>   mutate(name = sex_label) %>%
>   list_parse()
> 
> maxpop <- max(abs(df$population))
> 
> xaxis <- list(categories = sort(unique(df$age)),
>               reversed = FALSE, tickInterval = 5,
>               labels = list(step = 5))
> 
> hc <- highchart() %>%
>   hc_chart(type = "bar") %>%
>   hc_motion(enabled = TRUE, labels = yrs, series = c(0,1), autoplay = TRUE, updateInterval = 1) %>%
>   hc_add_series_list(series) %>%
>   hc_plotOptions(
>     series = list(stacking = "normal"),
>     bar = list(groupPadding = 0, pointPadding =  0, borderWidth = 0)
>   ) %>%
>   hc_tooltip(shared = TRUE) %>%
>   hc_yAxis(
>     labels = list(
>       formatter = JS("function(){ return Math.abs(this.value) / 1000000 + 'M'; }")
>     ),
>     tickInterval = 0.5e6,
>     min = -maxpop,
>     max = maxpop) %>%
>   hc_xAxis(
>     xaxis,
>     rlist::list.merge(xaxis, list(opposite = TRUE, linkedTo = 0))
>   ) %>%
>   hc_tooltip(shared = FALSE,
>              formatter = JS("function () { return '<b>' + this.series.name + ', age ' + this.point.category + '</b><br/>' + 'Population: ' + Highcharts.numberFormat(Math.abs(this.point.y), 0);}")
>   )
> 
> library(shiny)
> 
> ui <- fluidPage(
>   highchartOutput("hc1")
> )
> 
> server <- function(input, output, session) {
>   output$hc1 <- renderHighchart(hc)
> }
> 
> shinyApp(ui, server)
> ```
> 
> Stack trace in R console:
> 
> ```
> Warning: Error in value[[3L]]: Couldn't normalize path in `addResourcePath`, with arguments: `prefix` = 'font-awesome-0.0.0'; `directoryPath` = ''
>   106: stop
>   105: value[[3L]]
>   104: tryCatchOne
>   103: tryCatchList
>   102: tryCatch
>   101: addResourcePath
>   100: FUN
>    99: lapply
>    98: renderWidget
>    97: transform
>    96: func
>    94: f
>    93: Reduce
>    84: do
>    83: hybrid_chain
>    82: origRenderFunc
>    81: output$hc1
>     1: runApp
> ```
> 
> @jjesusfilho Do you happen to remember the last version of Shiny you were using where this worked for you?

I have shiny 1.20 installed in another computer and it is still working there.

Anyway thank you very much for the  thorough response. This issue was also raised by someone else in the highcharter package but is still waiting for @jbkunst reply.

**Comment by abenedetti** [comment] 2020-05-02 03:26
@jjesusfilho, got the same error on an animated choropleth map as well. Tried to downgrade shiny to 1.2.0 and highcharter to 0.5.0 but I still have the issue. Can you share your packages version on the machine you're still able to make `hr_motion` work? Thanks.
