### ISSUE TITLE
ggtern not working under Shiny 12.1

### ISSUE THREAD

**Issue by DataKritter** [rstudio/shiny#915] opened 2015-07-31 21:11 UTC
I use ggtern (an extension of ggplot2) to make ternary graphs.  They used to work fine in Shiny (either RStudio or Shiny.io).  However, recently, when I run them in Shiny, they come out differently and with multiple problems.

For example, in the first image below (from R), the axes are labelled, and there are gridlines within the triangle.

In the second image (exact same code in Shiny), only one axis is labelled, the label for another axis has moved to the left of the legend, the arrows are unlabled, and there are no gridlines.

(The code for this graph is available at: http://www.ggtern.com/2013/12/12/feldspar/).

Some things that seem broken in ggtern under Shiny:
themes
stat_density2d
axis labeling

By recreating my workspace from May, I've isolated the problem to an update that happened between shiny v 11.1 and 12.1.  As long as I keep shiny at v11.1, everything works as expected.
Thank you,
CB

Fig 1: Feldspar data in R

![image](https://cloud.githubusercontent.com/assets/6520841/9017824/1923faf8-37a7-11e5-929f-40f79273932d.png)

Fig 2. Feldspar Data in Shiny
![image](https://cloud.githubusercontent.com/assets/6520841/9017822/14bd3a88-37a7-11e5-8073-3aca36daf5a9.png)

**Comment by cainesap** [comment] 2016-01-16 20:58
Thank you for creating this issue, and for sharing the solution. I've re-installed Shiny 0.11.1 and hope this will be fixed soon, as I'd like to go back to 'latest Shiny'

**Comment by bruparel** [comment] 2016-07-28 19:28
I am in the same boat.  Is there a resolution in sight for this issue?  I am using the 'old' datatables with the ternary graphs and would like to use the successor package (DT).  However, I get the error that shiny version >= 0.12.0 is required for this.

**Comment by wch** [comment] 2016-07-29 19:12
Could any of you provide a minimal reproducible example that exhibits the problem? That will help us debug it.

**Comment by bruparel** [comment] 2016-07-29 19:37
Sure no problem.  Attached herewith is my app.R file and the Excel file that it uses.  You will have to adjust the Excel file's path my script to make it run.  Also I am using XLConnect package which requires that you have Java installed on your machine.
[example.zip](https://github.com/rstudio/shiny/files/391223/example.zip)

**Comment by wch** [comment] 2016-07-29 20:23
That example doesn't work for me because it references a directory I don't have.

Here's a minimal example:

```R
library(shiny)
library(ggtern)

ui <- fluidPage(
  plotOutput("plot")
)
server <- function(input, output) {
  output$plot <- renderPlot({
    ggtern() + geom_point(data=data.frame(x=1,y=0,z=0),aes(x,y,z))
  })
}
shinyApp(ui = ui, server = server)
```

This appears to be related to some strange things that ggtern does to redefine `print.ggplot` and `build_gtable`:
https://bitbucket.org/nicholasehamilton/ggtern/src/d1da3eb4dd2e4f4900b3a86ba84c51a0ce90fe4c/R/plot.R?at=master&fileviewer=file-view-default#plot.R-86:110
https://bitbucket.org/nicholasehamilton/ggtern/src/d1da3eb4dd2e4f4900b3a86ba84c51a0ce90fe4c/R/gg-internal.R?at=master&fileviewer=file-view-default

**Comment by wch** [comment] 2016-07-29 20:27
It also has its own version of `ggplot_build`: https://bitbucket.org/nicholasehamilton/ggtern/src/d1da3eb4dd2e4f4900b3a86ba84c51a0ce90fe4c/R/plot-build.R?at=master&fileviewer=file-view-default

**Comment by bruparel** [comment] 2016-07-29 20:38
Thanks Winston.  It looks like I will have to bring this the ggtern author's attention.  It is a shame because it is a great package otherwise.  I really like Shiny too and would love to use the latest version and push it as hard as I can.  Is there a way to run a specific version of Shiny in R for a specific application such as this for drawing the ternary diagram, and use its latest version in other applications that are not using the ternary diagram?
I am a Rails developer and it is quite easy to run and deploy with different versions of Ruby and Rails using the 'bundler.'  It this is possible, then we would love to use the hosting services provided by RStudio.

**Comment by wch** [comment] 2016-07-29 20:41
If you deploy to shinyapps.io, it automatically uses the same version of R and all packages. If you're using Shiny Server, you can use packrat with your app to maintain specific package versions, including Shiny.

**Comment by wch** [comment] 2016-07-29 20:54
At the moment I'm not sure what the best solution is for ggtern. The root of the problem is that it is overriding `print.ggplot`, and Shiny does as well, when the expression in `renderPlot()` returns a ggplot object. Shiny's overridden version of `print.ggplot` behaves like ggplot2's version of that function (with a minor change), but ggtern's overridden version of the function makes some other changes that Shiny does not duplicate.

I just realized, however, that you could work around the issue by calling `print()` on the plot object, within the `renderPlot()` call:

```R
library(shiny)
library(ggtern)

ui <- fluidPage(
  plotOutput("plot")
)

server <- function(input, output) {
  output$plot <- renderPlot({
    p <- ggtern() + geom_point(data=data.frame(x=1,y=0,z=0),aes(x,y,z))
    print(p)
    NULL
  })
}

shinyApp(ui = ui, server = server)
```

The `NULL` might not be absolutely necessary, but it's a good idea to keep it there to make sure that Shiny doesn't try call `print()` on the returned object.

**Comment by bruparel** [comment] 2016-07-29 21:35
On a side note Winston, are you planning on releasing the second edition of you R Graphics Cookbook sometime soon?  If yes, then I will wait for it to come out.

**Comment by bruparel** [comment] 2016-07-30 01:58
Winston.  I just did what you suggested above and it worked great!!
Thank you man.  But you did not answer my question above.  Are you releasing the second edition of you book soon?  If not then is it still advisable to buy the old edition?  I have not seen too many books rated as high as your book.  I am immensely interested in R Graphics especially in Shiny environment.  Please advise.
Thanks again.

**Comment by wch** [comment] 2016-08-12 13:48
@bruparel I'm hoping to get a second edition out at some point, but it probably won't be for quite a while -- probably at least a year.

**Comment by cricketbird** [comment] 2016-09-16 00:25
Glad to see a workaround - just tried using `print()` as Winston suggested, and it fixes everything except the gridlines, which are still gone.  I can live without those, though.  Thanks all :)

PS - @wch Your Graphics book is awesome.  I use it daily.  Worth its weight in gold!!!

**Comment by alandipert** [comment] 2019-04-26 20:47
Hello everyone, it seems like this issue was traced to `ggtern` and a suitable workaround has been suggested, so I'm closing it.

Please don't hesitate to comment further or create a new issue if you feel this should not have been closed.

**Closed by alandipert** 2019-04-26 20:47 UTC
