### ISSUE TITLE
update* won't allow HTML tags in labels

### ISSUE THREAD

**Issue by carlganz** [rstudio/shiny#1451] opened 2016-11-01 18:51 UTC
Apropos of this SO question: http://stackoverflow.com/questions/40341804/r-shiny-updateselectizeinput-custom-html-tags-for-labels

It appears one cannot use HTML tags when updating labels.

Here is a reproducible example:

```{R}
library(shiny)

ui =fluidPage(
  selectizeInput('Z',choices=1:3,
                 label=h6("Hello world")),
  actionButton("btn",h6("Press me"))
)

server = function(input, output, session) {
  
  observeEvent(input$btn,{
    updateSelectizeInput(session,"Z",
                         label = h6("Something different"))
    
    updateActionButton(session,"btn",label=h6("New words"))
  })
  
}
runApp(list(ui = ui, server = server))
```

When `h6` is used in the labels for the selectize and button on startup it is fine. When you press the button the labels are updated, but the output of the new labels is wrong (it says "[object Object]"). Inside the updates, wrapping `h6` with `as.character` gives the literal HTML code, and wrapping that in `HTML` or `I` doesn't fix anything. This seems like a bug and not a design decision.

Thanks

**Comment by bborgesr** [comment] 2016-11-17 20:59
duplicate of #1140

**Closed** 2016-11-17 21:00 UTC
