### ISSUE TITLE
Incorporate spin.js Widget

### ISSUE THREAD

**Issue by DarioS** [rstudio/shiny#1295] opened 2016-08-12 01:00 UTC
Shiny already has a progress indicator (`incProgress`) for tasks which have an easy way to break them into sub-tasks and increment the progress bar. What about incorporating [spin.js](http://spin.js.org/) to complement the visualisation of long-running tasks which are, for example, functions in CRAN packages and can't be easily modified to increment a progress bar ? [spin.js](http://spin.js.org/) seems like a stable software which rarely gets new releases and would be an appreciated addition to Shiny.

**Comment by daattali** [comment] 2016-08-15 08:27
FWIW I often do this functionality with shinyjs by just calling show+hide on a spinner image I have.  I feel like this is perhaps a feature that shinyjs could support , you can open an issue there if you'd like

**Comment by DarioS** [comment] 2016-08-16 02:00
It could mean less maintenance for the developers of shiny, which have a backlog of issues to address, but it would also be less streamlined if a progress indicator with increments was in one R package an another without increments was found in a different package. I implemented it in my project by copying the spin.js into the project directory and switching visibility by altering the `display` value with `session[["sendCustomMessage"]]`.

**Comment by wch** [comment] 2016-09-20 16:08
I think a good alternative is to add an option to the progress bar so that it's grows asymptotically, but where the client browser sends the events at some interval to grow the progress bar. This would work when the R process on the server is blocking due to a long-running computation.

**Comment by DarioS** [comment] 2016-09-23 07:00
Yes, that's a good alternative to include in the framework. In the meantime, I incorporated the spinner into my Shiny application by downloading spin.js from the internet, importing it with `includeScript`, and using `session[["sendCustomMessage"]]` to show and hide it in response to action button clicks and data processing finishing. But, the asymptotic progress bar would be an easier alternative for novice users.

**Comment by bborgesr** [comment] 2016-09-23 12:56
Sounds good, @DarioS! We'll look into implementing the asymptotic progress bar sometime in the nearish future.

**Comment by bborgesr** [comment] 2017-05-05 17:21
For stumblers on this issue interested in incorporating a spinner: there's now a new package by @andrewsali that makes this pretty easy: [andrewsali/shinycssloaders](https://github.com/andrewsali/shinycssloaders)

**Comment by alandipert** [comment] 2019-04-29 19:07
Closing as duplicate of #793

**Closed by alandipert** 2019-04-29 19:07 UTC
Labels: Difficulty: Intermediate, Effort: Medium
