### ISSUE TITLE
renderPlot does not work with {ggtree}

### ISSUE THREAD

**Issue by lz100** [rstudio/shiny#3406] opened 2021-05-26 01:41 UTC
Hi Shiny Team,

Browser Version: Chrome 90.0

Output of `sessionInfo()`:

```
R version 4.1.0 (2021-05-18)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.2 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] treeio_1.16.1 ggtree_3.0.0  shiny_1.6.0  

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6          BiocManager_1.30.15 compiler_4.1.0     
 [4] pillar_1.6.1        later_1.2.0         digest_0.6.27      
 [7] aplot_0.0.6         jsonlite_1.7.2      tidytree_0.3.4     
[10] lifecycle_1.0.0     tibble_3.1.2        gtable_0.3.0       
[13] nlme_3.1-152        lattice_0.20-44     pkgconfig_2.0.3    
[16] rlang_0.4.11        DBI_1.1.1           rvcheck_0.1.8      
[19] patchwork_1.1.1     parallel_4.1.0      fastmap_1.1.0      
[22] dplyr_1.0.6         generics_0.1.0      vctrs_0.3.8        
[25] grid_4.1.0          tidyselect_1.1.1    glue_1.4.2         
[28] R6_2.5.0            fansi_0.4.2         tidyr_1.1.3        
[31] ggplot2_3.3.3       purrr_0.3.4         magrittr_2.0.1     
[34] scales_1.1.1        promises_1.2.0.1    ellipsis_0.3.2     
[37] htmltools_0.5.1.1   assertthat_0.2.1    mime_0.10          
[40] ape_5.5             xtable_1.8-4        colorspace_2.0-1   
[43] httpuv_1.6.1        utf8_1.2.1          lazyeval_0.2.2     
[46] munsell_0.5.0       crayon_1.4.1   
```

### Example application *or* steps to reproduce the problem

I run the following code with no problem outside shiny 

```r
library(ggtree)
library(treeio)
treetext = "(((ADH2:0.1[&&NHX:S=human], ADH1:0.11[&&NHX:S=human]):
0.05 [&&NHX:S=primates:D=Y:B=100],ADHY:
0.1[&&NHX:S=nematode],ADHX:0.12 [&&NHX:S=insect]):
0.1[&&NHX:S=metazoa:D=N],(ADH4:0.09[&&NHX:S=yeast],
ADH3:0.13[&&NHX:S=yeast], ADH2:0.12[&&NHX:S=yeast],
ADH1:0.11[&&NHX:S=yeast]):0.1[&&NHX:S=Fungi])[&&NHX:D=N];"
tree <- read.nhx(textConnection(treetext))
ggtree(tree) + geom_tiplab()
```

But when I add the plot inside Shiny, I got an error

```r
library(shiny)
ui <- fluidPage(plotOutput("p"))
server <- function(input, output, session) {output$p <- renderPlot({ggtree(tree) + geom_tiplab()})}
shinyApp(ui, server)
```

```
Warning: Error in match.call: ... used in a situation where it does not exist
  [No stack trace available]
```

In principle, the output from {ggtree} is just ggplot2 objects, not sure why this will not work in Shiny. 

```r
> class(ggtree(tree) + geom_tiplab())
[1] "ggtree" "gg"     "ggplot"
```
Could you help me out?

**Comment by cpsievert** [comment] 2021-05-26 14:18
Running your example outside of shiny, I see:

```r
> ggtree(tree) + geom_tiplab()
Error in DataMask$new(.data, caller_env) : 
  argument "caller_env" is missing, with no default
```

**Comment by lz100** [comment] 2021-05-26 19:15
You may have a different package version. I managed to reproduce the error on a Rstudio cloud instance: https://rstudio.cloud/project/2588113. 

The R version and ggtree version are different but the error can be reproduced.

**Comment by tgstoecker** [comment] 2021-05-26 19:19
Facing the same problem.
In the {ggtree} issues [#395](https://github.com/YuLab-SMU/ggtree/issues/395), [#399](https://github.com/YuLab-SMU/ggtree/issues/399) and [#400](https://github.com/YuLab-SMU/ggtree/issues/400) 
```
Error in DataMask$new(.data, caller_env) : 
  argument "caller_env" is missing, with no default
```
 was discussed. It seems that is caused by a recent update in dplyr (1.0.5 -> 1.0.6).  

Re-installing the latest versions ggtree and tidytree,
```
remotes::install_github("YuLab-SMU/ggtree")
remotes::install_github("YuLab-SMU/tidytree")
```
as well as downgrading back to dplyr 1.0.5 fixes the issue on the ggtree side and plots work as expected again for me.

Trying to plot in shiny however, still leads to the `Error in match.call: ... used in a situation where it does not exist` error.
Specifically when `+ geom_tiplab()` is used. Without that layer I get no error.

**Comment by cpsievert** [comment] 2021-05-26 20:48
This is almost certainly due to [this recent change to ggtree](https://github.com/YuLab-SMU/ggtree/commit/949ac5cdc6bd8839f2f501736a739f4b121cdc6e#diff-fb3ebda9a69a20dfea7b9cf4f03cab39673bac903ff8546560ba358dd21f648eR25) by @xiangpin. It looks like the intention of using the `match.call()` here is to detect when `geom_tiplab()` is being called via `geom_nodelab()`, but that's not a fool-proof way to do it (it'd be better to have `geom_nodelab()` call an internal version of `geom_tiplab()` that sets `nodelab = TRUE` instead of trying to magically detect who is calling `geom_tiplab()`). 

Closing since this issue needs to be addressed in ggtree, please file issue over there if there isn't one already

**Closed by cpsievert** 2021-05-26 20:48 UTC
