### ISSUE TITLE
dataTableOutput rendering error in shiny 1.4.0

### ISSUE THREAD

**Issue by cataclysmic** [rstudio/shiny#2700] opened 2019-11-11 13:33 UTC
First, restart R. *Done multiple times*
To install latest shiny from CRAN:  *Installed shiny 1.4.0*

### System details
Ubuntu 18.04 64bit
Browser Version: 68.2.0esr 32bit

Output of `sessionInfo()`:

```
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.2 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=de_DE.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=de_DE.UTF-8        LC_COLLATE=de_DE.UTF-8
 [5] LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=de_DE.UTF-8
 [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] shinycssloaders_0.2.0 shinyWidgets_0.4.9    shiny_1.4.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.2       digest_0.6.22    later_1.0.0      mime_0.7
 [5] R6_2.4.0         xtable_1.8-4     jsonlite_1.6     magrittr_1.5
 [9] scales_1.0.0     rlang_0.4.1      promises_1.1.0   munsell_0.5.0
[13] httpuv_1.5.2     fastmap_1.0.1    compiler_3.6.1   colorspace_1.4-1
[17] htmltools_0.4.0
```

### Example application *or* steps to reproduce the problem

Reproducible example.
```R
library(shiny)


ui <- fluidPage(

    
           dataTableOutput("distPlot")
        
)


server <- function(input, output) {

    output$distPlot <- renderDataTable({
        iris
    })
}


shinyApp(ui = ui, server = server)
```
*Description*

After upgrade to shiny version 1.4.0 dataTableOutput fails to render with error:
```
DataTables warning: table id=DataTables_Table_0 - Requested unknown parameter 'X' for row Y. For more information about this error, please see http://datatables.net/tn/4
```
rendeTable works, renderDataTable fails.

**Comment by ismirsehregal** [comment] 2019-11-13 08:14
For a workaround you can use  `DT::dataTableOutput()` and `DT::renderDataTable`.

**Comment by cataclysmic** [comment] 2019-11-13 09:22
> 
> 
> For a workaround you can use `DT::dataTableOutput()` and `DT::renderDataTable`.

Thank you.
Yes, we are currently using that workaround.

**Comment by mikmart** [comment] 2019-11-25 10:56
This seems to have been caused by htmltools 0.4.0. I tried installing older versions of shiny, up to 1.2.0, and the issue persisted; but when I downgraded both shiny and htmltools to their previous versions (1.3.2 and 0.3.6), everything worked fine again.

**Comment by cataclysmic** [comment] 2019-11-26 10:12
> 
> 
> This seems to have been caused by htmltools 0.4.0. I tried installing older versions of shiny, up to 1.2.0, and the issue persisted; but when I downgraded both shiny and htmltools to their previous versions (1.3.2 and 0.3.6), everything worked fine again.

Thank you for the feedback. We use `DT:dataTableOutput` aus workaround and hope for the next iteration.

**Comment by wch** [comment] 2019-11-26 16:12
FWIW, this is a duplicate of #2653 and has been fixed in the development version of Shiny. You can install it with:

```R
remotes::install_github("rstudio/shiny")

# Or, with devtools:
devtools::install_github("rstudio/shiny")
```

**Closed by wch** 2019-11-26 16:12 UTC
