### ISSUE TITLE
Shiny apps not rendering after updated to v1.3.0

### ISSUE THREAD

**Issue by andresrcs** [rstudio/shiny#2372] opened 2019-04-08 19:28 UTC
All my apps have stopped rendering after I updated to shiny v 1.3.0 and I get not error messages in the logs, for example this app under v 1.3.0 renders like this

![image](https://user-images.githubusercontent.com/14981085/55750759-a28f0c00-5a09-11e9-86ed-6c1980426e1d.png)

![image](https://user-images.githubusercontent.com/14981085/55751520-7c6a6b80-5a0b-11e9-984a-fcf17b8d1842.png)

And after downgrading to v1.2.0 it renders normally, I get the same behaviour with all my apps.

![image](https://user-images.githubusercontent.com/14981085/55750953-18937300-5a0a-11e9-84f8-af403d9a149a.png)

My shiny-server version is 1.5.9.923 open source, running under ubuntu server 18.04.2 LTS

**Comment by wch** [comment] 2019-04-08 20:01
Can you put `sessioninfo::session_info()` in one of your apps and render the output in a `verbatimTextOutput`, then post the output here? (You'll also need to install the sessioninfo package.)

Also, if you could provide a minimal reproducible example, that would help.

**Comment by andresrcs** [comment] 2019-04-08 21:17
Ok, here is the reprex with `session_info()`
app.R
```
library(shiny)

ui <- fluidPage(

    titlePanel("Reprex"),

    sidebarLayout(
        sidebarPanel(
        ),

        mainPanel(
            verbatimTextOutput("info")
        )
    )
)

server <- function(input, output) {

    output$info <- renderPrint({
        print(sessioninfo::session_info())
    })
}

shinyApp(ui = ui, server = server)
```
With Shiny v 1.3.0 renders nothing
![image](https://user-images.githubusercontent.com/14981085/55757166-f2c19a80-5a18-11e9-9776-23f6b9d16710.png)

With Shiny v 1.2.0 shows this
![image](https://user-images.githubusercontent.com/14981085/55757395-71b6d300-5a19-11e9-9f09-42da0d8ec2c9.png)

**Comment by jcheng5** [comment] 2019-04-08 21:19
@andresrcs What do you see in your browser's JavaScript console when it fails to load?

**Comment by wch** [comment] 2019-04-08 21:34
FWIW, it seems to work OK when I run the same app in Ubuntu 18.04.2, with R-devel (this is running from R directly, not in Shiny Server):

![image](https://user-images.githubusercontent.com/86978/55758238-c5c2b700-5a1b-11e9-8519-8fa4a4d765e2.png)

**Comment by andresrcs** [comment] 2019-04-08 21:39
BTW I get the same behaviour on a Debian Stretch (Raspbian Stretch) server, so I think this is not related to Ubuntu 18.

**Comment by andresrcs** [comment] 2019-04-08 22:01
> @andresrcs What do you see in your browser's JavaScript console when it fails to load?

This is what I see

![image](https://user-images.githubusercontent.com/14981085/55759356-bb55ec80-5a1e-11e9-980c-929ff49555a0.png)
![image](https://user-images.githubusercontent.com/14981085/55759377-cd378f80-5a1e-11e9-8155-8e996c204d5c.png)

**Comment by jcheng5** [comment] 2019-04-09 01:53
It almost looks like httpuv wasn't upgraded to 1.5.1...

**Comment by wch** [comment] 2019-04-09 17:49
@andresrcs Does your code call `addResourcePath()` anywhere? We think this issue might be related to that.

**Comment by wch** [comment] 2019-04-09 19:27
@andresrcs It seems likely that this is a problem with your proxy configuration. Please see https://support.rstudio.com/hc/en-us/articles/213733868-Running-Shiny-Server-with-a-Proxy

**Comment by wch** [comment] 2019-04-09 19:37
This post on Community is about the same issue: https://community.rstudio.com/t/failed-to-load-resource/28142

**Comment by wch** [comment] 2019-04-09 20:22
For future reference, the user on community gave an example of his broken configuration, and then the working one:

Not working:

```
    location /apps/ {
      proxy_pass http://127.0.0.1:3838/apps/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }
```

Working:

```
  map $http_upgrade $connection_upgrade {
      default upgrade;
      ''      close;
  }

[... stuff here ...]

    location /apps/ {
      proxy_pass http://127.0.0.1:3838/apps/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_read_timeout 20d;
      proxy_buffering off;
    }
```

**Comment by wch** [comment] 2019-04-09 21:11
We've merged a pull request in httpuv which makes it more lenient with proxies that are misconfigured this way. It can be installed with:

```
devtools::install_github('rstudio/httpuv')
```

**Closed by wch** 2019-04-09 21:11 UTC
Labels: Type: Regression

**Comment by andresrcs** [comment] 2019-04-09 23:34
@wch 
Thanks, this issue is definitely related to my nginx config, I just want to report an additional problem with the config. If I use `proxy_set_header Connection $connection_upgrade;` I get this error message and nginx won't start.
```
sudo service nginx restart
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
```
If I use this instead `proxy_set_header Connection "connection_upgrade";` it works.

I get this behaviour on Ubuntu 18.04.2 LTS - nginx 1.14.0-0ubuntu1.2 and Debian Stretch - nginx 1.10.3-1+deb9u2

**Comment by andresrcs** [comment] 2019-04-10 01:51
@wch 
I have a problem implementing the correct proxy config solution, if I use this line in nginx config file `proxy_set_header Connection $connection_upgrade;` I get this error message and nginx won't start.
```
sudo service nginx restart
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.

systemctl status nginx.service
● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2019-04-10 01:34:09 UTC; 15s ago
     Docs: man:nginx(8)
  Process: 3985 ExecStop=/sbin/start-stop-daemon --quiet --stop --retry QUIT/5 --pidfile /run/nginx.pid (code=exited, status
  Process: 3901 ExecReload=/usr/sbin/nginx -g daemon on; master_process on; -s reload (code=exited, status=0/SUCCESS)
  Process: 3876 ExecStart=/usr/sbin/nginx -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
  Process: 3986 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=1/FAILURE)
 Main PID: 3881 (code=exited, status=0/SUCCESS)

abr 10 01:34:09 ip-172-xx-xx-xx systemd[1]: nginx.service: Failed with result 'timeout'.
abr 10 01:34:09 ip-172-xx-xx-xx systemd[1]: Stopped A high performance web server and a reverse proxy server.
abr 10 01:34:09 ip-172-xx-xx-xx systemd[1]: Starting A high performance web server and a reverse proxy server...
abr 10 01:34:09 ip-172-xx-xx-xx nginx[3986]: nginx: [emerg] unknown "connection_upgrade" variable
abr 10 01:34:09 ip-172-xx-xx-xx nginx[3986]: nginx: configuration file /etc/nginx/nginx.conf test failed
abr 10 01:34:09 ip-172-xx-xx-xx systemd[1]: nginx.service: Control process exited, code=exited status=1
abr 10 01:34:09 ip-172-xx-xx-xx systemd[1]: nginx.service: Failed with result 'exit-code'.
abr 10 01:34:09 ip-172-xx-xx-xx systemd[1]: Failed to start A high performance web server and a reverse proxy server.
```
What confuses me the most is this line:
 `abr 10 01:34:09 ip-172-xx-xx-xx nginx[3986]: nginx: [emerg] unknown "connection_upgrade" variable`

If I use this instead `proxy_set_header Connection "connection_upgrade";` it works, even with the CRAN version of `httpuv` (1.5.1)

What could be the problem? I get this behaviour on Ubuntu 18.04.2 LTS - nginx 1.14.0-0ubuntu1.2 and Debian Stretch - nginx  1.10.3-1+deb9u2

**Comment by jcheng5** [comment] 2019-04-10 01:54
connection_upgrade is a variable that is declared using that "map $http_upgrade $connection_upgrade {...}" part. Make sure to include that map directive in your config.

**Comment by andresrcs** [comment] 2019-04-10 02:10
Thanks, I have missed that part, I'm still confused about why this works `proxy_set_header Connection "connection_upgrade";` with `httpuv` 1.5.1 and this doesn't `proxy_set_header Connection "upgrade"` but I suppose it doesn't matter.

**Comment by jcheng5** [comment] 2019-04-10 02:17
Yeah, it's a bit confusing. httpuv specifically detects and rejects `Connection: upgrade` when serving up static files like JS and CSS files. But you should still not use `Connection: connection_upgrade` because it will keep proxy-to-httpuv connections open longer than necessary by implicitly enabling HTTP keepalive. We really do want `Connection: close` for non-WebSocket requests.

**Comment by andresrcs** [comment] 2019-04-10 02:22
Thanks for the clarification, I have fixed the problem and everything is working fine now

**Comment by thiagoveloso** [comment] 2019-04-10 23:02
> For future reference, the user on community gave an example of his broken configuration, and then the working one:
> 
> Not working:
> 
> ```
>     location /apps/ {
>       proxy_pass http://127.0.0.1:3838/apps/;
>       proxy_http_version 1.1;
>       proxy_set_header Upgrade $http_upgrade;
>       proxy_set_header Connection "upgrade";
>     }
> ```
> Working:
> 
> ```
>   map $http_upgrade $connection_upgrade {
>       default upgrade;
>       ''      close;
>   }
> 
> [... stuff here ...]
> 
>     location /apps/ {
>       proxy_pass http://127.0.0.1:3838/apps/;
>       proxy_http_version 1.1;
>       proxy_set_header Upgrade $http_upgrade;
>       proxy_set_header Connection $connection_upgrade;
>       proxy_read_timeout 20d;
>       proxy_buffering off;
>     }
> ```

I also had issues with shiny v.1.3.0 not loading apps properly and I fixed them by adding the `map` block that you mention in your reply. Thanks a lot!

**Comment by duocang** [comment] 2023-07-04 11:34
Hi.

I am working  with Shiny and JS in Mac m1. 

I recently met a strange problem about "Failed to load resource: the server responded with a status of 404 (not Found)"
<img width="433" alt="image" src="https://github.com/rstudio/shiny/assets/14146871/8ae04d50-1f5a-4ce5-8ed4-5e6d1d90e2de">

It is strange because it only happens when I start the shiny app via `Rscript app.R`. RStudio can run the shiny app properly.

I send data to JS file via `sendCustomMessage`. And JS file will plot on the page. It used to work without any issues. For some reason, JS file does not work anymore. The only change I can recall is update from R 4.2.3 to R 4.3.0, but return to R4.2.3 does not help.



I have uninstalled nginx as proxy, mentioned above in this thread.

```r
# serve plot data to D3
observeEvent(input$plot.button, {
# json data for D3
  json_pmet <- pretty_json(jsonify::to_json(dat()))

  # send json from the session to javascript
  session$sendCustomMessage(type = "jsondata", json_pmet)
  }, ignoreNULL = FALSE, ignoreInit = FALSE)

# render JS here
output$d3 <- renderUI({
  HTML('<script type="text/javascript", src="heatmap.js">  </script>')
})
```





sessionInfo from RStudio
```bash
> sessionInfo()
R version 4.2.3 (2023-03-15)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.2.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] zip_2.3.0             tictoc_1.2            lubridate_1.9.2      
 [4] forcats_1.0.0         stringr_1.5.0         readr_2.1.4          
 [7] tidyr_1.3.0           tidyverse_2.0.0       tibble_3.2.1         
[10] snow_0.4-4            shinyWidgets_0.7.6    shinyvalidate_0.1.2  
[13] shinythemes_1.2.0     shinyjs_2.1.0         shinycssloaders_1.0.0
[16] shinyFeedback_0.4.0   shinydisconnect_0.1.0 shinydashboard_0.7.2 
[19] shinybusy_0.3.1.9000  shinyBS_0.61.1        scales_1.2.1         
[22] rintrojs_0.3.2        reshape2_1.4.4        purrr_1.0.1          
[25] promises_1.2.0.1      openxlsx_4.2.5.2      kableExtra_1.3.4     
[28] jsonify_1.2.2         glue_1.6.2            ggpubr_0.6.0         
[31] ggplot2_3.4.2         ggasym_0.1.6          future_1.32.0        
[34] fullPage_0.1.1        dplyr_1.1.2           DT_0.28              
[37] data.table_1.14.8     bslib_0.5.0           shiny_1.7.3          

loaded via a namespace (and not attached):
 [1] fontawesome_0.5.1 webshot_0.5.5     httr_1.4.6       
 [4] tools_4.2.3       backports_1.4.1   utf8_1.2.3       
 [7] R6_2.5.1          colorspace_2.1-0  withr_2.5.0      
[10] tidyselect_1.2.0  compiler_4.2.3    cli_3.6.1        
[13] rvest_1.0.3       xml2_1.3.4        sass_0.4.6       
[16] checkmate_2.2.0   systemfonts_1.0.4 digest_0.6.31    
[19] rmarkdown_2.23    svglite_2.1.1     pkgconfig_2.0.3  
[22] htmltools_0.5.5   parallelly_1.36.0 fastmap_1.1.1    
[25] htmlwidgets_1.6.2 rlang_1.1.1       rstudioapi_0.14  
[28] jquerylib_0.1.4   generics_0.1.3    jsonlite_1.8.7   
[31] car_3.1-2         magrittr_2.0.3    Rcpp_1.0.10      
[34] munsell_0.5.0     fansi_1.0.4       abind_1.4-5      
[37] lifecycle_1.0.3   stringi_1.7.12    carData_3.0-5    
[40] plyr_1.8.8        grid_4.2.3        parallel_4.2.3   
[43] listenv_0.9.0     hms_1.1.3         knitr_1.43       
[46] pillar_1.9.0      ggsignif_0.6.4    codetools_0.2-19 
[49] evaluate_0.21     vctrs_0.6.3       tzdb_0.4.0       
[52] httpuv_1.6.8      gtable_0.3.3      cachem_1.0.8     
[55] xfun_0.39         mime_0.12         xtable_1.8-4     
[58] broom_1.0.5       rstatix_0.7.2     later_1.3.1      
[61] viridisLite_0.4.2 memoise_2.0.1     timechange_0.2.0 
[64] globals_0.16.2    ellipsis_0.3.2   
```

sessionInfo from terminal
```bash
> sessionInfo()
R version 4.2.3 (2023-03-15)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.2.1

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_4.2.3
```
