### ISSUE TITLE
Error in .getReactiveEnvironment()$currentContext:

### ISSUE THREAD

**Issue by avijit09** [rstudio/shiny#2645] opened 2019-09-27 16:00 UTC
Hi Experts,

I am getting the following error running my shiny app

Error in .getReactiveEnvironment()$currentContext:Operation not allowed without an active reactive context.
can you pls help me to resolve this issue

**Comment by avijit09** [comment] 2019-09-27 16:07
snippet of my code:

server <- function(input, output) {
  output$offenseOutput <- renderPrint(renderUI({
    checkboxGroupInput("offenseInput", "Choose from below",
                       sort(unique(exclude_theft_crime$offense)),
                       selected = "robbery")

**Comment by cpsievert** [comment] 2019-09-27 16:17
Duplicate of #2644, see my comment there.

**Closed by cpsievert** 2019-09-27 16:17 UTC
