### ISSUE TITLE
Error when selecting points that are labeled by discrete colors

### ISSUE THREAD

**Issue by hzc363** [rstudio/shiny#2346] opened 2019-03-04 18:14 UTC
In my app,  I created a scatter plot and tried to isolate a subset of points using the selection tool from plotly. The selection tool works when the point are labeled with continuous color scale. However, when they are labeled with discrete colors, the lasso selection tool does not return the correct ID of the points. 

I have created a minimalism shiny app as an example using IRIS dataset. If I choose the continuous variable "Patel.Length" as color label, the selection tool works as expected. However, if I choose the categorical variable "Species" as color label, the selection tool will return a wrong set of points. 

``` r
library(shiny)
library(plotly)

##### ui of shiny app ####
ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      
      # select color label of the points
      selectInput("color", label = "Color label",
                  choices = c("Petal.Length","Species"),
                  multiple=FALSE, selectize=TRUE)
    ),
    mainPanel(plotlyOutput("plot"),
              verbatimTextOutput("print"))))

##### server of the siny app #####
server <- function(input, output, session) {
    d = iris
    
    # display the selected data 
    output$plot <- renderPlotly({
      s1<- event_data("plotly_selected")
      if(!is.null(s1)){d_plot =  d[s1$pointNumber+1,]}else{d_plot=d}

      p <- ggplot(d_plot, aes_string(x = "Sepal.Length", y = "Sepal.Width")) +
        geom_point(aes_string(color = input$color))
      ggplotly(p)%>% layout(dragmode = "lasso")
    })
    
    # print the id of selected points
    output$print <- renderPrint({
      s1 <- event_data("plotly_selected")
      if(!is.null(s1)){
        cat("The IDs of selected points are : ", (s1$pointNumber+1))
      }
    })

}

##### run the app #####
shinyApp(ui, server)
```

**Comment by cpsievert** [comment] 2019-03-04 18:35
Duplicate of https://github.com/ropensci/plotly/issues/1475

**Closed by cpsievert** 2019-03-04 18:35 UTC
