### ISSUE TITLE
Input binding for <input type="datetime-local">

### ISSUE THREAD

**Issue by jcheng5** [rstudio/shiny#290] opened 2013-10-26 17:50 UTC

**Comment by wch** [comment] 2015-03-04 22:23
I think the `<input type="datetime-local">` in particular isn't going to be very useful, since it's apparently not supported in IE or Firefox.

Do we still need this now that we have date inputs? I suppose it would nice to have *date-time* inputs. There are a couple of those out there, though none of them seem to have built-in support for ranges.

* http://tarruda.github.io/bootstrap-datetimepicker/
* http://eonasdan.github.io/bootstrap-datetimepicker/
* http://www.malot.fr/bootstrap-datetimepicker/

**Comment by bcorwin** [comment] 2016-05-10 16:17
Any update on this?

**Comment by alandipert** [comment] 2019-04-26 15:21
Closing because duplicate of #897

**Closed by alandipert** 2019-04-26 15:21 UTC
