### ISSUE TITLE
Feature request: Images associated with radioButton inputs

### ISSUE THREAD

**Issue by philchalmers** [rstudio/shiny#1348] opened 2016-09-01 18:41 UTC
Hi all,

Could something like the following be added naively to shiny? http://stackoverflow.com/questions/35783446/can-you-have-an-image-as-a-radiobutton-choice-in-shiny

I have interests in using the `radioButtons()` input along with .png files, where each response option is associated with a specific image. It also would have to be included naively (trying to avoid the `:::` operator for CRAN packages and stability across versions). Cheers.

**Comment by wch** [comment] 2016-09-01 22:09
This is a duplicate of #1202. I think I misunderstood that issue the first time around -- I actually think it's a good idea to allow HTML to be used for radio button choices. For this particular case, a choice would need a `<img>` tag and the image would need to be stored in a www/ subdirectory.

**Comment by philchalmers** [comment] 2016-09-01 22:52
Thanks for the quick reply, and sorry for not noticing that earlier related issue. Support for `HTML()` constructed input objects for each element in `choices` would be perfect for my situation (for my purpose the www/ subdirectory isn't necessarily needed, but an explicit path to the image file should be sufficient).

**Comment by bborgesr** [comment] 2017-03-27 15:56
Closed via d62a2fc (#1521)

**Closed by bborgesr** 2017-03-27 15:56 UTC
Labels: onhold, P3
