### ISSUE TITLE
`option(width ...)` reset when Rstudio Viewer windows size changed

### ISSUE THREAD

**Issue by vnijs** [rstudio/shiny#1913] opened 2017-12-22 06:28 UTC
I posted https://github.com/rstudio/rstudio/issues/1870 but the issue may also apply to Shiny 

If you run the app below from Rstudio and then click on the `print` radio button you see "Width: 250". However, if you start the app, then change the width of the Viewer panel in Rstudio, and **then** click on the `print` radio button in the app you'll see that the width has changed. This occurs in Chrome as well as Safari when the app is run `external` and also when run in the Rstudio Viewer. Screenshot added.

```
options(width = 250)

ui = fluidPage(
  tags$head(tags$style(HTML("pre { overflow: auto; }"))),
  sidebarLayout(
    sidebarPanel(
      radioButtons("display", "Display:",
        c("str" = "str", "print" = "print"),
        selected = "str",
        inline = TRUE
      )
    ),
    uiOutput("mp")
    ## if we use the mainpanel specs below rather than 
    ## uiOutput("mp"), options(width = ...) is not changed
    # mainPanel(
    #   conditionalPanel("input.display == 'str'", 
    #     verbatimTextOutput("str")
    #   ),
    #   conditionalPanel("input.display == 'summary'", 
    #     verbatimTextOutput("print")
    #   )
    # )
  )
)

server = shinyServer(function(input, output, session) {

  output$str <- renderPrint({
    str(mtcars)
  })

  output$print <- renderPrint({
    cat(paste0("Width: ", getOption("width"), "\n\n"))
    print(data.frame(matrix(1:120, ncol = 60, nrow = 2)), row.names = FALSE)
  })

  output$mp <- renderUI({
    mainPanel(
      conditionalPanel("input.display == 'str'", 
        verbatimTextOutput("str")
      ),
      conditionalPanel("input.display == 'print'", 
        verbatimTextOutput("print")
      )
    )
  })
})

shinyApp(ui = ui, server = server)

```

![image](https://user-images.githubusercontent.com/2998956/34287569-ed2fcdc6-e69c-11e7-86af-1e8965914571.png)

**Comment by bborgesr** [comment] 2018-04-11 19:00
Are you still experiencing this issue? It seems to work as expected for me. (RStudio IDE v 1.1.442)

**Comment by vnijs** [comment] 2018-04-12 02:05
Yep. Here is how to replicate: (1) Start the app, then (2) change the width of the **Viewer panel in Rstudio**, and then (3) click on the print radio button in the app you'll see that the width has changed. The main reason I care is that want users to run the app in the viewer window. It is a pretty big app (navbarPage) so they will likely have to increase the width of the window ... but then width of printed output is reset to something much too small and not the 250 I want.

![image](https://user-images.githubusercontent.com/2998956/38651822-05c3b876-3db8-11e8-8a55-6ddb23ccfcaf.png)

Session info from my mac shown below but this also happens on the daily build of Rstudio on Windows and rstudio server pro on linux.

> devtools::session_info()
Session info ------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.4 (2018-03-15)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.1.444)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/Los_Angeles         
 date     2018-04-11                  

Packages ----------------------------------------------------------------------------------------------------
 package   * version    date       source                           
 base      * 3.4.4      2018-03-15 local                            
 compiler    3.4.4      2018-03-15 local                            
 datasets  * 3.4.4      2018-03-15 local                            
 devtools    1.13.5     2018-02-18 CRAN (R 3.4.3)                   
 digest      0.6.15     2018-01-28 CRAN (R 3.4.3)                   
 graphics  * 3.4.4      2018-03-15 local                            
 grDevices * 3.4.4      2018-03-15 local                            
 htmltools   0.3.6      2017-04-28 CRAN (R 3.4.0)                   
 httpuv      1.3.6.9007 2018-04-11 Github (rstudio/httpuv@bfeccea)  
 jsonlite    1.5        2017-06-01 CRAN (R 3.4.0)                   
 later       0.7.1      2018-03-07 CRAN (R 3.4.4)                   
 magrittr    1.5        2014-11-22 CRAN (R 3.4.0)                   
 memoise     1.1.0      2017-04-21 CRAN (R 3.4.0)                   
 methods   * 3.4.4      2018-03-15 local                            
 mime        0.5        2016-07-07 CRAN (R 3.4.0)                   
 promises    1.0        2018-04-11 Github (rstudio/promises@8f3f988)
 R6          2.2.2      2017-06-17 CRAN (R 3.4.0)                   
 Rcpp        0.12.16    2018-03-13 cran (@0.12.16)                  
 rlang       0.2.0.9001 2018-04-11 Github (tidyverse/rlang@70d2d40) 
 rsconnect   0.8.8      2018-03-09 CRAN (R 3.4.4)                   
 shiny     * 1.0.5.9000 2018-04-11 Github (rstudio/shiny@99e5ef9)   
 stats     * 3.4.4      2018-03-15 local                            
 tools       3.4.4      2018-03-15 local                            
 utils     * 3.4.4      2018-03-15 local                            
 withr       2.1.2      2018-04-11 Github (jimhester/withr@79d7b0d) 
 xtable      1.8-2      2016-02-05 CRAN (R 3.4.0)                   
 yaml        2.1.18     2018-03-08 CRAN (R 3.4.4)

**Comment by vnijs** [comment] 2018-06-18 19:19
@bborgesr Any updates or suggestions on how to deal with this issue? Do you see a way to address this in Shiny?

**Comment by yyuan-convoy** [comment] 2019-02-12 00:31
Bump, I believe I'm experiencing a similar problem. In my case, I find the setting the `width` option (via the `width` parameter in `renderPrint()`) doesn't affect the print width in `verbatimTextOutput`. Either the `width` argument isn't what I think it is, or `verbatimTextOutput` doesn't respect it the way I would expect.

Here is my MWE:

```
library(shiny)

ui <- fluidPage(
   
  wellPanel(
    p('Default width'),
    verbatimTextOutput('default_width')
  ),
  
  wellPanel(
    p('Narrow width'),
    verbatimTextOutput('narrow_width')
  ),
  
  wellPanel(
    p('Wide width'),
    verbatimTextOutput('wide_width')
  )
)

server <- function(input, output) {
  
  x = rep(1, 60)
   
   output$default_width <- renderPrint({
     cat('Width: ', getOption('width'), '\n'); x
   })
   
   output$narrow_width <- renderPrint({
     cat('Width: ', getOption('width'), '\n'); x
   }, width = 10)
   
   output$wide_width <- renderPrint({
     cat('Width: ', getOption('width'), '\n'); x
   }, width = 200)
}

shinyApp(ui = ui, server = server)
```

And see accompanying screenshot of the results.
<img width="1195" alt="screen shot 2019-02-11 at 4 27 58 pm" src="https://user-images.githubusercontent.com/39921311/52603084-1225b800-2e1a-11e9-8293-17e4549fc352.png">

And my session info:

```
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin17.6.0 (64-bit)
Running under: macOS  10.14.2

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_1.2.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0      digest_0.6.18   crayon_1.3.4    later_0.7.5     mime_0.6        R6_2.3.0        xtable_1.8-3   
 [8] jsonlite_1.6    magrittr_1.5    rlang_0.3.1     rstudioapi_0.8  promises_1.0.1  tools_3.5.1     httpuv_1.4.5   
[15] yaml_2.2.0      compiler_3.5.1  htmltools_0.3.6
```

**Comment by yyuan-convoy** [comment] 2019-02-12 00:44
Solution: It appears that using the `print()` statement will properly respect the width!

**Comment by vnijs** [comment] 2019-02-12 04:41
FYI: I still see the same problem described earlier where a data.frame is printed at a width different than what was set in the app after the user drags to change window sizes in Rstudio

**Comment by hadley** [comment] 2020-04-28 16:52
Duplicate of #2805

**Closed by hadley** 2020-04-28 16:52 UTC
