### ISSUE TITLE
runApp() and KDE browsers

### ISSUE THREAD

**Issue by unDocUMeantIt** [rstudio/shiny#150] opened 2013-04-21 13:19 UTC
i've tried runExample() and runApp() with KDE's browsers konqueror (rendering with KHTML) and rekonq (webkit), version 4.10.2. apps are only partly shown (no results are produced, conditional panels are ignored), while everything works fine in firefox.

however, when i installed shiny-server and started the same apps through it, they ran fine in all browsers. so apparently it's not really an issue on the browser side, but probably in the way runApp() deploys apps?

i tried with the CRAN version of shiny as well as a recent git snapshot.

**Comment by alandipert** [comment] 2019-04-24 21:04
Oh, hello 😄 I'm sorry nobody ever got back to you.

I'm closing this because I don't have an easy way to test for myself whether this remains a problem, and because nobody else has reported it since 2013.

If it's still a problem for you, please don't hesitate to create a new issue that includes your browser versions, and I will work to reproduce.

**Closed by alandipert** 2019-04-24 21:04 UTC
