### ISSUE TITLE
Error/crash with stopApp() on OSX

### ISSUE THREAD

**Issue by lorenzgerber** [rstudio/shiny#869] opened 2015-06-17 09:27 UTC
I use a shiny in-line app in an R function. The shiny app returns a value  `stopApp(value)` to the calling R function. This works fine the first time when I run the code in a session (or after building the package) but it crashes on every further execution time. 

The crash can be noticed by the fact that `Sys.sleep()` is not run and `shinyTest()` does not return any value. I get however no error message/warning on the console.

The same code works fine on Linux and Windows. 

```{r}
shinyTest<-function(){
  library(shiny)
  testo<-runApp(list(
    ui = shinyUI(fluidPage(
      actionButton("do", "Click Me")
    )),
    server = shinyServer(function(input, output, session) {
      observeEvent(input$do, {
        stopApp('test')
      })
    })
  ))
  Sys.sleep(5)
  return(testo)
}
```

This error kind of kills the otherwise great in-line R function capability of Shiny apps...

**Comment by wch** [comment] 2015-06-17 16:09
Very weird, there seems to be an odd interaction between Shiny and `Sys.sleep()` on a Mac. I'm not able to reproduce this on Linux. Here's a modified version of your app. Notice that after clicking the button, it doesn't run the code after `Sys.sleep()`:

```R
library(shiny)
shinyTest<-function(){
  library(shiny)
  testo <- runApp(list(
    ui = shinyUI(fluidPage(
      actionButton("do", "Click Me")
    )),
    server = shinyServer(function(input, output, session) {
      observeEvent(input$do, {
        cat("Button clicked\n")
        stopApp("Return value")
      })
    })
  ))
  
  cat("Before sleep\n")
  print(testo)
  Sys.sleep(1)
  cat("After sleep\n")
  print(testo)
  testo
}

shinyTest()
# Button clicked
# Before sleep
# [1] "Return value"
```


I thought it might be a problem with just `Sys.sleep()`, and not Shiny, but that theory seems wrong, as demonstrated by this code:

```R
sleepTest <- function(sleep) {
  cat("Before sleep\n")
  if (sleep) Sys.sleep(1)
  cat("After sleep\n")
}

sleepTest(TRUE)
# Before sleep
# After sleep

sleepTest(FALSE)
# Before sleep
# After sleep
```

**Comment by wch** [comment] 2015-06-17 16:24
Another data point: When I run this code on my Mac in RStudio, I get the weird behavior. But if I run it from R in the terminal, it works fine. So it may be an interaction with RStudio as well.

**Comment by yihui** [comment] 2015-06-17 17:13
I remember JJ once told me RStudio did something special to Sys.sleep(). I'm not sure if that is relevant here.

**Comment by lorenzgerber** [comment] 2015-06-17 18:02
I put the `Sys.sleep()` just to make the error more clear. In my production code where I first came about the error, there is no `Sys.sleep()`. Another funny thing is that the crash doesn't happen immediately after leaving the Shiny App. In my production code, the R function would run on sometimes two, sometimes three statements before crashing.

**Comment by jcheng5** [comment] 2015-06-17 18:07
cc @jmcphers @jjallaire @kevinushey

**Comment by jjallaire** [comment] 2015-06-17 18:09
We no longer do anything special in Sys.sleep (we used to pre R 3.0 but don't any longer).

**Comment by jjallaire** [comment] 2015-06-17 18:10
If RStudio is crashing you can find a stack trace by using the **Console** application and finding crash reports for the `rsession` process.

**Comment by jcheng5** [comment] 2015-06-17 18:13
@jjallaire The weird thing is that it's not crashing--just silently returning to the prompt, without finishing the code it was executing.

**Comment by wch** [comment] 2015-06-17 18:14
I just ran the same code with RStudio 0.98.1083, and had the same problematic result. Here's my session info:

```R
> devtools::session_info()
Session info ----------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.0 (2015-04-16)
 system   x86_64, darwin13.4.0        
 ui       RStudio (0.98.1083)         
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/Chicago             

Packages --------------------------------------------------------------------------
 package    * version   date       source        
 curl         0.8       2015-06-06 CRAN (R 3.2.0)
 devtools   * 1.8.0     2015-05-09 CRAN (R 3.2.0)
 digest       0.6.8     2014-12-31 CRAN (R 3.2.0)
 git2r        0.10.1    2015-05-07 CRAN (R 3.2.0)
 htmltools    0.2.6     2014-09-08 CRAN (R 3.2.0)
 httpuv       1.3.2     2014-10-23 CRAN (R 3.2.0)
 jsonlite     0.9.16    2015-04-11 CRAN (R 3.2.0)
 memoise      0.2.1     2014-04-22 CRAN (R 3.2.0)
 mime         0.3       2015-03-29 CRAN (R 3.2.0)
 R6           2.0.1     2014-10-29 CRAN (R 3.2.0)
 Rcpp         0.11.6    2015-05-01 CRAN (R 3.2.0)
 rstudio      0.98.1083 2015-06-17 local         
 rstudioapi   0.3.1     2015-04-07 CRAN (R 3.2.0)
 rversions    1.0.1     2015-06-06 CRAN (R 3.2.0)
 shiny      * 0.12.1    2015-06-12 CRAN (R 3.2.0)
 xml2         0.1.1     2015-06-02 CRAN (R 3.2.0)
 xtable       1.7-4     2014-09-12 CRAN (R 3.2.0)
```

**Comment by jcheng5** [comment] 2015-06-17 18:16
I used to demonstrate [ikmeans.R](https://gist.github.com/jcheng5/8303235) on Mac, clearly this can't always have been a problem...

**Comment by kevinushey** [comment] 2015-06-17 18:24
Any chance that we can get a reproducible example without Shiny? E.g. some minimal simulation of what `runApp()` does?

**Comment by jcheng5** [comment] 2015-06-17 18:25
I'll see if I can make an httpuv example.

**Comment by jcheng5** [comment] 2015-06-17 18:27
No repro for me with Winston's test.

```r
R version 3.2.0 (2015-04-16)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.3 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_0.12.1   leaflet_0.0.16

loaded via a namespace (and not attached):
 [1] Rcpp_0.11.6      rstudioapi_0.3.1 knitr_1.10.5     xml2_0.1.1      
 [5] magrittr_1.5     devtools_1.8.0   xtable_1.7-4     R6_2.0.1        
 [9] stringr_1.0.0    httr_0.6.1       tools_3.2.0      git2r_0.10.1    
[13] htmltools_0.2.6  rversions_1.0.1  yaml_2.1.13      digest_0.6.8    
[17] htmlwidgets_0.4  bitops_1.0-6     RCurl_1.95-4.6   curl_0.8        
[21] memoise_0.2.1    mime_0.3         stringi_0.4-1    jsonlite_0.9.16 
[25] httpuv_1.3.2

**Comment by wch** [comment] 2015-06-17 18:46
@hadley says he can't repro either.

@lorenzgerber For me, my test app doesn't even work the first time. Do you get the error when you run R from the terminal (not RStudio)?

**Comment by jjallaire** [comment] 2015-06-17 19:09
I can't repro either.

**Comment by wch** [comment] 2015-06-17 19:23
I've found that if I set `options(shiny.launch.browser = FALSE)`, and then view the app in Chrome (as opposed to RStudio's window), the problem doesn't happen -- I get the ""After sleep" text.

@jcheng says he is able to reproduce this behavior: he sees the problem when the RStudio viewer window is used, but not when Chrome is used.

**Comment by wch** [comment] 2015-06-17 19:27
The problem also does not happen when the RStudio viewer pane (as opposed to the viewer window) is used, e.g., with `options(shiny.launch.browser=rstudioapi::viewer)`.

**Comment by hadley** [comment] 2015-06-17 19:30
FWIW, in my case it nothing appears in the viewer, and I have to open it in an external window before I can even click the button

**Comment by jmcphers** [comment] 2015-06-17 20:08
@lorenzgerber et al. -- I just went over this in a call with @wch. I think this is actually an IDE bug: when the RStudio Shiny window is closed, it always interrupts R in order to stop the Shiny app and get you back to a console prompt. 

In this case, however, the timing is such that Shiny is already stopped, and the interrupt actually breaks the evaluation of the `shinyTest` function instead of stopping Shiny. We can fix this in the IDE by being smarter about interrupting R (i.e. we won't do it when the window is being torn down as a result of the app completing execution). I'm closing this bug and I'll file one for the IDE.

**Closed by jmcphers** 2015-06-17 20:08 UTC

**Comment by lorenzgerber** [comment] 2015-06-17 21:09
@wch right, does not happen when run from terminal. On RStudio, it works for me the first time. However, some of my collaborators said that it didn't work for them at all.
@jmcphers ok, thanks. Could you post the link to the new issue on IDE, I'd like to follow it as this is important for my current work.

**Comment by jmcphers** [comment] 2015-06-17 21:13
Unfortunately we don't currently have a public-facing issue tracking system for the IDE. It's on the list. :-) I'll post a comment on this Shiny issue when we have a fix.

**Comment by colinbrislawn** [comment] 2017-06-09 17:48
Has this been fixed in a newer version of the Rstudio IDE?

I've been using .99 so I'm not sure if this is fixed in 1.x...
