### ISSUE TITLE
dateInput(): entering numbers into field crashes app

### ISSUE THREAD

**Issue by coolbutuseless** [rstudio/shiny#803] opened 2015-04-18 21:24 UTC
What happens
--------------------
If you enter digits directly into dateInput() field, you can get the whole app to crash with
```r
Error in charToDate(x) : 
  character string is not in a standard unambiguous format
```

How to replicate
----------------------

* Have a dateInput() field in a shiny app
* put your cursor in it and just start pressing '1'. 
* after a few presses, app will crash because of unparseable date.

Expected behaviour
---------------------------
A user entering an incorrect/unparseable date into a form field shouldn't crash the app. 

Running R3.1.3, shiny-0.11.1 on rstudio-0.99.335

**Comment by wch** [comment] 2015-04-19 03:30
I'm not able to replicate this behavior with this example app: http://shiny.rstudio.com/gallery/date-and-date-range.html

Could you provide a minimal reproducible example app?

**Comment by wch** [comment] 2015-04-19 03:33
Oh, actually, I was able to reproduce it with that app. Previously I was clearing the text and typing `11111...`, but I found that by not first clearing the text, I can make it crash.

**Comment by kismsu** [comment] 2015-06-24 14:05
Looks like this hasn't been fixed in in 0.12.1.

**Comment by dcenergy-reeve** [comment] 2015-10-01 19:44
This is still an ongoing issue, and happens with both dateInput and dateRangeInput.  Typing a number in front the year without deleting it first will cause the app to crash (see screenshot below).

Minimal reproducible example:

app <- shinyApp(
  ui = bootstrapPage(
    dateRangeInput('dateRange', 'Date Range Input'),
    dateInput('date', 'Date Input')
    
  ),
  server = function(input, output, session) {
  }
)
runApp(app)

Type any date into the input field to the left of the current date, and the app will crash.

![image](https://cloud.githubusercontent.com/assets/13053362/10231789/afe2709c-6852-11e5-8062-e95ad5d4c7bf.png)

**Comment by kismsu** [comment] 2016-07-11 09:00
Any thoughts about this issue? Looks like it is still failing.

**Closed** 2016-08-13 02:29 UTC
Labels: date-time, P2, review
