### ISSUE TITLE
ReferenceError: Can't find variable: Shiny

### ISSUE THREAD

**Issue by AgazW** [rstudio/shiny#2298] opened 2019-01-10 07:55 UTC
I upgraded to `R 3.5.1` and all other packages on CentOs6, but I get some issue where only the content is loading without graphics. I don't get any error in the log file but I get some in the JS console.

**Comment by AgazW** [comment] 2019-01-10 07:57
![screen shot 2019-01-10 at 1 26 38 pm](https://user-images.githubusercontent.com/10917932/50954088-754ec280-14db-11e9-90e9-17aa9db79d0c.png)

**Comment by wch** [comment] 2019-01-10 22:48
It's possible that it's related to old packages that aren't compatible with R 3.5.1. Please see:
https://shiny.rstudio.com/articles/upgrade-R.html

**Comment by AgazW** [comment] 2019-01-11 00:41
Thank you for your comment. I would say that I installed `3.5.1` and all the packages anew to the latest versions, but still, I get the issue.

**Comment by wch** [comment] 2019-01-11 15:34
I doubt the problem is with Shiny itself. It looks there's probably a problem serving up many of the files. It's possible something is wrong with your Shiny Server configuration, or if you have a proxy, it might be configured incorrectly to work with Shiny Server.

**Comment by AgazW** [comment] 2019-01-12 08:09
My `.config` file 
`Last login: Sat Jan 12 10:06:53 on console
HussainWanis-MacBook-Air:~ hussainwani$ vi .Renviron
HussainWanis-MacBook-Air:~ hussainwani$ ls
Applications		Library			Mypackage_0.1.0.tar.gz
Desktop			Movies			Pictures
Django			Music			Public
Documents		Mypackage
Downloads		Mypackage.Rcheck
HussainWanis-MacBook-Air:~ hussainwani$ cd Desktop/
HussainWanis-MacBook-Air:Desktop hussainwani$ ls
All 4 data types
MAMGEDOnline_with_Agilent05_10_18
MAMGED_with_Agilent05_10_18
Mamgeed server copy
Sample data
Screen Shot 2019-01-10 at 1.17.33 PM.png
Screen Shot 2019-01-10 at 1.26.38 PM.png
Screen Shot 2019-01-11 at 4.56.32 PM.png
data
test.html
HussainWanis-MacBook-Air:Desktop hussainwani$ cd
HussainWanis-MacBook-Air:~ hussainwani$ pwd
/Users/hussainwani
HussainWanis-MacBook-Air:~ hussainwani$ ls
Applications		Library			Mypackage_0.1.0.tar.gz
Desktop			Movies			Pictures
Django			Music			Public
Documents		Mypackage
Downloads		Mypackage.Rcheck
HussainWanis-MacBook-Air:~ hussainwani$ vi .Renviron 
HussainWanis-MacBook-Air:~ hussainwani$ ssh ibab@192.168.1.125
ibab@192.168.1.125's password: 
Last login: Sat Jan 12 09:53:25 2019 from 192.168.2.122
-bash: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
[ibab@pirnabank ~]$ ls
389-admin-console-1.1.8-1.el6.noarch.rpm  backup_cron
AnnotationDbi_1.40.0.tar.gz               base64enc_0.1-3.tar.gz
BiocGenerics_0.24.0.tar.gz                index.html
Data-Types-0.09                           mailR_0.4.1.tar.gz
R                                         sendmailR_1.2-1.tar.gz
R-3.3.3                                   shiny-server
R-3.4.1                                   shiny-server-1.4.2.786-rh5-x86_64.rpm
R-3.4.1.tar.gz                            zlib-1.2.11
R.utils_2.6.0.tar.gz                      zlib-1.2.11.tar.gz
R_packages
[ibab@pirnabank ~]$ sudo status shiny-server
[sudo] password for ibab: 
shiny-server stop/waiting
[ibab@pirnabank ~]$ sudo start shiny-server
shiny-server start/running, process 26723
[ibab@pirnabank ~]$ ls
389-admin-console-1.1.8-1.el6.noarch.rpm  backup_cron
AnnotationDbi_1.40.0.tar.gz               base64enc_0.1-3.tar.gz
BiocGenerics_0.24.0.tar.gz                index.html
Data-Types-0.09                           mailR_0.4.1.tar.gz
R                                         sendmailR_1.2-1.tar.gz
R-3.3.3                                   shiny-server
R-3.4.1                                   shiny-server-1.4.2.786-rh5-x86_64.rpm
R-3.4.1.tar.gz                            zlib-1.2.11
R.utils_2.6.0.tar.gz                      zlib-1.2.11.tar.gz
R_packages
[ibab@pirnabank ~]$ sudo su - -c "R -e \"install.packages('shiny', repos='http://cran.rstudio.com/')\""
[sudo] password for ibab: 

R version 3.5.1 (2018-07-02) -- "Feather Spray"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-redhat-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> install.packages('shiny', repos='http://cran.rstudio.com/')
Installing package into ‘/usr/lib64/R/library’
(as ‘lib’ is unspecified)
trying URL 'http://cran.rstudio.com/src/contrib/shiny_1.2.0.tar.gz'
Content type 'application/x-gzip' length 2987723 bytes (2.8 MB)
==================================================
downloaded 2.8 MB

* installing *source* package ‘shiny’ ...
** package ‘shiny’ successfully unpacked and MD5 sums checked
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package ‘shiny’
    finding HTML links ... done
    HTML                                    html  
    NS                                      html  
    Progress                                html  
    absolutePanel                           html  
    actionButton                            html  
    addResourcePath                         html  
    applyInputHandlers                      html  
    bookmarkButton                          html  
    bootstrapLib                            html  
    bootstrapPage                           html  
    brushOpts                               html  
    brushedPoints                           html  
    builder                                 html  
Rd warning: /tmp/Rtmpmhxgz9/R.INSTALL69d447dd7938/shiny/man/builder.Rd:78: file link ‘as.character’ in package ‘base’ does not exist and so has been treated as a topic
    callModule                              html  
    checkboxGroupInput                      html  
    checkboxInput                           html  
    clickOpts                               html  
    column                                  html  
    conditionalPanel                        html  
    createRenderFunction                    html  
    createWebDependency                     html  
    dateInput                               html  
    dateRangeInput                          html  
    dblclickOpts                            html  
    debounce                                html  
    diskCache                               html  
    domains                                 html  
    downloadButton                          html  
    downloadHandler                         html  
    enableBookmarking                       html  
    exportTestValues                        html  
    exprToFunction                          html  
    fileInput                               html  
    fillPage                                html  
    fillRow                                 html  
    fixedPage                               html  
    flowLayout                              html  
    fluidPage                               html  
    freezeReactiveValue                     html  
    getCurrentOutputInfo                    html  
    getQueryString                          html  
    headerPanel                             html  
    helpText                                html  
    hoverOpts                               html  
    htmlOutput                              html  
    htmlTemplate                            html  
    finding level-2 HTML links ... done

    icon                                    html  
    include                                 html  
    inputPanel                              html  
    insertTab                               html  
    insertUI                                html  
    installExprFunction                     html  
    invalidateLater                         html  
    is.reactivevalues                       html  
    isRunning                               html  
    isolate                                 html  
Rd warning: /tmp/Rtmpmhxgz9/R.INSTALL69d447dd7938/shiny/man/isolate.Rd:28: file link ‘local’ in package ‘base’ does not exist and so has been treated as a topic
    key_missing                             html  
    knitr_methods                           html  
    knitr_methods_htmltools                 html  
    mainPanel                               html  
    makeReactiveBinding                     html  
    markOutputAttrs                         html  
    markRenderFunction                      html  
    maskReactiveContext                     html  
    memoryCache                             html  
    modalButton                             html  
    modalDialog                             html  
    navbarPage                              html  
    navlistPanel                            html  
    nearPoints                              html  
    numericInput                            html  
    observe                                 html  
    observeEvent                            html  
    onBookmark                              html  
    onFlush                                 html  
    onStop                                  html  
    outputOptions                           html  
    pageWithSidebar                         html  
    parseQueryString                        html  
    passwordInput                           html  
    plotOutput                              html  
    plotPNG                                 html  
    radioButtons                            html  
    reactive                                html  
    reactiveFileReader                      html  
    reactivePlot                            html  
    reactivePoll                            html  
    reactivePrint                           html  
    reactiveTable                           html  
    reactiveText                            html  
    reactiveTimer                           html  
    reactiveUI                              html  
    reactiveVal                             html  
    reactiveValues                          html  
    reactiveValuesToList                    html  
Rd warning: /tmp/Rtmpmhxgz9/R.INSTALL69d447dd7938/shiny/man/reactiveValuesToList.Rd:16: file link ‘as.list’ in package ‘base’ does not exist and so has been treated as a topic
    registerInputHandler                    html  
    removeInputHandler                      html  
    removeUI                                html  
    renderCachedPlot                        html  
    renderDataTable                         html  
Rd warning: /tmp/Rtmpmhxgz9/R.INSTALL69d447dd7938/shiny/man/renderDataTable.Rd:48: file link ‘I’ in package ‘base’ does not exist and so has been treated as a topic
    renderImage                             html  
    renderPlot                              html  
Rd warning: /tmp/Rtmpmhxgz9/R.INSTALL69d447dd7938/shiny/man/renderPlot.Rd:36: file link ‘replayPlot’ in package ‘grDevices’ does not exist and so has been treated as a topic
    renderPrint                             html  
    renderTable                             html  
    renderText                              html  
    renderUI                                html  
    repeatable                              html  
Rd warning: /tmp/Rtmpmhxgz9/R.INSTALL69d447dd7938/shiny/man/repeatable.Rd:25: file link ‘.Random.seed’ in package ‘base’ does not exist and so has been treated as a topic
    req                                     html  
    restoreInput                            html  
    runApp                                  html  
    runExample                              html  
    runGadget                               html  
    runUrl                                  html  
    safeError                               html  
    selectInput                             html  
Rd warning: /tmp/Rtmpmhxgz9/R.INSTALL69d447dd7938/shiny/man/selectInput.Rd:45: file link ‘I’ in package ‘base’ does not exist and so has been treated as a topic
    serverInfo                              html  
    session                                 html  
    setBookmarkExclude                      html  
    setSerializer                           html  
    shiny-options                           html  
    shiny-package                           html  
    shinyApp                                html  
    shinyDeprecated                         html  
    shinyOptions                            html  
    shinyServer                             html  
    shinyUI                                 html  
    showBookmarkUrlModal                    html  
    showModal                               html  
    showNotification                        html  
    showReactLog                            html  
    showTab                                 html  
    sidebarLayout                           html  
    sidebarPanel                            html  
    singleton                               html  
    sizeGrowthRatio                         html  
    sliderInput                             html  
Rd warning: /tmp/Rtmpmhxgz9/R.INSTALL69d447dd7938/shiny/man/sliderInput.Rd:66: file link ‘strftime’ in package ‘base’ does not exist and so has been treated as a topic
    snapshotExclude                         html  
    snapshotPreprocessInput                 html  
    snapshotPreprocessOutput                html  
    splitLayout                             html  
    stacktrace                              html  
    stopApp                                 html  
    submitButton                            html  
    suppressDependencies                    html  
    tabPanel                                html  
    tableOutput                             html  
    tabsetPanel                             html  
    tag                                     html  
Rd warning: /tmp/Rtmpmhxgz9/R.INSTALL69d447dd7938/shiny/man/tag.Rd:42: file link ‘as.character’ in package ‘base’ does not exist and so has been treated as a topic
    textAreaInput                           html  
    textInput                               html  
    textOutput                              html  
    titlePanel                              html  
    updateActionButton                      html  
    updateCheckboxGroupInput                html  
    updateCheckboxInput                     html  
    updateDateInput                         html  
    updateDateRangeInput                    html  
    updateNumericInput                      html  
    updateQueryString                       html  
    updateRadioButtons                      html  
    updateSelectInput                       html  
Rd warning: /tmp/Rtmpmhxgz9/R.INSTALL69d447dd7938/shiny/man/updateSelectInput.Rd:43: file link ‘I’ in package ‘base’ does not exist and so has been treated as a topic
    updateSliderInput                       html  
    updateTabsetPanel                       html  
    updateTextAreaInput                     html  
    updateTextInput                         html  
    urlModal                                html  
    validate                                html  
    validateCssUnit                         html  
    varSelectInput                          html  
Rd warning: /tmp/Rtmpmhxgz9/R.INSTALL69d447dd7938/shiny/man/varSelectInput.Rd:39: file link ‘I’ in package ‘base’ does not exist and so has been treated as a topic
Rd warning: /tmp/Rtmpmhxgz9/R.INSTALL69d447dd7938/shiny/man/varSelectInput.Rd:54: file link ‘!!’ in package ‘rlang’ does not exist and so has been treated as a topic
Rd warning: /tmp/Rtmpmhxgz9/R.INSTALL69d447dd7938/shiny/man/varSelectInput.Rd:57: file link ‘!!!’ in package ‘rlang’ does not exist and so has been treated as a topic
    verbatimTextOutput                      html  
    verticalLayout                          html  
    viewer                                  html  
    wellPanel                               html  
    withMathJax                             html  
    withProgress                            html  
    withTags                                html  
** building package indices
** testing if installed package can be loaded
* DONE (shiny)
Making 'packages.html' ... done

The downloaded source packages are in
	‘/tmp/Rtmp159fhe/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
> 
> 
[ibab@pirnabank ~]$ ls
389-admin-console-1.1.8-1.el6.noarch.rpm  backup_cron
AnnotationDbi_1.40.0.tar.gz               base64enc_0.1-3.tar.gz
BiocGenerics_0.24.0.tar.gz                index.html
Data-Types-0.09                           mailR_0.4.1.tar.gz
R                                         sendmailR_1.2-1.tar.gz
R-3.3.3                                   shiny-server
R-3.4.1                                   shiny-server-1.4.2.786-rh5-x86_64.rpm
R-3.4.1.tar.gz                            zlib-1.2.11
R.utils_2.6.0.tar.gz                      zlib-1.2.11.tar.gz
R_packages
[ibab@pirnabank ~]$ sudo -i R

R version 3.5.1 (2018-07-02) -- "Feather Spray"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-redhat-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

During startup - Warning message:
Setting LC_CTYPE failed, using "C" 
> library(shiny)
> packageVersion('shiny')
[1] '1.2.0'
> packageVersion('shinyjs')
[1] '1.0'
> q()
Save workspace image? [y/n/c]: n
[ibab@pirnabank ~]$ ls
389-admin-console-1.1.8-1.el6.noarch.rpm  backup_cron
AnnotationDbi_1.40.0.tar.gz               base64enc_0.1-3.tar.gz
BiocGenerics_0.24.0.tar.gz                index.html
Data-Types-0.09                           mailR_0.4.1.tar.gz
R                                         sendmailR_1.2-1.tar.gz
R-3.3.3                                   shiny-server
R-3.4.1                                   shiny-server-1.4.2.786-rh5-x86_64.rpm
R-3.4.1.tar.gz                            zlib-1.2.11
R.utils_2.6.0.tar.gz                      zlib-1.2.11.tar.gz
R_packages
[ibab@pirnabank ~]$ vi /etc/shiny-server/.config
[ibab@pirnabank ~]$ cd
[ibab@pirnabank ~]$ vi /etc/shiny-server/shiny-server.conf 
[ibab@pirnabank ~]$ sudo vi /etc/shiny-server/shiny-server.conf 
[sudo] password for ibab: 
[ibab@pirnabank ~]$ sudo vi /etc/shiny-server/shiny-server.conf 
[ibab@pirnabank ~]$ sudo stop shiny-server
shiny-server stop/waiting
[ibab@pirnabank ~]$ sudo start shiny-server
shiny-server start/running, process 27383
[ibab@pirnabank ~]$ sudo vi /etc/shiny-server/shiny-server.conf 

# Instruct Shiny Server to run applications as the user "shiny"
run_as ibab;
preserve_logs true;
# Define a server that listens on port 3838
server {
  listen 3838;

  # Define a location at the base URL
  location / {
    # Only allow up to one connection per Shiny process, and at most five
    # Shiny processes per application.
    #utilization_scheduler 1 .7 5;

    # Host the directory of Shiny Apps stored in this directory
    site_dir /srv/shiny-server;

    # Log all Shiny output to files in this directory
    log_dir /var/log/shiny-server;

    # When a user visits the base URL rather than a particular application,
    # an index of the applications available in this directory will be shown.
    directory_index on;
  }
}'

**Comment by AgazW** [comment] 2019-01-14 05:16
In google chrome, I get some different errors

![screen shot 2019-01-14 at 10 45 25 am](https://user-images.githubusercontent.com/10917932/51097370-98ce8180-17e9-11e9-875f-f1aa646581f8.png)

**Comment by jcheng5** [comment] 2019-01-14 14:57
Do you see anything in /var/log/shiny-server/*.log or in /var/log/shiny-server.log? I'm guessing your R process is crashing because of a missing R package dependency besides shiny.

**Comment by jcheng5** [comment] 2019-01-14 14:58
Oh, I just saw your note about shinyjs. Make sure that ALL packages that your app depends on are installed under R 3.5.1.

**Comment by AgazW** [comment] 2019-01-16 09:51
In `/var/log/shiny-server.log`

```
[^[[32m[2019-01-16 14:54:38.108] [INFO] shiny-server - ^[[39mStopping listener on 0.0.0.0:3838
^[[32m[2019-01-16 14:54:38.108] [INFO] shiny-server - ^[[39mShutting down worker processes (with notification)

/opt/shiny-server/lib/main.js:367
  throw err;
        ^
TypeError: Cannot read property 'readable' of null
    at ServerResponse.ondrain (/opt/shiny-server/node_modules/http-proxy/lib/node-http-proxy/http-proxy.js:327:19)
    at ServerResponse.emit (events.js:92:17)
    at Socket.ondrain (http.js:1855:44)
    at Socket.emit (events.js:117:20)
    at onwriteDrain (_stream_writable.js:289:12)
    at afterWrite (_stream_writable.js:277:5)
    at onwrite (_stream_writable.js:270:7)
    at Socket.WritableState.onwrite (_stream_writable.js:97:5)
    at Object.afterWrite (net.js:731:12)
0^[[32m[2019-01-16 14:54:41.765] [INFO] shiny-server - ^[[39mShiny Server v1.4.2.786 (Node.js v0.10.40)
^[[32m[2019-01-16 14:54:41.769] [INFO] shiny-server - ^[[39mUsing pidfile /var/run/shiny-server.pid
](url)
```

**Comment by AgazW** [comment] 2019-01-16 12:03
Thank you for your time. Upgrading `shiny-server` to the latest version fixed the issue.

**Comment by alandipert** [comment] 2019-03-30 08:03
@AgazW I'm closing this because it appears your issue has been resolved. Feel free to re-open if I'm wrong.

**Closed by alandipert** 2019-03-30 08:03 UTC
