### ISSUE TITLE
updateSliderInput does not handle named vectors well

### ISSUE THREAD

**Issue by hherrada** [rstudio/shiny#1465] opened 2016-11-15 21:27 UTC
Example:

```
server <- function(input, output, clientData, session) {
  
  observe({
    updateSliderInput(session, "inSlider",
                      label = "Slider",
                      value = quantile(1:12,.5, names = FALSE))
  })
  
}

ui <- shinyUI(
  sliderInput("inSlider", "Slider input:",
              min = 1, max = 20, value = 15)
)  

shinyApp(ui,server)

```
When `names = TRUE` the following warning appears:

```
Input to asJSON(keep_vec_names=TRUE) is a named vector. In a future version of jsonlite, this option will not be supported, and named vectors will be translated into arrays instead of objects. If you want JSON object output, please use a named list instead. See ?toJSON.
```

**Comment by bborgesr** [comment] 2016-11-25 15:53
Yes, I think that, unfortunately, that is not going to be supported at all by `jsonlite` or Shiny. The idea behind that warning is (from Winston's comment at jeroenooms/jsonlite#76):

> compatibility option would just be there as a stopgap solution, until developers have enough time to switch their code to named lists.

This is what is likely to happen in the future:

> How about having a backward-compatibility option for this, where it will output JSON objects and also print a message saying that a named list should be used instead? Then I think after some time, it could be changed to an error, and then later it could be removed.

The error message can be traced to [this commit](https://github.com/wch/jsonlite/commit/9091eb0b3ecb48fffc5ad4e8fbae67ca84ff673f).

So, I'd recommend you change your code to use named lists.

@wch: let me know if this is not accurate
Closing this for now.

**Closed** 2016-11-25 15:53 UTC

**Comment by wch** [comment] 2016-11-27 17:48
That's the expected behavior; you should just use pass unnamed vectors to `updateSliderInput`.

**Comment by sanjmeh** [comment] 2020-02-02 18:25
I get the same warning: `Input to asJSON(keep_vec_names=TRUE)...` The problem is which variable to check. I use `shiny modules` and this warning pops up after the input sliders adjust to certain levels - not all the time.
I don't use `updateSliderInput` and don't even know which variable is causing this warning. Pasting the full warning text and the previous warning too although it seems not connected.

> Warning: Removed 20 rows containing missing values (geom_point).
Input to asJSON(keep_vec_names=TRUE) is a named vector. In a future version of jsonlite, this option will not be supported, and named vectors will be translated into arrays instead of objects. If you want JSON object output, please use a named list instead. See ?toJSON

I haven't explicitly used named vectors anywhere. Have used following shiny widgets in the module when this warning appears:

` dateRangeInput`
` selectInput`
Creating a min reprex for a shiny warning is a huge task but if there is any hint on what to check and where to look I can perhaps solve this without a full fledged issue or SO question.

**Comment by conrad-mac** [comment] 2020-02-25 02:15
> I get the same warning: `Input to asJSON(keep_vec_names=TRUE)...` The problem is which variable to check. I use `shiny modules` and this warning pops up after the input sliders adjust to certain levels - not all the time.
> I don't use `updateSliderInput` and don't even know which variable is causing this warning. Pasting the full warning text and the previous warning too although it seems not connected.
> 
> > Warning: Removed 20 rows containing missing values (geom_point).
> > Input to asJSON(keep_vec_names=TRUE) is a named vector. In a future version of jsonlite, this option will not be supported, and named vectors will be translated into arrays instead of objects. If you want JSON object output, please use a named list instead. See ?toJSON
> 
> I haven't explicitly used named vectors anywhere. Have used following shiny widgets in the module when this warning appears:
> 
> ` dateRangeInput`
> ` selectInput`
> Creating a min reprex for a shiny warning is a huge task but if there is any hint on what to check and where to look I can perhaps solve this without a full fledged issue or SO question.

I'm getting the same warning when running my shiny app (although mine is `...missing values (geom_bar)`). The only inputs I'm using in the app are `selectInput`s. I'm also doing an `updateSelectInput` on the server side. Given the reference to missing values in `geom...`, is this a shiny problem or maybe a ggplot problem?

**Comment by atakanekiz** [comment] 2020-04-23 22:08
I'm getting the same warning when I try to `updateSelectizeInput` by using an **unnamed** character vector (as a reactive object). I also tried converting reactive vector into a named `list` but it didn't help.

**Comment by earnaud** [comment] 2020-09-16 08:46
I tried to `as.list` the provided arguments to potential causes of this bug, but the messages still appear.
Couldn't it be possible to disable these messages? I tried to use `suppressMessage()` on my `updateSelectizeInput()` and any potential statement causing this: they still appear. 
This is driving me really mad as they are junk in my debug logs.

**Comment by wch** [comment] 2020-09-16 16:54
The warning is being issued by `jsonlite::asJSON` because something unexpected is being sent to it. Here's an example that illustrates. (Note that shiny calls `jsonlite::toJSON` with the arguments below.)

```R
x <- c(a=1, b=2)


# (1)
# Named vectors get turned into JS objects, but with a warning
#> a b 
#> 1 2
jsonlite::toJSON(x, keep_vec_names=TRUE, auto_unbox=TRUE)
#> Input to asJSON(keep_vec_names=TRUE) is a named vector. In a future version of jsonlite, this option will not be supported, and named vectors will be translated into arrays instead of objects. If you want JSON object output, please use a named list instead. See ?toJSON.
#> {"a":1,"b":2}


# (2)
# Unnamed vectors get turned into JS arrays
unname(x)
#> [1] 1 2
jsonlite::toJSON(unname(x), keep_vec_names=TRUE, auto_unbox=TRUE)
#> [1,2]


# (3)
# Named lists get turned into JS objects (without warning)
as.list(x)
#> $a
#> [1] 1
#> 
#> $b
#> [1] 2
jsonlite::toJSON(as.list(x), keep_vec_names=TRUE, auto_unbox=TRUE)
#> {"a":1,"b":2}
```

The warning shouldn't be ignored: it's telling you that in a future version of jsonlite, your code will no longer work as it does now. That is, if your code is currently behaving like (1), in the future it will behave like (2), and the wrong data will get sent to the web browser.

It you think there's a bug in Shiny, you can file a new issue, and please include a reproducible example: 
https://github.com/rstudio/shiny/wiki/Creating-a-Reproducible-Example

The `?updateSelectizeInput` page has a simple example to start with, if that helps.
