### ISSUE TITLE
ggvis plot disappears at random Shiny - possible bug in bind_shiny() 

### ISSUE THREAD

**Issue by Nicolabo** [rstudio/shiny#765] opened 2015-03-11 17:30 UTC
I have a strange problem in Shiny. I published the same question in stackoverflow.com and one guy named `numbercruncher` claims it refers to some bug in `bind_shiny`. But it is just an assumption.
http://stackoverflow.com/questions/28915921/ggvis-plot-disappears-at-random-shiny

 My shiny app has one ggvis plot with layer_points() and several options to manipulate the plot . When I run my app sometimes everything works good even if I change all options, but sometimes ( I suppose there is no specific rule) plot disappers. Plot comes back when I change one of options but it is not cool. I study this issue but I do not really know whether it is a solution for my problem. When the plot disappears my Shiny app looks like:

![zrzut ekranu 2015-03-11 o 18 15 10](https://cloud.githubusercontent.com/assets/5960799/6602585/aa72299e-c81c-11e4-802f-fdead9b18f9f.png)

Here you can find my code:
https://gist.github.com/Nicolabo/6b272cd9f1de9af8c81b

**Comment by alandipert** [comment] 2019-04-26 04:12
Sorry it took so long to respond, but thank you for bringing this to our attention. I updated your app to work on the latest Shiny, but I was not able to reproduce the issue. I'm using Shiny 1.3.2 and Firefox 66. I clicked around a lot and the plot never disappeared.

I'm closing this issue, but if you still have this problem please don't hesitate to open a new one.

Updated app:

```R
library(shiny)
library(ggvis)
library(markdown)
library(shiny)
library(dplyr)
library(magrittr)

choices <- list("Value1" = "AT1", "Value2" = "AT2",
                "Value3" = "AT3", "Value4" = "AT4",
                "Value5" = "AT5", "Value6" = "RT1",
                "Value7" = "AT6", "Value8" = "AT7",
                "Value9" = "AT8", "Value10" = "AT9",
                "Value11" = "AT10", "Value12" = "RT2")

levele <- c("AT1","AT2","AT3","AT4","AT5","RT1","AT6","AT7","AT8","AT9","AT10","RT2")

df1 <- data.frame(value = levele,number = seq(2,46,4), number2 = seq(2,24,2),order = 1:12) 

df2 <- data.frame(value = levele,number = rep(4:15), number2 = rep(4:9,each = 2),order = 1:12) 

df1$value <- factor(df1$value, levels = levele)
df2$value <- factor(df2$value, levels = levele)

axis_vars_y <- c("number","number2")
axis_vars_x <- c("value", "order","number","number2")

ui <- shinyUI(
  fluidPage(
    h3("Title"),
    fluidRow(
      column(3,
             wellPanel(
               radioButtons("radio",h5("Select"),choices=list("All values","Selected values"),
                            selected="All values"),
               
               conditionalPanel(
                 condition = "input.radio != 'All values'",
                 checkboxGroupInput("checkGroup",label = "",
                                    choices,
                                    selected = c("AT1","AT2"))
               ),
               hr(),
               radioButtons("dataset", label = h5("Drilldown"),
                            choices = list("2 Level" = "df1", "3 Level" = "df2")
                            
               ),
               hr(),
               h5("Choice"),
               selectInput("xvar", h6(""), 
                           axis_vars_x,
                           selected = "value"),
               selectInput("yvar", h6(""), 
                           axis_vars_y,
                           selected = "number2"),
               hr(),
               uiOutput("slider")
             )
      ),
      column(9,
             ggvisOutput("plot")
      )
    )
    
  )
)
server <- function(input, output,session) {
  datasetInput <- reactive({
    switch(input$dataset,
           df2 = df2,
           df1 = df1)
  })
  
  axis_vara_y <- reactive({
    switch(input$yvar,
           number = 2,
           number2 = 3)
  }) 
  
  
  output$slider <- renderUI({
    sliderInput("inslider",h5(""), min   = round(min(datasetInput()[,axis_vara_y()]),0)-1, 
                max   = round(max(datasetInput()[,axis_vara_y()]),0)+1,
                value = c(round(min(datasetInput()[,axis_vara_y()]),0)-1, 
                          round(max(datasetInput()[,axis_vara_y()]),0)+1),
                step  = 0.5)
  })
  
  data <- reactive({
    filteredData <- datasetInput()
    axisData <- axis_vara_y()
    
    if(!is.null(input$inslider)){
      if(input$radio == "All values"){
        filteredData <- filteredData %>%
          filter(filteredData[,axisData] >= input$inslider[1],
                 filteredData[,axisData] <= input$inslider[2])
      }
      else {
        filteredData <- filteredData %>%
          filter(value %in% input$checkGroup,
                 filteredData[,axisData] >= input$inslider[1],
                 filteredData[,axisData] <= input$inslider[2])
      }
    }
    return(filteredData)
  })  
  
  data_point <- reactive({
    data() %>%
      mutate(id = row_number())
    
  })
  
  xvar <- reactive(as.symbol(input$xvar))
  yvar <- reactive(as.symbol(input$yvar))
  
  dotpoint_vis <- reactive({
    
    xvar_name <- names(axis_vars_x)[axis_vars_x == input$xvar]
    yvar_name <- names(axis_vars_y)[axis_vars_y == input$yvar]
    
    
    data_point_detail <- data_point()
    
    plot <- data_point_detail %>%
      ggvis(x = xvar(),y =  yvar()) %>%
      layer_points(size := 120,fill = ~value) %>%
      add_axis("x", title = xvar_name) %>%
      add_axis("y", title = yvar_name) %>%
      set_options(width = 750, height = 500, renderer = "canvas") 
    
  })
  dotpoint_vis %>% bind_shiny("plot")
  
}

shinyApp(ui, server)
```

**Closed by alandipert** 2019-04-26 04:12 UTC
