### ISSUE TITLE
runDemo

### ISSUE THREAD

**Issue by hadley** [rstudio/shiny#212] opened 2013-08-14 16:08 UTC
It would be useful if shiny had a `runDemo` function like this:

``` R
runDemo <- function(package, demo, ...) {
  path <- system.file("demo", demo, package = package)
  if (path == "") stop("Couldn't find demo ", demo, " in ", package, call. = FALSE)

  runApp(path, ...)
}
```

then you could easily run demos in installed packages:

``` R
runDemo("apps/basic", "gigvis")
```

That might almost be a better way to implement `runExample()`:

``` R
runExample <- function(example, ...) runApp("shiny", example, ...)
```

although then you'd have to move the existing examples into the demo directory - this would be a good idea because it's fits the R package conventions a little better, and reduces the confusion between `runExample()` and `example()`

**Comment by dougmet** [comment] 2016-03-02 11:58
Found this just before posting a similar issue. I think it would be nice to add a `package` argument to `runExample`. This would turn the following line:

```r
shiny::runApp(system.file("shiny-examples", "basic", package="radarchart"))
```
into
```r
shiny::runExample("basic", package="radarchart")
```

Happy to submit a PR if there's interest. The main thing is to agree on a standard directory to keep shiny examples. Here I've used `shiny-examples`, similar to [this post](http://deanattali.com/2015/04/21/r-package-shiny-app/) but some use `examples` some use `demo`.

For me the name isn't important, but having this function as part of shiny would be a great way to encourage consistency.

**Comment by 0tertra** [comment] 2016-11-08 15:26
already added a pull request for this before looking into the issues. 
You can find the request here [#1458](https://github.com/rstudio/shiny/pull/1458)

**Comment by alandipert** [comment] 2019-04-23 22:40
Closing because dupe of #1458

**Closed by alandipert** 2019-04-23 22:40 UTC
