### ISSUE TITLE
Issue with "hidden error" when using eventReactive

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#1125] opened 2016-03-04 13:17 UTC
I'm not exactly sure how `eventReactive()` works internally so my diagnosis might not be correct.

It seems that when a reactive context tries to get the value of a reactive value that's defined with a `eventReactive()`, the first time it's called (ie. before the variable gets an initial value) a silent error is thrown with no text.

Explanation:

Here's a simple app that assigns the value of a button into the `foo` reactive using `eventReactive`, and there's also a textOutput that just displays static text

```
ui <- fluidPage(
  actionButton("btn", "Button"),
  textOutput("text")
)

server <- function(input, output, session) {
  foo <- eventReactive(input$btn, input$btn)
  
  output$text <- renderText({
    "hello"
  })
}

shinyApp(ui = ui, server = server)
```

As expected, the app shows a "hello" message.

Now, add a `cat(foo())` just before returning "hello".  Now when you run the app, "hello" doesn't show up until after the button gets pressed, because before that the `cat(foo())` statement results in a "silent" error.  When I put a `browser()` there to inspect the value of `foo()`, I just got `Error:` without any text for the error.

Sorry this was not very well explained, I blame it on the fact that it's past 5am...

**Comment by wch** [comment] 2016-07-27 18:12
With this test app, when I run `foo()` at the browser prompt, it gets in some sort of loop that prints out `Error:` over and over again.

```R
ui <- fluidPage(
  actionButton("btn", "Button"),
  textOutput("text")
)

server <- function(input, output, session) {
  foo <- eventReactive(input$btn, input$btn)

  output$text <- renderText({
    browser()
    "hello"
  })
}

shinyApp(ui = ui, server = server)
```


Here's what it does:

```
Called from: renderText(...)
Browse[1]> foo()
Error: 
Error: 
Error: 
Error: 
Error: 
Error: 
Error: 
Error: 
Error: 
Error: 
```

**Comment by jcheng5** [comment] 2016-08-10 21:17
> It seems that when a reactive context tries to get the value of a reactive value that's defined with a eventReactive(), the first time it's called (ie. before the variable gets an initial value) a silent error is thrown with no text.

That's right, this is as intended. By default, if `input$btn` is `NULL` or an unclicked action button, the eventReactive is considered to be missing a prerequisite (`req(input$btn)`, more or less). This is what we want if the button says, e.g., "Submit" or "Calculate".

If that's not what you want, e.g. the button is something like "Refresh", "Recalculate", or "Update", then pass `ignoreNULL = FALSE` when calling `eventReactive()`.

> it gets in some sort of loop that prints out Error: over and over again

Now _that_ is unexpected...

**Comment by jcheng5** [comment] 2016-08-10 22:23
Winston, I can't reproduce. If you can't either, can you close this?

**Comment by bborgesr** [comment] 2016-08-11 00:44
I get the same as Winston, @jcheng5:

![screen shot 2016-08-11 at 1 41 51 am](https://cloud.githubusercontent.com/assets/6527540/17575857/d7c21efa-5f64-11e6-93fa-341562956b94.png)

Where you running Winston's code or Dean's? The issue with Winston's is the `browser()` statement. If you just run the app, disregard the window that pops up and type `foo()` at the browsing prompt, you get the error on a loop...

**Comment by jcheng5** [comment] 2016-08-11 00:52
@bborgesr I was trying with Winston's code, doing just what you said. Can you try it after installing from master, and a restart of R?

**Comment by jcheng5** [comment] 2016-08-11 00:54
(I just get a single `Error:`, not many.)

**Comment by bborgesr** [comment] 2016-08-11 00:58
Installed from master and restarted R, and I still get exactly the same thing... :/ Will try from my Windows VM

**Comment by wch** [comment] 2016-08-11 02:21
```
> devtools::session_info()
Session info ---------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.0 (2016-05-03)
 system   x86_64, darwin13.4.0        
 ui       RStudio (0.99.1281)         
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/Chicago             
 date     2016-08-10                  

Packages -------------------------------------------------------------------------------
 package   * version     date       source                          
 devtools    1.12.0.9000 2016-07-22 Github (hadley/devtools@5cd2d80)
 digest      0.6.10      2016-08-02 cran (@0.6.10)                  
 htmltools   0.3.5       2016-03-21 CRAN (R 3.3.0)                  
 httpuv      1.3.3       2015-08-04 CRAN (R 3.3.0)                  
 memoise     1.0.0       2016-01-29 CRAN (R 3.3.0)                  
 mime        0.5         2016-07-07 CRAN (R 3.3.0)                  
 R6          2.1.2       2016-01-26 CRAN (R 3.3.0)                  
 Rcpp        0.12.6      2016-07-19 CRAN (R 3.3.0)                  
 shiny     * 0.13.2.9005 2016-08-11 Github (rstudio/shiny@d1e4483)  
 withr       1.0.2       2016-06-20 CRAN (R 3.3.0)                  
 xtable      1.8-2       2016-02-05 CRAN (R 3.3.0)                  
```

**Comment by bborgesr** [comment] 2016-08-11 02:30
This is driving me a bit insane, but FWT, I get the exact same problem with a regular reactive that uses `req(input$btn)`:

```r
ui <- fluidPage(
  actionButton("btn", "Button"),
  textOutput("text")
)

server <- function(input, output, session) {
  
  foo <- reactive({
    req(input$btn)
    "bye"
  })
  
  output$text <- renderText({
    browser()
    "hello"
  })
}

shinyApp(ui = ui, server = server)
```

**Comment by bborgesr** [comment] 2016-08-11 04:05
I suspect the error is somewhere here: https://github.com/rstudio/shiny/blob/master/R/reactives.R#L523. Also the explanation for the error handling mechanism in that function ([here](https://github.com/rstudio/shiny/blob/master/R/reactives.R#L547)) is outdated...

**Comment by jcheng5** [comment] 2016-08-12 03:02
The repeating error only repros on R 3.3, not R 3.2 😱

**Comment by daattali** [comment] 2016-08-12 03:03
That's terrifying!

**Comment by jcheng5** [comment] 2016-08-12 04:07
Minimal repro (not involving Shiny):

```r
breakme <- function() {
  on.exit({})
  stop()
}
browser()
```

**Comment by jcheng5** [comment] 2016-08-12 06:20
Bisected to this change:
https://github.com/wch/r-source/commit/3031b676d1fc644f98da24196b9b5e62df58d36c

**Comment by jcheng5** [comment] 2016-08-12 06:23
Similar repro:

```r
breakme <- function() {
  tryCatch(
    stop(),
    finally = {}
  )
}
browser()
```

**Comment by kevinushey** [comment] 2016-08-12 06:35
FWIW, I can't repro with a recent R 3.3.1 patched:

```
> sessionInfo()
R version 3.3.1 Patched (2016-07-30 r71015)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X El Capitan (10.11.6)
```

Is there any other state that's necessary here, or is it possible this is fixed in the latest versions of R?

**Comment by jcheng5** [comment] 2016-08-12 07:19
No repro on current R-devel! Great!

@wch @bborgesr Can we close the issue?

**Comment by wch** [comment] 2016-08-12 14:19
Nice sleuthing!

**Closed by wch** 2016-08-12 14:19 UTC
Labels: P1, targeted

**Comment by daattali** [comment] 2017-02-12 21:26
@wch @jcheng5 may I raise this issue again? I recently helped two different people who have very large shiny apps, I had to debug why their reactives were broken and weren't functioning as expected. In both cases it turned out to be that this issue was the cause. It was worse than my silly little minimal example - charts were not plotting at all because they were relying on an eventReactive that "errored" initially. Doesn't feel like correct behaviour to me to get a silent error when trying to access a value

**Comment by bborgesr** [comment] 2017-02-14 04:38
@daattali: re 
> Doesn't feel like correct behaviour to me to get a silent error when trying to access a value

maybe that's true, maybe it's not.. - we've discussed among us whether or not the default behavior of `ignoreNULL` is correct... For better or worse, `ignoreNULL = TRUE` is the default and we can't go back and change that. (We can't even go back and start printing a message for the situations you describe, because for the people that do want this behavior, that would be terrible; and, in general, we're very conservative when it comes to backward compatibility...) The most we could do is bring people's attention to it more during workshops/webinars...  We *could* add an article directly about this, but it would largely be reciting the documentation (which is one of the most extensive pieces of documentation we have for an argument to a function)... And  it wouldn't change the fact that you'd have to be looking for this info in order to get it. There's just no way that we can introduce this subtlety at the same time people are learning about reactives (or even `eventReactive`s) for the first time... I've copy-pasted the relevant doc sections below. Also, `ignoreInit` is a pretty recent argument (but documented together) and your statement 
> because they were relying on an eventReactive that "errored" initially

especially the "initially" part, makes me wonder if this wouldn't even be better suited for your purposes... - although this is only valid for `observeEvent` (not for `eventReactive`)... (I'm also including the description and example for `once`, given that it is also a recently added argument and that it is somewhat related to this discussion - pretty much the mirror opposite of what you seemed to need for your situations; also, only applies to `observeEvent`..):

**Arguments description:**
> `ignoreNULL`	
> Whether the action should be triggered (or value calculated, in the case of eventReactive) when the input is NULL. See Details.
>
> `ignoreInit`	
> If TRUE, then, when this observeEvent is first created/initialized, ignore the handlerExpr (the second argument), whether it is otherwise supposed to run or not. The default is FALSE. See Details.
>
> `once`	
> Whether this observeEvent should be immediately destroyed after the first time that the code in handlerExpr is run. This pattern is useful when you want to subscribe to a event that should only happen once.

**Details:**
> ***ignoreNULL and ignoreInit***
>
> Both observeEvent and eventReactive take an ignoreNULL parameter that affects behavior when the eventExpr evaluates to NULL (or in the special case of an actionButton, 0). In these cases, if ignoreNULL is TRUE, then an observeEvent will not execute and an eventReactive will raise a silent validation error. This is useful behavior if you don't want to do the action or calculation when your app first starts, but wait for the user to initiate the action first (like a "Submit" button); whereas ignoreNULL=FALSE is desirable if you want to initially perform the action/calculation and just let the user re-initiate it (like a "Recalculate" button).
>
> Unlike what happens for ignoreNULL, only observeEvent takes in an ignoreInit argument. By default, observeEvent will run right when it is created (except if, at that moment, eventExpr evaluates to NULL and ignoreNULL is TRUE). But when responding to a click of an action button, it may often be useful to set ignoreInit to TRUE. For example, if you're setting up an observeEvent for a dynamically created button, then ignoreInit = TRUE will guarantee that the action (in handlerExpr) will only be triggered when the button is actually clicked, instead of also being triggered when it is created/initialized.
>
> Even though ignoreNULL and ignoreInit can be used for similar purposes they are independent from one another. Here's the result of combining these:
>
> `ignoreNULL = TRUE` and `ignoreInit = FALSE`
> This is the default. This combination means that handlerExpr will run every time that eventExpr is not NULL. If, at the time of the observeEvent's creation, handleExpr happens to not be NULL, then the code runs.
>
> `ignoreNULL = FALSE` and `ignoreInit = FALSE`
> This combination means that handlerExpr will run every time no matter what.
>
> `ignoreNULL = FALSE` and `ignoreInit = TRUE`
> This combination means that handlerExpr will not run when the observeEvent is created (because ignoreInit = TRUE), but it will run every other time.
>
> `ignoreNULL = TRUE` and `ignoreInit = TRUE`
> This combination means that handlerExpr will not run when the observeEvent is created (because ignoreInit = TRUE). After that, handlerExpr will run every time that eventExpr is not NULL.

**Examples:**
> ...
> ```r
>  ## App 2: Using `once`
>  shinyApp(
>    ui = basicPage( actionButton("go", "Go")),
>    server = function(input, output, session) {
>      observeEvent(input$go, {
>        print(paste("This will only be printed once; all",
>              "subsequent button clicks won't do anything"))
>      }, once = TRUE)
>    }
>  )
>
>  ## App 3: Using `ignoreInit` and `once`
>  shinyApp(
>    ui = basicPage(actionButton("go", "Go")),
>    server = function(input, output, session) {
>      observeEvent(input$go, {
>        insertUI("#go", "afterEnd",
>                 actionButton("dynamic", "click to remove"))
>
>        # set up an observer that depends on the dynamic
>        # input, so that it doesn't run when the input is
>        # created, and only runs once after that (since
>        # the side effect is remove the input from the DOM)
>        observeEvent(input$dynamic, {
>          removeUI("#dynamic")
>        }, ignoreInit = TRUE, once = TRUE)
>      })
>    }
>  )
> ```

Feel free to share your thoughts if you think I didn't answer your concern sufficiently...

**Comment by daattali** [comment] 2017-02-14 07:26
Answered very sufficiently, thank you @bborgesr
