### ISSUE TITLE
Bookmarking bug: only the last `setBookmarkExclude()` is honoured, all previous excludes are ignored 

### ISSUE THREAD

**Issue by daattali** [rstudio/shiny#2971] opened 2020-07-16 04:35 UTC
When calling `setBookmarkExclude()` multiple times, only the last call actually excludes the given inputs. 

Example: There are 4 inputs in the app below, which are being excluded in two separate calls. When the bookmark button is clicked, the excluded inputs are printed, and you can see it's only the inputs from the last call.

```
library(shiny)

ui <- function(req) {
  fluidPage(
    bookmarkButton(),
    textInput("test1", "test1", "test1"),
    textInput("test2", "test2", "test2"),
    textInput("test3", "test3", "test3"),
    textInput("test4", "test4", "test4")
  )
}

server <- function(input, output, session) {
  setBookmarkExclude(c("test1", "test2"))
  setBookmarkExclude(c("test3", "test4"))
  
  onBookmark(function(state) {
    message(state$exclude)
  })
}

shinyApp(ui, server, enableBookmarking = "url")
```

I think it's because in [this line](https://github.com/rstudio/shiny/blob/8ec6275f9a49b5b6d5a307febaaf5bee8086c99a/R/shiny.R#L1476) the excluded inputs are being assigned/overrided instead of appended to a list. Is there a reason they can't be appended instead of overridden?

**Comment by jcheng5** [comment] 2020-07-28 18:20
This has caught me out as well. I think for now we'd need to use an `add = TRUE` like `on.exit`, but here's another case for shiny editions to let us change the default behavior in the future...

**Comment by jcheng5** [comment] 2020-07-28 18:21
LOL, dupe of your own issue #2323

**Closed by jcheng5** 2020-07-28 18:21 UTC

**Comment by daattali** [comment] 2020-07-28 18:22
Whoops :p My github issue searching skills are much weaker than my googling skills....
