### ISSUE TITLE
plotly not working for multiple plots in shiny

### ISSUE THREAD

**Issue by pranithkumar** [rstudio/shiny#1744] opened 2017-06-14 12:15 UTC
This is the code:
#ui.R

shinyUI(fluidPage(
  
  titlePanel("Sample App"),
  sidebarLayout(
    sidebarPanel(
      selectInput("select", label = h3("Select"), 
                  choices = list("1"," 2"))
    ),
    mainPanel(
       plotlyOutput("distPlot")
    )
  )
))

#server.R

library(plotly)
shinyServer(function(input, output) {
   
  output$distPlot <- renderPlotly({
    if(input$select=="1"){
      x <- c('Product A', 'Product B', 'Product C')
      y <- c(20, 14, 23)
      text <- c('27% market share', '24% market share', '19% market share')
      data <- data.frame(x, y, text)
      
      p <- plot_ly(data, x = ~x, y = ~y, type = 'bar', text = text,
                   marker = list(color = 'rgb(158,202,225)',
                                 line = list(color = 'rgb(8,48,107)',
                                             width = 1.5))) %>%
        layout(title = "January 2013 Sales Report",
               xaxis = list(title = ""),
               yaxis = list(title = ""))
      p
    }
    else if(input$select=="2")
    {
      q <- plot_ly(
        x = c("giraffes", "orangutans", "monkeys"),
        y = c(20, 14, 23),
        name = "SF Zoo",
        type = "bar"
      )
      q
    }
  })
  
})

Both the plots are displayed seperately but when the user input changes to second plot it gives an error.
Warning: Error in UseMethod: no applicable method for 'ggplotly' applied to an object of class "NULL"
Stack trace (innermost first):
    79: "plotly"::"ggplotly"
    78: func
    77: origRenderFunc
    76: output$distPlot
     1: runApp

**Comment by ChrisMuir** [comment] 2017-06-19 14:42
Think this is related to plotly, check it:

https://github.com/ropensci/plotly/issues/1032

Found while searching for answers to my own plotly/shiny issues.

**Comment by pranithkumar** [comment] 2017-06-20 18:54
Thank you I checked the issue 
ropensci/plotly#1032
My problem was solved when I used switch instead of if else statement.
But I still don't understand why if else is not working.

**Comment by alandipert** [comment] 2019-05-08 22:11
@pranithkumar I think the problem is that your reactive expression can return `NULL` if neither `input$select=="1"` nor `input$select=="2"` are true.

I'm closing because this isn't an inherent issue with Shiny and your problem seems to have been resolved, but please don't hesitate to comment further or create a new issue if I misunderstand.

**Closed by alandipert** 2019-05-08 22:11 UTC
