### ISSUE TITLE
ggplot and renderPlot in IE8 not displaying plot. Works in other browsers

### ISSUE THREAD

**Issue by Marccohen** [rstudio/shiny#616] opened 2014-10-13 17:05 UTC
Title says it all. The application works in chrome and firefox and more current IE versions. 

RStudio folks say this is not a server problem but appears to be a problem with the shiny package. 

Thanks

**Comment by yihui** [comment] 2015-01-06 19:44
Closing this issue, since there were no more follow-ups after a few rounds of private emails.

**Comment by Marccohen** [comment] 2015-01-16 17:56
I've put together a small example that does not work for us on:

Environment 1


-Windows XP Professional Build 2600.xpsp_sp3_gdr.080814-1236 Service Pack 3

-Browser Internet Explorer Version 8.0.600.1872

- Tried on three modes: IE7, IE8 , IE8 compatibility view



Environment 2

-Windows XP Professional Build 2600.xpsp_sp3_qfe.101209-1646 Service Pack 3

-Browser Internet Explorer Version: 8.600.1872

-Tried on three modes: IE7, IE8 , IE8 compatibility View


Thanks for looking into this,


Marc

On Tue, Jan 6, 2015 at 2:44 PM, Yihui Xie <notifications@github.com> wrote:

> Closed #616 <https://github.com/rstudio/shiny/issues/616>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rstudio/shiny/issues/616#event-214883374>.
>



-- 

Marc-david Cohen  |  Chief Science Officer |  +1.415.205.6295  |
www.aktana.com

**Comment by alandipert** [comment] 2019-04-23 23:04
@Marccohen I know it's been a really long time, but is this still a problem for you? If not, would you consider closing this issue? Thank you.

**Comment by alandipert** [comment] 2019-04-25 20:05
I realized that IE 8 hasn't been supported by Microsoft since 2016, and I know that we haven't tested against it since at least then, so I'm going to close this issue.

And, as far as I know, we were never able to reproduce.

Please don't hesitate to create a new issue if this is still a problem.

**Closed by alandipert** 2019-04-25 20:05 UTC
