### ISSUE TITLE
suspendWhenHidden = FALSE is not working in Firefox

### ISSUE THREAD

**Issue by ppagnone** [rstudio/shiny#1535] opened 2017-01-13 15:32 UTC
Hi all, I am working in a interface with a shinyBS modal with a datatable inside. I have a button "select my groups" that can select some rows in the table even if this is hidden.

I added  suspendWhenHidden = FALSE for this, and is working well in Chrome, but in Firefox this is not working when I load the page(the table and modal is hidden), I click on button "showmygroups" and I have the following error:
"Couldn't find table with id activity-groupslist     jquery.... > eval (line 911)"

If I previously showed the modal/table with the other button(selectgroup), later the button "showmygroups" work correctly.

Some idea ? Maybe is related to #1409 ?
Thanks in advance

UI
``` 
library(shiny)
library(dplyr)
library(DT)
library(shinyBS)
shinyUI(
  uiOutput("main")
)
```
Server:
``` 
shinyServer(function(input, output,session) {
  
  output$main <- renderUI({
    
      callModule(activityServer,"activity")
      fixedPage(
        activityUI("activity")
      )
  })
})
```

Module:
``` 
activityUI <- function(id){
  ns <- NS(id)
  fixedPage(
    fluidRow(
      column(12,
             bsModal(ns("bs"),
                     "Group Selection",ns("selectgroup"),
                     DT::dataTableOutput(ns("groupslist")),
                     div(textOutput(ns("groupsSelected2")))),
             actionButton(ns("showmygroups"), 
                          "Show my groups only"),
             actionButton(ns("selectgroup"),
                          "Select Groups"),
             actionButton(ns("reset"),
                          "Reset"),
             column(12,
                    textOutput(ns("groupsSelected"))
             )
      )
    )
  )
}

activityServer <- function(input,output,session){
  
  groups <- data.frame(c("1","2"),c("group1","group2"))
  groups <- setNames(groups,c("id","name"))
  
  output$groupslist <- DT::renderDataTable(groups %>% select(name), 
                                           options = c(list(order=list(0, 'asc'))),
                                           filter = "bottom",
                                           rownames = FALSE,
                                           selection = 'multiple')
  
  outputOptions(output, "groupslist", suspendWhenHidden = FALSE)
  
  output$groupsSelected <- renderText({
    
    if(is.null(input$groupslist_rows_selected)) {
      ret <- "All"
    } else {
      g <- groups[input$groupslist_rows_selected,]
      ret <- paste(g$name)
    }
    
    paste("Selected Groups: ",a <- paste(ret, collapse = " / "),".")
  })
  
  observeEvent(input$reset,{
    DT::dataTableProxy(session$ns("groupslist")) %>% selectRows(NULL)
  })
  
  observeEvent(input$showmygroups, {
    DT::dataTableProxy(session$ns("groupslist")) %>% selectRows(c(1))
  })
}
```

**Comment by bborgesr** [comment] 2017-01-16 02:11
Could you give us a minimal reproducible example?

**Comment by ppagnone** [comment] 2017-01-16 04:56
Hi @bborgesr,  thank you for your time , I updated my comment and uploaded my current structure working with module (this is working well in chrome but not in firefox).

I also checked without modules, with this code:
```
library(shiny)
library(shinyBS)
library(dplyr)
library(DT)
shinyUI <- function(id) {
  fixedPage(
    fluidRow(
      column(12,
             bsModal("bs",
                     "Group Selection","selectgroup",
                     DT::dataTableOutput("groupslist"),
                     div(textOutput("groupsSelected2"))),
             actionButton("showmygroups", 
                          "Show my groups only"),
             actionButton("selectgroup",
                          "Select Groups"),
             actionButton("reset",
                          "Reset"),
             column(12,
                    textOutput("groupsSelected")
             )
      )
    )
  )
}

shinyServer <- function(input,output,session){
  
  groups <- data.frame(c("1","2"),c("group1","group2"))
  groups <- setNames(groups,c("id","name"))
  
  output$groupslist <- DT::renderDataTable(groups %>% select(name), 
                                           options = c(list(order=list(0, 'asc'))),
                                           filter = "bottom",
                                           rownames = FALSE,
                                           selection = 'multiple')
  
  outputOptions(output, "groupslist", suspendWhenHidden = FALSE)
  
  output$groupsSelected <- renderText({
    
    if(is.null(input$groupslist_rows_selected)) {
      ret <- "All"
    } else {
      g <- groups[input$groupslist_rows_selected,]
      ret <- paste(g$name)
    }
    
    paste("Selected Groups: ",a <- paste(ret, collapse = " / "),".")
  })
  
  observeEvent(input$reset,{
    DT::dataTableProxy("groupslist") %>% selectRows(NULL)
  })
  
  observeEvent(input$showmygroups, {
    DT::dataTableProxy("groupslist") %>% selectRows(c(1,2))
  })
}

shinyApp(shinyUI, shinyServer)
```

But this second case is not working in some browser, except if you click first in "select group" button, there the button "Show my groups.." will work.

What do you think? Am I doing something wrong in my code?
Thanks in advance

**Comment by bborgesr** [comment] 2017-01-16 05:44
Wonderful, thanks! I can reproduce your error now. Let me investigate and I'll get back to you.

**Comment by ppagnone** [comment] 2017-01-16 18:24
Thank you @bborgesr , I found the following posts:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/shiny-discuss/4E61F-tvGR4/p2B8hYp6AQAJ

https://groups.google.com/forum/#!topic/shiny-discuss/2_06PCpAP8U

This seem to be related to them. I will try to add the trigger with js and I will add comment if that resolve this problem.

**Comment by alandipert** [comment] 2019-05-01 19:08
I was able to reproduce this both in Firefox 66 and Chrome 74 with Shiny 1.3.2 and DT 0.5.

Closing because I believe it's a duplicate of #1364.

**Closed by alandipert** 2019-05-01 19:08 UTC
Labels: Difficulty: Advanced, Type: Bug :bug:
