### ISSUE TITLE
Issue in generating ppt animation using “Generate PPT Animation” button

### ISSUE THREAD

**Issue by somaghosh1** [rstudio/shiny#3150] opened 2020-11-17 17:23 UTC
Hi,
I have launched GWSDAT from Shinyapps.io. I'm facing one issue while generating  ppt animation using “Generate PPT Animation” button. PPT animation generation failed. I'm using local machine. 

I'm pasting the log file below. Please help to resolve.

Log file:

2020-11-17T13:04:06.048361+00:00 shinyapps[2907608]: Running on host: 53564a9c1321
2020-11-17T13:04:06.054323+00:00 shinyapps[2907608]: Server version: 1.8.4.1-20
2020-11-17T13:04:06.054333+00:00 shinyapps[2907608]: LANG: en_US.UTF-8
2020-11-17T13:04:06.054334+00:00 shinyapps[2907608]: R version: 4.0.2
2020-11-17T13:04:06.054334+00:00 shinyapps[2907608]: shiny version: 1.5.0
2020-11-17T13:04:06.243453+00:00 shinyapps[2907608]: Starting R with process ID: '26'
2020-11-17T13:04:06.054334+00:00 shinyapps[2907608]: httpuv version: 1.5.4
2020-11-17T13:04:06.054341+00:00 shinyapps[2907608]: rmarkdown version: (none)
2020-11-17T13:04:06.054405+00:00 shinyapps[2907608]: jsonlite version: 1.7.1
2020-11-17T13:04:06.054397+00:00 shinyapps[2907608]: knitr version: (none)
2020-11-17T13:04:06.054405+00:00 shinyapps[2907608]: RJSONIO version: (none)
2020-11-17T13:04:06.054406+00:00 shinyapps[2907608]: htmltools version: 0.5.0
2020-11-17T13:04:06.054549+00:00 shinyapps[2907608]: Using pandoc: /opt/connect/ext/pandoc2
2020-11-17T13:04:06.243453+00:00 shinyapps[2907608]: 
2020-11-17T13:04:06.240146+00:00 shinyapps[2907608]: Using jsonlite for JSON processing
2020-11-17T13:04:07.573184+00:00 shinyapps[2907608]: 
2020-11-17T13:04:07.572340+00:00 shinyapps[2907608]: 
2020-11-17T13:04:07.445127+00:00 shinyapps[2907608]: Warning: no DISPLAY variable so Tk is not available
2020-11-17T13:04:07.572342+00:00 shinyapps[2907608]: Attaching package: ‘shinyjs’
2020-11-17T13:04:07.572343+00:00 shinyapps[2907608]: 
2020-11-17T13:04:07.573183+00:00 shinyapps[2907608]: The following object is masked from ‘package:shiny’:
2020-11-17T13:04:07.606490+00:00 shinyapps[2907608]: Listening on http://127.0.0.1:39916
2020-11-17T13:04:07.595774+00:00 shinyapps[2907608]:   file("") only supports open = "w+" and open = "w+b": using the former
2020-11-17T13:04:07.606489+00:00 shinyapps[2907608]: 
2020-11-17T13:04:07.573185+00:00 shinyapps[2907608]: 
2020-11-17T13:04:07.573572+00:00 shinyapps[2907608]: 
2020-11-17T13:04:07.573185+00:00 shinyapps[2907608]:     runExample
2020-11-17T13:04:07.573571+00:00 shinyapps[2907608]: The following objects are masked from ‘package:methods’:
2020-11-17T13:04:07.573573+00:00 shinyapps[2907608]:     removeClass, show
2020-11-17T13:04:07.573573+00:00 shinyapps[2907608]: 
2020-11-17T13:04:07.595772+00:00 shinyapps[2907608]: Warning in file(con, "r") :
2020-11-17T13:04:20.920488+00:00 shinyapps[2907608]: * entering image_plot()
2020-11-17T13:04:21.000644+00:00 shinyapps[2907608]: [1] "in plotFilledContour"
2020-11-17T13:04:21.001265+00:00 shinyapps[2907608]: [1] 2.0 1.0 2.0 4.1
2020-11-17T13:04:25.437672+00:00 shinyapps[2907608]: [1] "in plotFilledContour"
2020-11-17T13:04:25.438020+00:00 shinyapps[2907608]: [1] 2.0 1.0 2.0 4.1
2020-11-17T13:04:25.500186+00:00 shinyapps[2907608]: Warning: Error in : 'ph_with_img' is defunct.
2020-11-17T13:04:25.500188+00:00 shinyapps[2907608]: Use 'ph_with' instead.
2020-11-17T13:04:25.500189+00:00 shinyapps[2907608]: See help("Defunct")
2020-11-17T13:04:25.505164+00:00 shinyapps[2907608]:   [No stack trace available]

**Comment by cpsievert** [comment] 2020-12-21 18:30
> I have launched GWSDAT from Shinyapps.io.

I'm not sure what this means. Could you be more specific?

Without a reproducible example, it's going to be very difficult to provide any help. I'm closing since it's very likely this is not a shiny issue but rather an issue with some other R package.

**Closed by cpsievert** 2020-12-21 18:30 UTC
