### ISSUE TITLE
plot brushing is not selecting correct points in Edge

### ISSUE THREAD

**Issue by bborgesr** [rstudio/shiny#1639] opened 2017-03-30 02:31 UTC
For example, this app (https://winston.shinyapps.io/108-module-output/):

![screen shot 2017-03-30 at 3 29 12 am](https://cloud.githubusercontent.com/assets/6527540/24484984/31b2805e-14f9-11e7-94dc-bf0a03d57ea2.png)

**Comment by bborgesr** [comment] 2017-03-30 04:47
Even though I noticed this being a lot worse in Edge, there's also some plot brushing difficulties in Safari (there might be more, haven't tested other browsers):

![screen shot 2017-03-30 at 5 46 11 am](https://cloud.githubusercontent.com/assets/6527540/24488089/688a2e3e-150c-11e7-8f2f-53dae72de55e.png)

**Comment by wch** [comment] 2017-03-30 13:44
Regarding Safari, I think that it's working correctly, and the behavior is the same in Chrome. By default, ggplot adds a little space around the x and y limits that are requested. If the example were to use `coord_cartesian(expand=FALSE)`, then it wouldn't add the extra space. I'll modify the example to do that.

**Comment by wch** [comment] 2017-03-30 13:54
I'm not able to reproduce the behavior on Edge. Is it always shifted like that?

**Comment by bborgesr** [comment] 2017-03-30 13:58
@wch: phew, glad at least one of these isn't a bug. As for Edge, hmm, it always seemed shifted for me. I can show you when we talk today

**Comment by bborgesr** [comment] 2017-03-30 20:10
*Notes from out chat today:*
As for the problem with Edge, that's due to the app being in showcase mode which affects the zoom level of the plots. Since the brushing does not take into account zoom level, it seems off. We could try to take that into account in the code, but that's risky and there's a lot of edge cases... So, we're mulling this over. Not important for this release.

**Comment by alandipert** [comment] 2019-05-08 20:00
Closing because couldn't repro with Edge 44.17763.1.0

**Closed by alandipert** 2019-05-08 20:00 UTC
Labels: Difficulty: Advanced, Effort: High, Feature: Showcase Mode, Needs Repro, Priority: Low
