### ISSUE TITLE
Conditional Panel + Plot Resizing Bug

### ISSUE THREAD

**Issue by trestletech** [rstudio/shiny#426] opened 2014-03-25 16:47 UTC
When the sidebarPanel has a conditionalPanel and the mainPanel has a plot, the width of the plot can be altered on update. We found this when interacting with an application that had some fairly expensive image creation code, resulting in the plot "flickering" a few times when inputs were changed or the window was resized.

We've found this issue on Firefox (Linux and Windows), though I don't see it in WebKit. 

Demo here: https://gist.github.com/trestletech/9765992 

Steps to reproduce:
 1. runApp()
 2. Open in Firefox
 3. Resize window. You should notice an initial 1 second delay while the histogram loads (expected), then another 1 second delay before loading a new histogram (unexpected).

Based on a quick glance at the reactivity log, I think the plot's width is being altered by a few pixels when the conditionalPanel fires its `show` method. Then when it updates again, there's a chance that it would be again altered, resulting in potentially many flickers.

**Comment by wch** [comment] 2015-01-21 22:26
I'm not able to reproduce this with Shiny 0.11 in Firefox on Linux. It's possible this was fixed by the change to Bootstrap 3.

Here's the example app in cut-and-pasteable form:

```R

library(shiny)
 
server <- function(input, output) {
   
  output$distPlot <- renderPlot({
    print("Plotting");
    Sys.sleep(1)
    # generate and plot an rnorm distribution with the requested
    # number of observations
    dist <- rnorm(input$obs)
    hist(dist)
  })
  
  output$content <- renderTable({
    data.frame(a=1:3, b=2:4)
  })
}

ui<- pageWithSidebar(
  # Application title
  headerPanel("New Application"),
  
  # Sidebar with a slider input for number of observations
  sidebarPanel(
    conditionalPanel("1 == 1",
      sliderInput("obs", 
                "Number of observations:", 
                min = 1, 
                max = 1000, 
                value = 500))
  ),
  
  # Show a plot of the generated distribution
  mainPanel(
    tabsetPanel(
      tabPanel("Tab1", 
               plotOutput("distPlot")
      )
    )
  )
)

shinyApp(ui, server)
```

**Comment by wch** [comment] 2015-03-04 22:05
I'm not able to reproduce this bug with Shiny 0.11.1. Regarding @jcheng5's comment about the differing sizes of the img and wrapper div: those now seem to have the exact same sizes, at least in my version of Firefox (35.0.1, Mac).

I'm going to close now; if anyone can reproduce the problem, please feel free to re-open.

**Closed by wch** 2015-03-04 22:05 UTC
Labels: bug
