### ISSUE TITLE
Interaction between shiny and Rcpp's RNGScope

### ISSUE THREAD

**Issue by asardaes** [rstudio/shiny#1953] opened 2018-02-23 15:46 UTC
I saw in #1763 that there were some problems with this before, and I'm having the following problem:

```r
library(Rcpp)
library(shiny)

code <- '
#include <Rcpp.h>

// [[Rcpp::export]]
Rcpp::NumericVector rng() {
    Rcpp::NumericVector ret(2);
    ret[0] = R::runif(1,10);
    ret[1] = R::runif(1,10);
    return ret;
}
'

sourceCpp(code = code, verbose = TRUE)

seed1 <- .Random.seed
invisible(rng())
seed2 <- .Random.seed
identical(seed1, seed2) # FALSE

shiny::runApp(shiny::shinyApp(
    ui = fluidPage(
        sidebarLayout(
            sidebarPanel(
                h1("Test")
            ),
            mainPanel(
                h1("Test")
            )
        )
    ),
    server = function(input, output, session) {
        seed1 <- .Random.seed
        invisible(rng())
        seed2 <- .Random.seed
        cat("same seeds? ", identical(seed1, seed2), "\n") # TRUE gets printed
    }
))
```

Within the app, the random state doesn't get updated.

-----

R session info:
```
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_1.0.5  Rcpp_0.12.15

loaded via a namespace (and not attached):
 [1] compiler_3.4.3  R6_2.2.2        rsconnect_0.8.5 htmltools_0.3.6 tools_3.4.3     yaml_2.1.16     jsonlite_1.5   
 [8] digest_0.6.15   xtable_1.8-2    httpuv_1.3.5    mime_0.5   
```

Are there special considerations I should take into account when using shiny with functions that depend on Rcpp's `RNGScope`?

**Comment by asardaes** [comment] 2018-02-23 15:57
In my R package I export my C++ functions manually, without depending on Rcpp attributes, and if I manually call `GetRNGstate()` and `PutRNGstate()` instead of depending on `Rcpp::RNGScope`, the random state gets updated as expected.

**Comment by wch** [comment] 2018-02-23 16:38
The random seed handling can be slightly different inside a Shiny application. Here's a summary of the issue, as I understand it: R has an "true" internal random seed, which it uses for random number generation, and it has a publicly visible face for the random seed, which is the `.Random.seed` variable accessible from R. Those two are not always in sync.

When you write C code that uses R's internal RNG, you need to call `PutRNGstate()` in order to copy the internal seed over to the `.Random.seed` variable. Similarly, calling `GetRNGstate()` will copy the `.Random.seed` over to the internal seed. See http://www.hep.by/gnu/r-patched/r-exts/R-exts_132.html for more about this.

Rcpp puts a veneer over this so users (usually) don't have to do anything special. Usually when you call an Rcpp C++ function, it calls `GetRNGstate()` to copy `.Random.seed` over to the internal seed. When it exits that function, it calls `PutRNGstate()` copy the intenral seed to `.Random.seed`. However, if that Rcpp function calls more functions, it won't run `GetRNGstate()` or `PutRNGstate()` because Rcpp [keeps track](https://github.com/RcppCore/Rcpp/blob/0069f0b0/src/api.cpp#L71-L88)  of the call depth.

In the case of your shiny app, the `server` function is called by Rcpp, so when `rng()` is called, it's already in an Rcpp function call, and doesn't bother to call `GetRNGstate()` or `PutRNGstate()` when entering or exiting `rng()`.

In your code, if you call `GetRNGstate()` at the beginning of your function and `PutRNGstate()` right before returning, it will fix the problem. I don't think you need to get rid of the Rcpp attributes for that to work.

**Comment by asardaes** [comment] 2018-02-23 18:35
The main problem is the discrepancy between the behavior of `rng()` when called outside or inside the app. Regardless of how Rcpp works internally, I would expect that (at least when using Rcpp attributes), the `.Random.seed` should be modified when calling random functions inside C++. This is indeed the behavior outside the shiny app, but not inside.

In other words, in the next code, I would expect `seed1`, `seed2` and `seed3` to be different from each other, but this is not the case within the shiny app.

```r
# same Rcpp code as above...

seed1 <- .Random.seed
invisible(rng())
seed2 <- .Random.seed
identical(seed1, seed2) # FALSE
runif(1,1,10)
seed3 <- .Random.seed
identical(seed2, seed3) # FALSE

shiny::runApp(shiny::shinyApp(
    ui = fluidPage(
        h1("Test")
    ),
    server = function(input, output, session) {
        seed1 <- .Random.seed
        invisible(rng())
        seed2 <- .Random.seed
        runif(1,1,10)
        seed3 <- .Random.seed
        cat("same seeds? ", identical(seed1, seed2), "\n") # TRUE
        cat("same seeds again? ", identical(seed2, seed3), "\n") # FALSE
    }
))
```

**Comment by asardaes** [comment] 2018-02-23 18:43
And for completeness, changing the `rng` function to the following yields the expected results both outside and inside the app:

```r
code <- '
#include <Rcpp.h>

// [[Rcpp::export(rng=false)]]
Rcpp::NumericVector rng() {
    GetRNGstate();
    Rcpp::NumericVector ret(2);
    ret[0] = R::runif(1,10);
    ret[1] = R::runif(1,10);
    PutRNGstate();
    return ret;
}
'
```

I'm not sure if this is related to shiny or more to Rcpp, maybe @eddelbuettel has some insight?

**Comment by eddelbuettel** [comment] 2018-02-23 18:53
We support interfacing `set.seed()` and take care of details.  This worked for many years of shiny and Rcpp use. 

If you insist on playing with `seed1 <- .Random.seed` you may have to slay a few dragons yourself.  Do you really need to?

**Comment by asardaes** [comment] 2018-02-23 18:59
I don't want to play directly with `.Random.seed`, that's just for debugging. The problem is that my supposedly random shiny app is displaying the same random pattern because the random state within the shiny app is apparently not updated by `RNGScope`.

**Comment by wch** [comment] 2018-02-23 18:59
@asardaes I understand that it would be best if behavior is the same inside and outside a shiny app, but that may not be within our control, because of the global counter that Rcpp uses. We will investigate it some more, though.

**Comment by asardaes** [comment] 2018-02-23 19:02
If the incompatibility is unavoidable, that's fine, but then the explicit usage of `Get/PutRNGstate()` for C++ code that will run within shiny should be documented.

**Comment by wch** [comment] 2018-02-23 19:03
@asardaes If you could provide a minimal example of the problem you're facing, with the same random pattern being shown, that would be helpful. I suspect that might fixable in shiny, even if the one you described above is not.

**Comment by eddelbuettel** [comment] 2018-02-23 19:15
I am really not sure what Rcpp could/would have to with:   calls to Rcpp function a _synchronous_ as is just about anything else. Before the call, and after, we take care of the state. 

@asardaes "the explicit usage of Get/PutRNGstate() for C++ code ... should be documented"  It is.  

@wch What would be the global counter here?  Nothing comes to my mind.

**Comment by wch** [comment] 2018-02-23 19:59
@eddelbuettel I'm thinking of [`RNGScopeCounter`](https://github.com/RcppCore/Rcpp/blob/0069f0b0/src/api.cpp#L68). When Shiny runs its various callbacks, they are (indirectly) called from Rcpp, so it is already in an `RNGScope`. So when one of these callbacks calls another Rcpp function, the additional `RNGScope` doesn't trigger Get/PutRNGstate().

Here's a simplified example:

```R
library(Rcpp)

cppFunction('
  Rcpp::NumericVector rng() {
    return R::runif(1,10);
  }
')

cppFunction('
  Rcpp::RObject invoke(Rcpp::Function f) {
    return f();
  }
')

f <- function() {
  seed1 <- .Random.seed
  invisible(rng())
  seed2 <- .Random.seed
  identical(seed1, seed2)
}

f()  # FALSE

invoke(f) # TRUE
```

The last line, `invoke(f)`, is analogous to what is happening in Shiny.

**Comment by eddelbuettel** [comment] 2018-02-23 20:04
Don't like the example as `.Random.seed` mucking calls for trouble, and using `Rcpp::Function()` is _obviously_ a way to run circles around our treatment of `Get/PutRNGState()`.

But the counter reminder is a good.  Maybe users who need this have to putz around with direct calls to get `Get/PutRNGState()`.      

I really don't know.  Shiny and its reactivity are a wee bit complicated.   But to close this, I do not see how anything in Rcpp should change....

**Comment by asardaes** [comment] 2018-02-23 20:13
@wch Thanks, that example made me understand the behavior of `rng`. 

I meant that perhaps shiny should also document this, but maybe it already is documented? I couldn't find it.

**Comment by jcheng5** [comment] 2018-02-23 20:31
@eddelbuettel This example at least doesn't directly refer to `.Random.seed` at all, but demonstrates that calling `rng()` doesn't have the expected side effect of changing it.

```r
library(Rcpp)

cppFunction('
  Rcpp::NumericVector rng() {
    return R::runif(1,10);
  }
')

cppFunction('
  Rcpp::RObject invoke(Rcpp::Function f) {
    return f();
  }
')

f <- function() {
  set.seed(100)
  a <- runif(1)
  invisible(rng())
  
  set.seed(100)
  invisible(rng())
  b <- runif(1)

  identical(a, b)
}

f()  # FALSE

invoke(f) # TRUE
```

I assume the reason `Get/PutRNGState()` are only performed when not already in an `RNGScope`, is because of performance? You could create an `InverseRNGScope` class that temporarily resets the refcount to 0, and anywhere in our C++ code we call back to arbitrary user R code, we could use one of those...?

**Comment by wch** [comment] 2018-02-23 20:31
@asardaes It's not documented anywhere, but perhaps it should be. I'll reopen the issue.

As Rcpp and Shiny (and other async programming in R) gain in popularity, I think we'll see these problems more and more. I'll file an issue on Rcpp for discussion there.

**Comment by eddelbuettel** [comment] 2018-02-23 20:41
@jcheng5 You may have missed what I said about `Rcpp::Function()`.  If you call back, and things break, you get to keep the pieces.

@wch Come on.  We have been using Rcpp-based code on shiny on multiple servers with multiple user over multiple years with an issue.

**Comment by wch** [comment] 2018-02-23 21:05
@eddelbuettel The reason you haven't seen problems is because we worked around them. #1763, #1768.

**Comment by eddelbuettel** [comment] 2018-02-23 21:09
@wch Or maybe I didn't rely on randomization _and_ callbacks of R functions ?

**Comment by jcheng5** [comment] 2018-02-23 21:16
Just to be clear, the issue wouldn't be that you don't get random numbers is Shiny apps (that obviously would be a show stopper!). It'd be that if you mix C++ and R based RNG from within Shiny code, your results would simply be _different_ than if you ran that same code outside of Shiny (even if you started out with the same seed). Right, @asardaes?

Any user R code that ever runs in httpuv or Shiny is being called back from Rcpp; the web server is written in C after all. So we have all probably been relying on randomization and callbacks of R functions; but few people probably care that their results are reproducible inside of and outside of a Shiny app.

@eddelbuettel I think we should start by trying to work around this in httpuv/shiny, and if we're not successful there (or learn enough to make a useful suggestion) then we'll loop back with you. Does that sound fair?

**Comment by eddelbuettel** [comment] 2018-02-23 21:48
@jcheng5 Yes, that's what my (edited, may have done that right when you wrote this) comment was trying to get at.

We have a nice a convenience tool in Rcpp::Attributes but we may need to bypass it.  And I am with you: full reproducibility of (RNG-using) Shiny code may not be the most important thing in the world, but it would still be nice to get to it eventually.

**Comment by jcheng5** [comment] 2018-02-23 21:55
Yeah, we think that's the path that makes the most sense too. To be continued...

**Comment by wch** [comment] 2018-02-23 22:10
A minimal test app:

```R
library(Rcpp)
library(shiny)

cppFunction('
  double rng() {
    return R::runif(0,1);
  }
')

shinyApp(
  fluidPage(
    h4("These should be different:"),
    verbatimTextOutput("x"),
    verbatimTextOutput("y")
  ),
  server = function(input, output) {
    output$x <- renderText({
      set.seed(100)
      a <- runif(1)
      rng()
      a
    })

    output$y <- renderText({
      set.seed(100)
      rng()
      b <- runif(1)
      b
    })
  }
)
```

**Comment by asardaes** [comment] 2018-02-23 22:26
@jcheng5 I think it can be problematic. My app is meant to be used interactively in RStudio, and it performs clustering in the background. The app will provide a way of saving the results to the current R session, and I have another function to reproduce the results programmatically, but reproducibility wouldn't be ensured if I'm not careful with the handling of seeds and random states.

**Comment by eddelbuettel** [comment] 2018-02-23 22:36
If it is this paramount, you could use a different RNG source.

**Comment by asardaes** [comment] 2018-02-23 23:13
Calling `GetRNGstate` and `PutRNGstate` is sufficient for my needs, I just didn't know I had to do it until I noticed a pattern repeating itself (since I was relying on `RNGScope`).

**Closed** 2018-04-10 17:30 UTC
