### ISSUE TITLE
Updating selection of server-side selectize input with >1000 choices fails

### ISSUE THREAD

**Issue by nicolaromano** [rstudio/shiny#2760] opened 2020-02-17 15:27 UTC
I have a shiny app containing a server-side selectize input with a long list (>10k) of choices. I would like to update the selection upon clicking a button. Here is a reproducible example

```
library(shiny)

ui <- fluidPage(
  actionButton('buttonid','Button'),

  selectizeInput("listid", "A long list", choices = NULL)
  )

server <- function(input, output, session) 
  {
  updateSelectizeInput(session, "listid", choices = paste("Item", 1:10000), server = T)
  observeEvent(input$buttonid,
               {
               updateSelectizeInput(session, "listid", selected = "Item 1234")
               })
  }

shinyApp(ui = ui, server = server)
```

The above code results in a blank selection when I press the button. However, if I search for "Item 1234", then change the selection, and press the button, now the item gets selected.

Also, trying to select an item between Item 1 and 1000 does not give problems, presumably because 1000 items get loaded at the beginning.

This seems akin to this old bug https://github.com/rstudio/shiny/issues/1018

**Comment by adamsma** [comment] 2020-02-21 17:48
Not sure if it's a feature or a bug, but work around is specifying `server = TRUE` and `choices = paste("Item", 1:10000)` in update call. 

Some more details on tracing cause in [SO response](https://stackoverflow.com/questions/60264119/updating-selection-of-server-side-selectize-input-with-1000-choices-fails/60343776#60343776).

**Comment by stla** [comment] 2020-07-05 01:24
That's normal. The default value of the `maxOptions` option of `selectize.js` is 1000.

```
  updateSelectizeInput(
    session, "listid", choices = paste("Item", 1:10000), server = TRUE, 
    options = list(maxOptions = 10000)
  )
```

**Comment by cpsievert** [comment] 2020-08-18 16:31
Closing since this seems to be expected behavior (note you can also set `maxOptions` in `selectizeInput()`)

**Closed by cpsievert** 2020-08-18 16:31 UTC
Labels: UI toolkit: selectInput

**Comment by tyluRp** [comment] 2021-04-05 20:49
I have a particular use case where a user can copy and paste a bunch of values that are fed to `selectizeInput`. However, it seems that since I have to provide the choices, there is a pretty significant delay, especially if there are a lot of choices. The example below takes awhile with 20,000 choices. I am curious if anyone has a trick to make this faster as I have been struggling to find a dropdown in shiny that can support my use case.

```r
library(shiny)

choices <- sort(unique(babynames::babynames$name))[1:20000]

ui <- fluidPage(
  selectizeInput(
    inputId = "babyname",
    label = "Baby Name", 
    multiple = TRUE, 
    choices = character(0),
    options = list(maxOptions = 1000)
  ),
  actionButton("go", "go")
)

server <- function(input, output, session) {
  updateSelectizeInput(
    session = session, 
    inputId = "babyname", 
    choices = choices, 
    server = TRUE
  )
  
  observeEvent(input$go, {
    updateSelectizeInput(
      session = session, 
      inputId = "babyname", 
      selected = last(choices), 
      choices = choices
    )
  })
}

shinyApp(ui, server)
```
