### ISSUE TITLE
updateSliderInput doesn't adjust step size

### ISSUE THREAD

**Issue by gzgreg** [rstudio/shiny#801] opened 2015-04-16 19:08 UTC
Repro:

```
#ui.R
shinyUI(fluidPage(
  sliderInput("test", "Test", 1, 100, 2)
))
#server.R
shinyServer(function(input, output, session){
  updateSliderInput(session, "test", max=2)
})
```

This results in pretty strange labeling. The default behavior of sliderInput is to use a heuristic to determine step size if it's missing: it seems logical to use the same heuristic if step's missing in updateSliderInput as well.

**Comment by wch** [comment] 2015-07-01 19:17
Hm, I think this is going to be tricky to fix. The problem is that normally there are various `sliderInput` parameters (like step size) calculated on the server side, but there's no state recorded on the server, so when you call `updateSliderInput` there's not enough information to calculate step size. It might be necessary to move all of that calculation into the client.

**Comment by alandipert** [comment] 2019-04-26 15:35
I was still able to reproduce this using an updated example:
```R
ui <- fluidPage(
  sliderInput("test", "Test", 1, 100, 2)
)

server <- function(input, output, session){
  updateSliderInput(session, "test", max=2)
}

shinyApp(ui, server)
```
![Screen Shot 2019-04-26 at 8 32 48 AM](https://user-images.githubusercontent.com/26024/56819121-f10c1b00-67fd-11e9-9d26-3d49966bf1fb.png)

This can be worked-around with `renderUI`:

```R
ui <- fluidPage(
  uiOutput("sliderWrapper"),
  actionButton("update", "Update Slider")
)

server <- function(input, output, session){
  output$sliderWrapper <- renderUI({
    sliderInput("test", "Test", 1, 100, 2)
  })
  observeEvent(input$update, {
    output$sliderWrapper <- renderUI({
      sliderInput("test", "Test", 1, 2, 2)
    })
  })
}

shinyApp(ui, server)
```
![slider](https://user-images.githubusercontent.com/26024/56819284-40eae200-67fe-11e9-9879-f9f5b1684222.gif)

**Comment by alandipert** [comment] 2019-04-26 16:26
I just realized this is a dupe of #2398, so closing.

**Closed by alandipert** 2019-04-26 16:26 UTC
Labels: Difficulty: Advanced, Effort: High, Priority: Low, Type: Bug :bug:
