### ISSUE TITLE
comparing null objects in 3.4 & shiny hot fix

### ISSUE THREAD

**Issue by smartinsightsfromdata** [rstudio/shiny#1682] opened 2017-04-25 21:36 UTC
I am a bit puzzled by what is happening to my `shiny` code :(

I've just installed latest `shiny 1.0.2.9000` and I'm on `R 3.4`.

If I run this code in R all is fine:
```
a <- matrix(integer(), nrow = 0, ncol = 2,dimnames = list(NULL,c("row" ,"col")))
if( length(a) == 0) print(1)
[1] 1
```
If I run (within a `browser()` session the above code in `shiny` I get the same result.

But if I run the following within a reactive function:
```
a <- matrix(integer(), nrow = 0, ncol = 2,dimnames = list(NULL,c("row" ,"col")))
if( length(a) == 0) return()
```

I get the following `new` warning in `R 3.4`  (thank you `R core` folks!)
```
Warning in structure(x, class = unique(c("AsIs", oldClass(x)))) :
  Calling 'structure(NULL, *)' is deprecated, as NULL cannot have attributes.
  Consider 'structure(list(), *)' instead.
```
I tried different things, but I do not seem to be able to get rid of it, so I end up with lots of warnings in `R` console.

Why only in shiny?  but more importantly, how to avoid it??

**Comment by jcheng5** [comment] 2017-04-25 21:46
I'm not getting a repro here (Mac)--can you provide a runnable example?

**Comment by bborgesr** [comment] 2017-04-25 21:54
I tried this and also couldn't get a repro:

```r
library(shiny)

ui <- fluidPage(
  actionButton("go", "Go")
)

server <- function(input, output, session) {
  r <- reactive({
    a <- matrix(integer(), nrow = 0, ncol = 2,dimnames = list(NULL,c("row" ,"col")))
    if( length(a) == 0) return(1)
  })
  
  observe({
    input$go
    print(r())
  })
}

shinyApp(ui, server)
```

It always prints `[1] 1` as expected.

<details>
  <summary>Here's the session info</summary>

   ```r
	> devtools::session_info()
	Session info --------------------------------------------------------------------
	setting  value                       
	version  R version 3.4.0 (2017-04-21)
	system   x86_64, darwin15.6.0        
	ui       RStudio (1.1.211)           
	language (EN)                        
	collate  en_US.UTF-8                 
	tz       Europe/Lisbon               
	date     2017-04-25                  

	Packages ------------------------------------------------------------------------
	package    * version    date       source                            
	devtools     1.12.0     2016-06-24 CRAN (R 3.4.0)                    
	digest       0.6.12     2017-01-27 cran (@0.6.12)                    
	htmltools    0.3.5      2016-03-21 CRAN (R 3.4.0)                    
	httpuv       1.3.3      2015-08-04 CRAN (R 3.4.0)                    
	jsonlite     1.4        2017-04-08 cran (@1.4)                       
	memoise      1.0.0      2016-01-29 CRAN (R 3.4.0)                    
	mime         0.5        2016-07-07 CRAN (R 3.4.0)                    
	R6           2.2.0      2016-10-05 CRAN (R 3.4.0)                    
	Rcpp         0.12.8     2016-11-17 CRAN (R 3.4.0)                    
	rsconnect    0.7.0-2    2017-04-24 Github (rstudio/rsconnect@425f376)
	rstudioapi   0.6        2016-06-27 CRAN (R 3.4.0)                    
	shiny      * 1.0.2.9000 2017-04-24 Github (rstudio/shiny@af8d099)    
	withr        1.0.2      2016-06-20 CRAN (R 3.4.0)                    
	xtable       1.8-2      2016-02-05 CRAN (R 3.4.0)                    
	yaml         2.1.14     2016-11-12 CRAN (R 3.4.0)                    
   ```

</details>

**Comment by smartinsightsfromdata** [comment] 2017-04-25 21:57
This is the code that generates the warning.  Please note that this code doesn't do anything else than generate the warning (i.e. nothing is displayed etc.).

```
library(shiny)
library(DT)

ui <- fluidPage( DT::dataTableOutput('changes'))


server <- function(input, output,session) {


output$changes <- DT::renderDataTable({ 

df1 <- df2 <- data.frame(Parameter=c('A','B','C'),Min=c(10,20,30),
                                          Max=c(20,30,40),
                                          stringsAsFactors = F)

# dfa <- matrix(integer(), nrow = 0, ncol = 2,dimnames = list(NULL,c("row" ,"col")))

dfm  <- which(df1 != df2, arr.ind=TRUE)

if( length(dfm) == 0 ) return()

DT::renderDataTable(dfm)

})

}

shinyApp(ui, server)
```

**Comment by smartinsightsfromdata** [comment] 2017-04-25 22:11
Incidentally, I run  @bborgesr code with no warnings or errors.

It is the `return()` that triggers the warning (e.g. when I debug with `browser()` )

**Comment by bborgesr** [comment] 2017-04-25 22:16
This seems to be a problem with the return statement of `DT::renderDataTable`. Here's the minimal repro:

```r
library(shiny)
library(DT)

ui <- fluidPage(DT::dataTableOutput('changes'))

server <- function(input, output, session) {
  output$changes <- DT::renderDataTable({ 
    return()
  })
}

shinyApp(ui, server)
```

cc: @yihui

**Comment by jcheng5** [comment] 2017-04-25 22:33
I get the same with leaflet. I think this'll need to be fixed in htmlwidgets.

**Comment by bborgesr** [comment] 2017-04-25 23:56
The issue is htmlwidgets is here: https://github.com/ramnathv/htmlwidgets/issues/269 (and a possible fix here: https://github.com/ramnathv/htmlwidgets/pull/270)

**Comment by wch** [comment] 2017-05-04 19:03
Closing here because the issue is in other packages.

**Closed by wch** 2017-05-04 19:03 UTC

**Comment by bklingen** [comment] 2017-05-10 21:16
This issue seems to have serious (aborting R) consequences (and must break many apps, including mine) when returning ``NULL`` in a renderPlot. **Running the following in R 3.4 will crash R!** (Running it in R 3.3 works just fine.)
```{r}
library(shiny)
ui <- fluidPage(
  plotOutput("plot")
)

server <- function(input, output) {
  output$plot <- renderPlot({
    return(NULL)
  })
}

shinyApp(ui = ui, server = server)
```

**Comment by jcheng5** [comment] 2017-05-10 21:36
@bklingen This is likely https://github.com/rstudio/shiny/issues/1695, not an issue in Shiny per se but the result of your packages being compiled against R 3.3 but now being used with R 3.4. Most version changes for R happen to be binary-compatible, but occasionally they change something (as is their right).

If you don't mind your packages being updated to the latest versions, you can run `https://github.com/rstudio/shiny/issues/1695`. If it's important to stay on the current versions of your installed packages, then I'd stay on R 3.3 for now; @wch is working on a script to rebuild your packages for R 3.4 while keeping the same package versions, that should be coming out in the next few days.

**Comment by bklingen** [comment] 2017-05-10 21:51
OK, I will just stay on R 3.3 for now. Thanks!

**Comment by bklingen** [comment] 2017-05-10 21:58
... but just to confirm, running

``update.packages(ask = FALSE, checkBuilt = TRUE)``

in R 3.4 does remove the problem as I have just checked.
