### ISSUE TITLE
two iframes  cause problem to the height of the second? - version 0.10.2.9006 (Bug?) 

### ISSUE THREAD

**Issue by smartinsightsfromdata** [rstudio/shiny#678] opened 2014-12-19 21:35 UTC
(apologies for bad formatting)

I have a "complex" UI page with 2 iframe that I size with div etc.

The second iframe (which should be only one single long row dynamic UI component) height appears cut in half and does not respond to 'height:' instructions. 

The problem is with version 0.10.2.9006 but I suspect it was there with older versions.
This is the UI code:

```R
 library(shiny)
suppressPackageStartupMessages(library(ggvis))
library(shinyhdtable)
shinyUI(fluidPage(

  fluidRow(column(3,
    selectInput("inputTime", label=NULL, choices= slTime, selected = NULL
                , multiple = FALSE, selectize = TRUE))
 
  ),
  conditionalPanel("input.inputTime == 'year by month'",  
  tabsetPanel(
    tabPanel("Overview PPU",
        fluidPage( 
         verticalLayout( fluidRow( column(2
                   , selectInput("inputLPA", label=NULL, choices= selLPA, selected = "H"
                , multiple = FALSE, selectize = TRUE))
                   , column(1, actionButton( "pivotButton","Pivot"))
      , column(3, actionButton( "resetButton","Reset")
                , actionButton("saveButton", "Update Model"))
      , column(4, textInput("caption", label=NULL, "Save comments"))  )
               
             , fluidRow(
                 column(10 
                        , div(style='height:250px; width:700px; overflow: scroll'
                              , hdtable('hdtablePpu')
                        ))
                 , column(2
                          , uiOutput("outPpu")) ) )
       , verticalLayout(br(),fluidRow( column(12,  "Spread value(s) over the following period:"))
             ,  fluidRow(br(),column(12
       (next line is  intended to be in the code, but with it is commented out to avoid to have the row cut in the middle 
(#) , div(style='height:300px; width:700px; overflow-x: scroll' 
                        , checkboxGroupInput("monthIdppu", label=NULL
                          , month.abb[1:12] , selected = c("Jan","Apr") , inline = TRUE))))
           	  

             )),
    tabPanel("Activity"), 
    tabPanel("Resource"),
    tabPanel("FTE Assign")          
  )) # end of tabset panel

))
```

**Comment by wch** [comment] 2015-01-05 17:09
Can you supply a reproducible example -- an app that others can run? You can write it as a [single-file app](http://shiny.rstudio.com/articles/single-file.html).

**Comment by smartinsightsfromdata** [comment] 2015-01-09 18:31
Please see attached example.  It is problematic in two ways:
1. It cuts the top of the first row of letters in the checkboxGroupInput
2. It breaks the line into two lines: I would rather have one line with the ability to scroll (which I thought the div(style etc. was going to give me, as it does for the table.

Please note that I used the div(style also for the DataTable (even if it has its own scrolling settings) as in real life I'm using another component and this reflects more closely my situation.

(apologies for the poor formatting)

library(shiny)

#
df_ = data.frame( Month = month.abb[1:5],
A=rnorm(5, mean = 5, sd = 4),
B=rnorm(5, mean = 5, sd = 4),
C=rnorm(5, mean = 5, sd = 4),
D=rnorm(5, mean = 5, sd = 4),
E=rnorm(5, mean = 5, sd = 4),
F=rnorm(5, mean = 5, sd = 4),
G=rnorm(5, mean = 5, sd = 4),
H=rnorm(5, mean = 5, sd = 4),
I=rnorm(5, mean = 5, sd = 4),
J=rnorm(5, mean = 5, sd = 4),
K=rnorm(5, mean = 5, sd = 4),
L=rnorm(5, mean = 5, sd = 4),
M=rnorm(5, mean = 5, sd = 4),
N=rnorm(5, mean = 5, sd = 4), stringsAsFactors=F)


df_$id <- 1:nrow(df_)

shinyApp(
  ui = fluidPage( 
  
  tabsetPanel(
    tabPanel("Overview PPU",
        fluidPage(
         verticalLayout( fluidRow( column(2
                , selectInput("inputLPA", label=NULL, choices= letters[1:5], selected = "H"
                , multiple = FALSE, selectize = TRUE))
                   , column(1, actionButton( "pivotButton","Pivot"))
      , column(3, actionButton( "resetButton","Reset")
                , actionButton("saveButton", "Update Model"))
      , column(4, textInput("caption", label=NULL, "Save comments"))  )

             , fluidRow(
                  column(6, 
                         div(style='height:350px; width:500px; overflow: scroll' 
                             ,dataTableOutput('DT')))
                 , column(2 , uiOutput("outPpu")) )
             , fluidRow( column(12, 
                  "Spread value(s) over the following period:"))
             ,  fluidRow(br(),column(12
                  , div(style='height:350px; width:700px; overflow: scroll'       
                       , checkboxGroupInput("monthIdppu", label=NULL
                          , letters , selected = c("a","c") , inline = TRUE))))


             ))),
    tabPanel("Activity"), 
    tabPanel("Resource"),
    tabPanel("FTE Assign")          
  ) # end of tabset panel
),

  server = function(session,input, output) {
output$DT <- renderDataTable({ 
  df_
  }, options = list(
  # scrollX = TRUE,
  # scrollY = "250px" ,
  # scrollCollapse = TRUE,
  paging = FALSE,
  searching = FALSE,
  ordering = FALSE )
)
  }
)

**Comment by wch** [comment] 2015-01-09 18:35
A quick note about formatting: You can use ```` ```R ```` to start the code block and ```` ``` ```` to end it. I edited your comment added those; you'll see them if you edit your comment now. See https://guides.github.com/features/mastering-markdown/ for more information about formatting.

**Comment by wch** [comment] 2015-01-09 21:00
For the issue of checkboxes getting their top cut off, it happens when there's no label for the checkboxGroup. I just pushed a fix for that to the development version of Shiny.

To disable wrapping, you'll also need 'white-space: nowrap'. So you'd have something like:

```
style='height:350px; width:700px; overflow: scroll; white-space: nowrap;' 
```

But you still need more than that. Because Bootstrap uses `position:absolute` for inline checkboxes, the checkboxes themselves won't scroll, even though the labels wil. You need to add some CSS to override this behavior for checkboxes. Something like this:

```css
.checkbox-inline input[type=checkbox] {
  position: static;
}
```

See [this article](http://shiny.rstudio.com/articles/css.html) for information on how to add CSS to a Shiny app. If you have just a small amount of CSS, the simplest way is to use the "Add CSS to the header with `tags`" method described on that page.

You can experiment with CSS properties of page elements by right-clicking on them in your browser, and choosing "Inspect Element".

An aside: these are issues that are happening within divs, not iframes. An iframe is a view to another URL -- essentially a nested browser window to a different page.

**Closed by wch** 2015-01-09 21:00 UTC

**Comment by smartinsightsfromdata** [comment] 2015-01-10 15:07
Thanks Winston, for the fix as well as for the learning!
