### ISSUE TITLE
`min` and `max` not enforced in `numericInput()`

### ISSUE THREAD

**Issue by ms609** [rstudio/shiny#3689] opened 2022-08-27 04:19 UTC
### System details

Output of `sessionInfo()`:

```
R Under development (unstable) (2022-07-19 r82607 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.utf8  LC_CTYPE=English_United Kingdom.utf8   
[3] LC_MONETARY=English_United Kingdom.utf8 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_1.7.2

loaded via a namespace (and not attached):
 [1] microbenchmark_1.4.9 cli_3.3.0            rlang_1.0.4          stringi_1.7.8       
 [5] promises_1.2.0.1     jsonlite_1.8.0       xtable_1.8-4         htmltools_0.5.3     
 [9] httpuv_1.6.5         sass_0.4.2           jquerylib_0.1.4      ellipsis_0.3.2      
[13] fastmap_1.1.0        lifecycle_1.0.1      memoise_2.0.1        stringr_1.4.0       
[17] compiler_4.3.0       htmlwidgets_1.5.4    Rcpp_1.0.9           rstudioapi_0.13     
[21] later_1.3.0          digest_0.6.29        R6_2.5.1             magrittr_2.0.3      
[25] bslib_0.4.0          tools_4.3.0          withr_2.5.0          mime_0.12           
[29] profvis_0.3.7        cachem_1.0.6    
```

### Example application *or* steps to reproduce the problem

```R
shinyApp(
  ui = fluidPage(
    numericInput("number", "Insert a number from 5 to 10",
                 min = 5, max = 10, value = 7),
    htmlOutput("display")
  ), 
  server = function(input, output) {
    output$display <- renderUI(input$number)
  })
```

### Describe the problem in detail

`numericInput()` documents `min` and `max` as the minimum and maximum allowed values.  I interpret this to mean that `numericInput(min = 5, max = 10)` will return a value in the range 5–10. Whilst this is guaranteed to be the case for a `sliderInput`, it is not for `numericInput`.  Clearing the contents of the box and pressing 'enter' results in an `NA` value; manually typing a number larger than 10 results that number.  As such, it is necessary to manually validate the contents before using them – I have encountered app crashes when a user supplies out-of-range values.

```r
server = function(input, output) {
  ValidatedNumber <- reactive({
    min(10, max(5, as.numeric(input$plottedChar), na.rm = TRUE))
  })
  output$display <- renderUI(ValidatedNumber())
})
```

### Proposed solutions

1. Could this validation be performed by shiny before returning `input$number`?
2. If not, could the documentation be updated to make clear that `min` and `max` only apply to the javascript control, and are not guaranteed?

### Further note

Perhaps a similar argument applies to the `step` parameter, though the current documentation does make clear that this is only applied "when stepping between min and max".

**Comment by ismirsehregal** [comment] 2022-08-29 07:07
This is a duplicate of https://github.com/rstudio/shiny/issues/927

Please see this comment on [shinyvalidate](https://rstudio.github.io/shinyvalidate/):

https://github.com/rstudio/shiny/issues/927#issuecomment-849664075

**Closed** 2022-09-12 16:30 UTC
