### ISSUE TITLE
Heatmap, leaflet & shiny

### ISSUE THREAD

**Issue by Stophface** [rstudio/shiny#1044] opened 2015-12-21 14:22 UTC
Sorry for corssposting: https://github.com/rstudio/leaflet/issues/223
Not sure where to post this since I stumbled over a post here which was Shiny related: https://groups.google.com/forum/#!topic/shiny-discuss/Im_I_f_46MM

I want to include this heatmap (https://github.com/Leaflet/Leaflet.heat) as a layer on my leaflet map in `R`.

Currently I am drawing the leaflet map for a shiny app in `js` and include this in my `R` files. I am aware of sending the data between `js` and my `R-Shiny` scripts like so

    newPoints<- cbind(lat,lng)
        session$sendCustomMessage(type = "myCallbackHandler", newPoints)

My `js`

        Shiny.addCustomMessageHandler("myCallbackHandler",function(newPoints) {
            var addressPoints = newPoints;
            console.log(addressPoints);
            heat = window.myHeat;
            heat.setLatLngs(addressPoints);
          });

Here I overlay the heatmap on leaflet.

        var heat = L.heatLayer(addressPoints).addTo(map);

However, I want to draw my leaflet map in `R` completeIy. But, I dont want to use `rMaps`. I am aware of this: http://rmaps.github.io/blog/posts/leaflet-heat-maps/index.html
Using rMaps, I would use a lot of the functionality of leaflet shiny I guess?!
So, how would I overlay the heatmap on a leaflet map, drawn in `R`! Is there a way to do this?

**Comment by jcheng5** [comment] 2016-08-10 18:03
Closing as dupe of rstudio/leaflet#223

**Closed** 2016-08-10 18:03 UTC
